import { useEffect, useRef } from 'react'
import type { Instruction } from './api'
import { useDisassembly } from './useDisassembly'
import type { DisassemblySource } from './useDisassembly'

export type { DisassemblySource } from './useDisassembly'

type Props = {
  label: string
  source: DisassemblySource
  // Same byte range BinaryDiff highlights in the Original column -- reused
  // here to highlight/scroll to whichever instructions fall in that range.
  // Best-effort on the recompiled side: real-compiler byte offsets aren't
  // guaranteed to line up with tbx's own addressing.
  highlightRange?: [number, number] | null
  // Top-level BASIC statements with the byte offset each decoded from
  // the ORIGINAL exe, source order. Used to annotate instructions with the
  // source line that produced them -- the inverse of EditTab's binary-side
  // highlight. Passed to the recompiled pane too as a best-effort: these
  // are the original exe's addresses, but wherever the recompiled binary
  // is still byte-identical to it (everywhere before firstDiffOffset),
  // the same address means the same statement in both.
  statements: { address: number; text: string }[]
}

// One entry per instruction: the BASIC source line that instruction came
// from, or null if it's the same statement as the previous instruction (so
// the comment only prints once, at the first instruction of each
// statement) or before any statement starts (the compiler's fixed
// per-program preamble, which isn't generated by any BASIC line).
export function buildStatementComments(
  instructions: Instruction[],
  statements: { address: number; text: string }[]
): (string | null)[] {
  const sorted = [...statements].sort((a, b) => a.address - b.address)
  let cursor = 0
  let current: string | null = null
  let prev: string | null = null
  const comments: (string | null)[] = []
  for (const ins of instructions) {
    while (cursor < sorted.length && sorted[cursor].address <= ins.address) {
      current = sorted[cursor].text
      cursor++
    }
    comments.push(current !== prev ? current : null)
    prev = current
  }
  return comments
}

// IDA-style symbolic labels for jump/call targets: `sub_XXXXXX` for a
// target only ever reached via `call`, `loc_XXXXXX` for anything reached by
// a jump (jmp/jcc) -- call wins if a target is reached both ways, since
// that's the more informative fact about the target.
export function buildLabels(instructions: Instruction[]): Map<number, string> {
  const kind = new Map<number, 'sub' | 'loc'>()
  for (const ins of instructions) {
    if (ins.target == null) continue
    const isCall = ins.text.trimStart().startsWith('call')
    const prev = kind.get(ins.target)
    if (prev !== 'sub') kind.set(ins.target, isCall ? 'sub' : 'loc')
  }
  const labels = new Map<number, string>()
  for (const [addr, k] of kind) {
    labels.set(addr, `${k}_${addr.toString(16)}`)
  }
  return labels
}

// Replace the raw hex operand of a jump/call instruction with its symbolic
// label, e.g. "jnz 0a3fh" -> "jnz loc_a3f". Falls back to the original text
// when there's no operand to split off (shouldn't happen once target is set,
// but decode_insns' output is trusted input, not reason to crash the panel).
export function withLabel(text: string, label: string | undefined): string {
  if (!label) return text
  const space = text.indexOf(' ')
  if (space < 0) return text
  return text.slice(0, space + 1) + label
}

export default function Disassembly({ label, source, highlightRange, statements }: Props) {
  const { instructions, error } = useDisassembly(source)
  const containerRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!highlightRange || !instructions) return
    const index = instructions.findIndex(
      (ins) => ins.address >= highlightRange[0] && ins.address < highlightRange[1]
    )
    if (index < 0) return
    containerRef.current?.querySelector(`[data-insn="${index}"]`)?.scrollIntoView({ block: 'center' })
  }, [highlightRange, instructions])

  if (error) {
    // iced-x86 (the `debug` extra) isn't installed -- not a real error for
    // users who don't need disassembly, just an unavailable feature.
    return <p style={{ opacity: 0.6, fontSize: '12px' }}>Disassembly unavailable: {error}</p>
  }

  if (!instructions) {
    return <p>Disassembling…</p>
  }

  const labels = buildLabels(instructions)
  const statementComments = buildStatementComments(instructions, statements)
  const rowForAddress = new Map(instructions.map((ins, i) => [ins.address, i]))

  function jumpTo(target: number) {
    const index = rowForAddress.get(target)
    if (index == null) return
    containerRef.current?.querySelector(`[data-insn="${index}"]`)?.scrollIntoView({ block: 'center' })
  }

  return (
    <div className="panel" style={{ flex: '1 1 30%', minWidth: 0 }}>
      <h4 style={{ margin: 0, padding: '8px 10px', borderBottom: '1px solid var(--border)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
        {label} ({instructions.length} instructions)
      </h4>
      <div
        ref={containerRef}
        style={{
          fontFamily: 'var(--mono)',
          fontSize: '12.5px',
          height: '500px',
          overflow: 'auto',
          overflowAnchor: 'none',
          padding: '6px 10px',
        }}
      >
        {instructions.map((ins, i) => {
          const highlighted =
            !!highlightRange && ins.address >= highlightRange[0] && ins.address < highlightRange[1]
          const label = labels.get(ins.address)
          const targetLabel = ins.target != null ? labels.get(ins.target) : undefined
          const statementComment = statementComments[i]
          return (
            <div key={i}>
              {statementComment && (
                <div
                  style={{
                    color: 'var(--text-dim)',
                    opacity: 0.9,
                    marginTop: i > 0 ? 10 : 0,
                    whiteSpace: 'pre-wrap',
                  }}
                >
                  ; {statementComment}
                </div>
              )}
              {label && (
                <div style={{ color: 'var(--purple)', opacity: 0.8, marginTop: i > 0 ? 6 : 0 }}>
                  {label}:
                </div>
              )}
              <div
                data-insn={i}
                style={{
                  whiteSpace: 'pre',
                  background: highlighted ? 'rgba(102, 217, 239, 0.25)' : undefined,
                  outline: highlighted ? '1px solid #66d9ef' : undefined,
                }}
              >
                <span style={{ opacity: 0.5 }}>{ins.address.toString(16).padStart(6, '0')}</span>
                {'  '}
                <span style={{ color: 'var(--orange)' }}>{withLabel(ins.text, targetLabel)}</span>
                {targetLabel && (
                  <>
                    {' '}
                    <span
                      role="button"
                      title={`Jump to ${targetLabel}`}
                      onClick={() => jumpTo(ins.target as number)}
                      style={{ color: 'var(--cyan)', cursor: 'pointer', opacity: 0.8 }}
                    >
                      ↷
                    </span>
                  </>
                )}
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}
