/* generated by tbx --emit-c : Turbo Basic recompiled to C */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <time.h>
#include <setjmp.h>
#ifdef _WIN32
/* MinGW-w64 gcc or clang (labels-as-values), not MSVC. dirent.h is shipped
   by MinGW; the termios/poll/fnmatch pieces have _WIN32 replacements below. */
#include <windows.h>
#include <conio.h>
#include <io.h>
#include <dirent.h>
#else
#include <unistd.h>
#include <fcntl.h>
#include <termios.h>
#include <dirent.h>
#include <fnmatch.h>
#include <poll.h>
#include <sys/stat.h>
#ifndef FNM_CASEFOLD
#define FNM_CASEFOLD 0
#endif
#endif

/* Devices with no modern counterpart (the screen, the speaker) are rendered
   to files instead of replicated: SCREEN dumps its framebuffer to TB_SCREEN_PPM
   and PLAY dumps its audio to TB_PLAY_WAV, each at exit. This is a surrogate,
   not the original behavior, so it is gated at compile time -- build with
   -DTB_FILE_DEVICES=0 to omit the dumps entirely and leave the devices absent
   (silent PLAY, no screen file), the way real hardware-less execution behaves. */
#ifndef TB_FILE_DEVICES
#define TB_FILE_DEVICES 1
#endif

