"""Typed statement/expression IR for the byte-exact Turbo Basic decompiler.

Nodes are immutable dataclasses and pure data; analyses pattern-match on them.
Expressions follow the grammar

    expr := "(" expr OP expr ")" | NAME "(" args ")" | NAME | NUMBER | "?"

`unparse` is the inverse of `parse_expr`: `unparse(parse_expr(s)) == s` for
every expression the decoder produces (the IR's fidelity invariant, checked by
tests/tbx/test_ir.py).

The IR is split across submodules -- `expr_nodes` / `stmt_nodes` (the dataclass
node types), `fmt` (byte-faithful float formatting), `parse`
(tokenize/parse_expr), and `render` (unparse/unparse_stmt) -- with the whole
public surface re-exported here, so `from tbx import ir; ir.Foo` resolves
every name.
"""

from tbx.ir.expr_nodes import (
    INTRINSICS,
    ArrayRef,
    BinOp,
    Call,
    CaseIs,
    CaseRange,
    CaseValue,
    DblLit,
    Erl,
    Err,
    Expr,
    FnCall,
    Group,
    HexLit,
    Lit,
    LogOp,
    Neg,
    Not,
    Nullary,
    RelOp,
    SingleLit,
    Stmt,
    StrLit,
    Unknown,
    Var,
    VarSeg,
    _PREC,
)
from tbx.ir.fmt import f32_dec, f32_enc, fmt_double, fmt_plain
from tbx.ir.parse import lift_assign, parse_expr, tokenize
from tbx.ir.render import (
    params_sig,
    unparse,
    unparse_case_guard,
    unparse_cond,
    unparse_stmt,
)
from tbx.ir.stmt_nodes import (
    Assign,
    Beep,
    Bload,
    BodyLine,
    Bsave,
    CallAbsolute,
    CallInterrupt,
    CallStmt,
    CaseArm,
    Chain,
    Chdir,
    Circle,
    Clear,
    Close,
    Cls,
    Color,
    Common,
    Data,
    DataItem,
    DateTimeSet,
    DefFn,
    DefSeg,
    DefType,
    Delay,
    Dim,
    Do,
    Draw,
    End,
    Environ,
    Erase,
    ErrorStmt,
    ExitDef,
    ExitFor,
    ExitLoop,
    ExitSub,
    Field,
    Files,
    FnResult,
    For,
    Get,
    GetString,
    GetGfx,
    Gosub,
    Goto,
    IfBlock,
    IfGoto,
    IfInline,
    Inline,
    Input,
    InputFile,
    Key,
    KeyDef,
    KeyList,
    Kill,
    LineInput,
    LineStmt,
    Local,
    Locate,
    Loop,
    Lprint,
    Lset,
    MidAssign,
    Mkdir,
    Mtimer,
    Name,
    NextStmt,
    OnError,
    OnGosub,
    OnGoto,
    OnTrap,
    Open,
    OptionBase,
    Out,
    Paint,
    Palette,
    Play,
    Poke,
    Print,
    PrintUsing,
    Pset,
    Put,
    PutGfx,
    Randomize,
    Read,
    RegSet,
    Reset,
    Restore,
    Resume,
    Return,
    Rmdir,
    Rset,
    Run,
    Screen,
    Seek,
    SelectCase,
    Shared,
    Shell,
    Sound,
    SubDef,
    Swap,
    TrapCtl,
    Troff,
    Tron,
    View,
    Wait,
    Wend,
    While,
    Width,
    Window,
    Write,
)

__all__ = [
    # constants / doc-aliases
    "INTRINSICS",
    "Expr",
    "Stmt",
    # expression nodes
    "ArrayRef",
    "BinOp",
    "Call",
    "CaseIs",
    "CaseRange",
    "CaseValue",
    "DblLit",
    "Erl",
    "Err",
    "FnCall",
    "Group",
    "HexLit",
    "Lit",
    "LogOp",
    "Neg",
    "Not",
    "Nullary",
    "RelOp",
    "SingleLit",
    "StrLit",
    "Unknown",
    "Var",
    "VarSeg",
    # fmt
    "f32_dec",
    "f32_enc",
    "fmt_double",
    "fmt_plain",
    # parse
    "lift_assign",
    "parse_expr",
    "tokenize",
    # render
    "params_sig",
    "unparse",
    "unparse_case_guard",
    "unparse_cond",
    "unparse_stmt",
    # statement nodes
    "Assign",
    "Beep",
    "Bload",
    "BodyLine",
    "Bsave",
    "CallAbsolute",
    "CallInterrupt",
    "CallStmt",
    "CaseArm",
    "Chain",
    "Chdir",
    "Circle",
    "Clear",
    "Close",
    "Cls",
    "Color",
    "Common",
    "Data",
    "DataItem",
    "DateTimeSet",
    "DefFn",
    "DefSeg",
    "DefType",
    "Delay",
    "Dim",
    "Do",
    "Draw",
    "End",
    "Environ",
    "Erase",
    "ErrorStmt",
    "ExitDef",
    "ExitFor",
    "ExitLoop",
    "ExitSub",
    "Field",
    "Files",
    "FnResult",
    "For",
    "Get",
    "GetString",
    "GetGfx",
    "Gosub",
    "Goto",
    "IfBlock",
    "IfGoto",
    "IfInline",
    "Inline",
    "Input",
    "InputFile",
    "Key",
    "KeyDef",
    "KeyList",
    "Kill",
    "LineInput",
    "LineStmt",
    "Local",
    "Locate",
    "Loop",
    "Lprint",
    "Lset",
    "MidAssign",
    "Mkdir",
    "Mtimer",
    "Name",
    "NextStmt",
    "OnError",
    "OnGosub",
    "OnGoto",
    "OnTrap",
    "Open",
    "OptionBase",
    "Out",
    "Paint",
    "Palette",
    "Play",
    "Poke",
    "Print",
    "PrintUsing",
    "Pset",
    "Put",
    "PutGfx",
    "Randomize",
    "Read",
    "RegSet",
    "Reset",
    "Restore",
    "Resume",
    "Return",
    "Rmdir",
    "Rset",
    "Run",
    "Screen",
    "Seek",
    "SelectCase",
    "Shared",
    "Shell",
    "Sound",
    "SubDef",
    "Swap",
    "TrapCtl",
    "Troff",
    "Tron",
    "View",
    "Wait",
    "Wend",
    "While",
    "Width",
    "Window",
    "Write",
]

# `_PREC` (imported above) is re-exported for the modules that reach for `ir._PREC`;
# it is intentionally private, so it is kept out of `__all__`.
