"""Experimental native-recompile back end: typed IR statements -> portable C.

Where emit0 targets the original Borland toolchain byte-for-byte, this back end
targets MODERN platforms: the generated translation unit is self-contained
(embedded runtime prelude, no external headers beyond libc/libm) and compiles
with gcc or clang on any modern OS (`cc out.c -lm`). GOSUB/RETURN use the
labels-as-values extension, so gcc/clang specifically, not MSVC.

Fidelity is behavioral, not byte-exact, and deliberately fail-loud in the
repo's style: an IR node, intrinsic, or type combination outside the
implemented vocabulary raises ValueError rather than mistranslating. The
implemented semantics follow the Turbo Basic handbook:

- unsuffixed and `!` variables are C `float` (TB singles), `%` is `short`
  with CINT banker's rounding on store, `#` is `double`, `$` is a heap
  C string (allocations are never freed -- recompiled programs are
  short-lived by assumption);
- \\ MOD AND OR XOR NOT operate on CINT-rounded 16-bit integers;
- PRINT reproduces the GW-BASIC family layout: sign-or-space before a
  number, trailing space after, `.5` without a leading zero, 7 significant
  digits (single precision), 14-column comma zones untouched (the decoder
  never produces comma items -- TAB/SPC arrive as Call items);
- FOR/WHILE/DO compile to explicit test/jump label pairs so EXIT FOR /
  EXIT LOOP and cross-statement GOTO keep working exactly as in the flat IR.

Unsupported (raises): file I/O, graphics/sound/events, error trapping,
PRINT USING, SUB/CALL and block DEF FN, RUN, CHAIN, machine access
(PEEK/POKE/OUT/CALL ABSOLUTE...), and any intrinsic not listed in
_NUM_FUNCS/_STR_FUNCS.
"""

from __future__ import annotations

from tbx import ir

_PRELUDE = r"""/* generated by tbx --emit-c : Turbo Basic recompiled to C */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <time.h>

static int tb_col = 0;
static void tb_ps(const char *s) {
    for (; *s; s++) { putchar(*s); tb_col = (*s == '\n') ? 0 : tb_col + 1; }
}
static void tb_nl(void) { tb_ps("\n"); }
static const char *tb_s(const char *s) { return s ? s : ""; }
/* GW-BASIC family number image: integral -> no point; else 7 significant
   digits (single precision) with the leading zero of "0.5" stripped. */
static void tb_fmt(double v, char *out) {
    if (v == floor(v) && fabs(v) < 1e15) { sprintf(out, "%.0f", v); return; }
    char b[48]; sprintf(b, "%.7G", v);
    char *p = b, *o = out;
    if (*p == '-') *o++ = *p++;
    if (p[0] == '0' && p[1] == '.') p++;
    strcpy(o, p);
}
static void tb_pn(double v) {
    char b[64]; tb_fmt(v, b);
    if (v >= 0) tb_ps(" ");
    tb_ps(b); tb_ps(" ");
}
static void tb_tab(double n) { while (tb_col < (int)n - 1) tb_ps(" "); }
static void tb_spc(double n) { for (int i = 0; i < (int)n; i++) tb_ps(" "); }
/* CINT: round half to even (the x87/IEEE default nearbyint mode). */
static double tb_cint(double v) { return nearbyint(v); }
static long tb_i(double v) { return (long)tb_cint(v); }
static double tb_idiv(double a, double b) { return (double)(tb_i(a) / tb_i(b)); }
static double tb_mod(double a, double b) { return (double)(tb_i(a) % tb_i(b)); }
static double tb_and(double a, double b) { return (double)(short)(tb_i(a) & tb_i(b)); }
static double tb_or(double a, double b) { return (double)(short)(tb_i(a) | tb_i(b)); }
static double tb_xor(double a, double b) { return (double)(short)(tb_i(a) ^ tb_i(b)); }
static double tb_not(double a) { return (double)(short)~tb_i(a); }
static double tb_sgn(double v) { return v > 0 ? 1 : v < 0 ? -1 : 0; }
static double tb_timer(void) {
    time_t t = time(NULL); struct tm *lt = localtime(&t);
    return lt->tm_hour * 3600.0 + lt->tm_min * 60.0 + lt->tm_sec;
}
static void tb_delay(double secs) {
    struct timespec ts = { (time_t)secs, (long)((secs - (long)secs) * 1e9) };
    nanosleep(&ts, NULL);
}
static char *tb_alloc(size_t n) {
    char *p = malloc(n + 1);
    if (!p) { fputs("out of memory\n", stderr); exit(1); }
    p[n] = 0; return p;
}
static char *tb_dup(const char *s) { char *p = tb_alloc(strlen(s)); strcpy(p, s); return p; }
static char *tb_cat(const char *a, const char *b) {
    a = tb_s(a); b = tb_s(b);
    char *p = tb_alloc(strlen(a) + strlen(b));
    strcpy(p, a); strcat(p, b); return p;
}
static double tb_len(const char *s) { return (double)strlen(tb_s(s)); }
static double tb_asc(const char *s) { return (double)(unsigned char)tb_s(s)[0]; }
static double tb_val(const char *s) { return strtod(tb_s(s), NULL); }
static char *tb_chr(double c) { char *p = tb_alloc(1); p[0] = (char)tb_i(c); return p; }
static char *tb_strS(double v) {
    char b[64]; tb_fmt(v, b);
    char *p = tb_alloc(strlen(b) + 1);
    if (v >= 0) { p[0] = ' '; strcpy(p + 1, b); } else strcpy(p, b);
    return p;
}
static char *tb_space(double n) {
    long k = tb_i(n) < 0 ? 0 : tb_i(n);
    char *p = tb_alloc(k); memset(p, ' ', k); return p;
}
static char *tb_stringS(double n, double c) {
    long k = tb_i(n) < 0 ? 0 : tb_i(n);
    char *p = tb_alloc(k); memset(p, (char)tb_i(c), k); return p;
}
static char *tb_left(const char *s, double n) {
    s = tb_s(s); size_t L = strlen(s), k = tb_i(n) < 0 ? 0 : (size_t)tb_i(n);
    if (k > L) k = L;
    char *p = tb_alloc(k); memcpy(p, s, k); return p;
}
static char *tb_right(const char *s, double n) {
    s = tb_s(s); size_t L = strlen(s), k = tb_i(n) < 0 ? 0 : (size_t)tb_i(n);
    if (k > L) k = L;
    return tb_dup(s + (L - k));
}
static char *tb_mid(const char *s, double start, double len) {
    s = tb_s(s); size_t L = strlen(s);
    long st = tb_i(start); if (st < 1) st = 1;
    if ((size_t)st > L) return tb_dup("");
    size_t avail = L - (st - 1), k = len < 0 ? avail : (size_t)tb_i(len);
    if (k > avail) k = avail;
    char *p = tb_alloc(k); memcpy(p, s + st - 1, k); return p;
}
static double tb_instr(double start, const char *a, const char *b) {
    a = tb_s(a); b = tb_s(b);
    long st = tb_i(start); if (st < 1) st = 1;
    if ((size_t)st > strlen(a)) return 0;
    const char *hit = strstr(a + st - 1, b);
    return hit ? (double)(hit - a + 1) : 0;
}
static char *tb_ucase(const char *s) {
    char *p = tb_dup(tb_s(s));
    for (char *q = p; *q; q++) if (*q >= 'a' && *q <= 'z') *q -= 32;
    return p;
}
static char *tb_lcase(const char *s) {
    char *p = tb_dup(tb_s(s));
    for (char *q = p; *q; q++) if (*q >= 'A' && *q <= 'Z') *q += 32;
    return p;
}
static char *tb_ltrim(const char *s) { s = tb_s(s); while (*s == ' ') s++; return tb_dup(s); }
static char *tb_rtrim(const char *s) {
    char *p = tb_dup(tb_s(s));
    for (size_t L = strlen(p); L && p[L - 1] == ' '; L--) p[L - 1] = 0;
    return p;
}
static char *tb_hex(double v) { char b[24]; sprintf(b, "%lX", tb_i(v) & 0xFFFF); return tb_dup(b); }
static char *tb_oct(double v) { char b[24]; sprintf(b, "%lo", tb_i(v) & 0xFFFF); return tb_dup(b); }
static double tb_input_num(const char *prompt, int mark) {
    if (prompt) tb_ps(prompt);
    if (mark) tb_ps("? ");
    char line[256];
    if (!fgets(line, sizeof line, stdin)) return 0;
    tb_col = 0;
    return strtod(line, NULL);
}
static char *tb_input_str(const char *prompt, int mark) {
    if (prompt) tb_ps(prompt);
    if (mark) tb_ps("? ");
    char line[256];
    if (!fgets(line, sizeof line, stdin)) return tb_dup("");
    tb_col = 0;
    line[strcspn(line, "\r\n")] = 0;
    return tb_dup(line);
}
static char *tb_dateS(void) {
    time_t t = time(NULL); struct tm *lt = localtime(&t); char b[16];
    sprintf(b, "%02d-%02d-%04d", lt->tm_mon + 1, lt->tm_mday, lt->tm_year + 1900);
    return tb_dup(b);
}
static char *tb_timeS(void) {
    time_t t = time(NULL); struct tm *lt = localtime(&t); char b[16];
    sprintf(b, "%02d:%02d:%02d", lt->tm_hour, lt->tm_min, lt->tm_sec);
    return tb_dup(b);
}
static void *tb_calloc(long n, size_t w) {
    void *p = calloc(n > 0 ? n : 1, w);
    if (!p) { fputs("out of memory\n", stderr); exit(1); }
    return p;
}
static void *tb_gstack[256];
static int tb_gsp = 0;
"""

# name -> (c_call, arity); {0}... are the rendered numeric/string args in order.
_NUM_FUNCS = {
    ("SQR", 1): "sqrt({0})",
    ("ABS", 1): "fabs({0})",
    ("SIN", 1): "sin({0})",
    ("COS", 1): "cos({0})",
    ("TAN", 1): "tan({0})",
    ("ATN", 1): "atan({0})",
    ("EXP", 1): "exp({0})",
    ("LOG", 1): "log({0})",
    ("LOG2", 1): "log2({0})",
    ("LOG10", 1): "log10({0})",
    ("INT", 1): "floor({0})",
    ("FIX", 1): "trunc({0})",
    ("SGN", 1): "tb_sgn({0})",
    ("CINT", 1): "tb_cint({0})",
    ("CSNG", 1): "(double)(float)({0})",
    ("CDBL", 1): "({0})",
    ("LEN", 1): "tb_len({0})",
    ("ASC", 1): "tb_asc({0})",
    ("VAL", 1): "tb_val({0})",
    ("INSTR", 2): "tb_instr(1, {0}, {1})",
    ("INSTR", 3): "tb_instr({0}, {1}, {2})",
    ("POS", 1): "(double)(tb_col + 1)",
    # free memory: meaningless on a modern host; a fixed roomy answer keeps
    # low-memory guard code on its happy path
    ("FRE", 1): "65536.0",
}
_STR_FUNCS = {
    ("CHR$", 1): "tb_chr({0})",
    ("STR$", 1): "tb_strS({0})",
    ("SPACE$", 1): "tb_space({0})",
    ("STRING$", 2): "tb_stringS({0}, {1})",
    ("LEFT$", 2): "tb_left({0}, {1})",
    ("RIGHT$", 2): "tb_right({0}, {1})",
    ("MID$", 2): "tb_mid({0}, {1}, -1)",
    ("MID$", 3): "tb_mid({0}, {1}, {2})",
    ("UCASE$", 1): "tb_ucase({0})",
    ("LCASE$", 1): "tb_lcase({0})",
    ("LTRIM$", 1): "tb_ltrim({0})",
    ("RTRIM$", 1): "tb_rtrim({0})",
    ("HEX$", 1): "tb_hex({0})",
    ("OCT$", 1): "tb_oct({0})",
}
_NULLARY = {"TIMER": "tb_timer()"}
_NULLARY_STR = {"DATE$": "tb_dateS()", "TIME$": "tb_timeS()"}

# variable C types by TB suffix: (c type, mangle prefix, zero)
_VTYPES = {
    "NUM": ("float", "f_", "0"),
    "SGL": ("float", "f_", "0"),
    "INT": ("short", "i_", "0"),
    "LNG": ("int", "l_", "0"),  # TB `&` long: 32-bit signed
    "DBL": ("double", "d_", "0"),
    "STR": ("char *", "s_", '""'),
}
# store conversion applied on assignment, per TB variable type
_STORE_CAST = {
    "NUM": "(float)({0})",
    "SGL": "(float)({0})",
    "INT": "(short)tb_cint({0})",
    "LNG": "(int)tb_cint({0})",
    "DBL": "({0})",
}

_INT_BINOPS = {"\\": "tb_idiv", "MOD": "tb_mod", "AND": "tb_and", "OR": "tb_or", "XOR": "tb_xor"}


def _suffix_ty(name: str) -> str:
    return {"%": "INT", "&": "LNG", "!": "SGL", "#": "DBL", "$": "STR"}.get(name[-1], "NUM")


def _base(name: str) -> str:
    return name.rstrip("%&!#$")


def _cstr(s: str) -> str:
    out = ['"']
    for ch in s:
        if ch in '"\\':
            out.append("\\" + ch)
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            out.append(f'\\{ord(ch):03o}')
    out.append('"')
    return "".join(out)


class _Raw:
    """A pre-rendered C fragment standing in for an Expr in assign()."""

    def __init__(self, code: str, is_str: bool):
        self.code = code
        self.is_str = is_str


def _is_str(e) -> bool:
    if isinstance(e, _Raw):
        return e.is_str
    if isinstance(e, ir.StrLit):
        return True
    if isinstance(e, (ir.Var, ir.ArrayRef, ir.Call, ir.FnCall, ir.Nullary)):
        return e.name.endswith("$")
    if isinstance(e, ir.BinOp) and e.op == "+":
        return _is_str(e.lhs)
    if isinstance(e, ir.Group):
        return _is_str(e.inner)
    return False


class _Unsupported(ValueError):
    pass


class _Gen:
    """One translation: collects declarations while rendering the body."""

    def __init__(self, stmts):
        self.stmts = list(stmts)
        self.vars: dict[str, str] = {}  # mangled -> C declaration
        # name -> (ty, dims, rank); dims is a tuple of int upper bounds for a
        # compile-time DIM, or None for a runtime (variable-bound) DIM
        self.arrays: dict[str, tuple[str, tuple[int, ...] | None, int]] = {}
        self.fns: list[str] = []  # hoisted inline DEF FN definitions
        self.fn_names: set[str] = set()
        self.data: list[tuple[str, bool]] = []
        self.data_offset: dict[int, int] = {}  # top-level stmt index -> data cursor
        self.labels: set[int] = set()
        self.n = 0  # unique-label counter
        self.params: dict[str, str] = {}  # active DEF FN param name -> C name

    def uid(self) -> int:
        self.n += 1
        return self.n

    # --- naming / declarations ---

    def var(self, name: str) -> str:
        if name in self.params:
            return self.params[name]
        cty, pre, zero = _VTYPES[_suffix_ty(name)]
        m = pre + _base(name)
        self.vars.setdefault(m, f"static {cty}{'' if cty.endswith('*') else ' '}{m} = {zero};")
        return m

    def array(self, name: str, rank: int) -> tuple[str, tuple[int, ...] | None, int]:
        if name not in self.arrays:
            self.dim_array(name, (10,) * rank)  # implicit DIM x(10[,10])
        return self.arrays[name]

    def dim_array(self, name: str, bounds) -> list[str]:
        """Register array `name`; returns the allocation code (empty when static)."""
        ty = _suffix_ty(name)
        if all(isinstance(b, int) for b in bounds):
            self.arrays[name] = (ty, tuple(int(b) for b in bounds), len(bounds))
            return []
        # runtime bounds: heap allocation at the DIM statement
        rank = len(bounds)
        if rank > 2:
            raise _Unsupported("DIM rank > 2")
        self.arrays[name] = (ty, None, rank)
        cty, pre, _ = _VTYPES[ty]
        m = "a" + pre + _base(name)
        dims = [f"((long)tb_cint({self.num(b)}) + 1)" for b in bounds]
        code = [f"{m}_n{k + 1} = {d};" for k, d in enumerate(dims)]
        total = " * ".join(f"{m}_n{k + 1}" for k in range(rank))
        code.append(f"{m} = tb_calloc({total}, sizeof *{m});")
        return code

    # --- expressions ---

    def num(self, e) -> str:
        """Render e as a C double-valued expression."""
        if isinstance(e, _Raw):
            return e.code
        if _is_str(e):
            raise _Unsupported(f"string expression where a number is needed: {e!r}")
        if isinstance(e, ir.Lit):
            return repr(float(e.value)) if isinstance(e.value, float) else str(e.value)
        if isinstance(e, (ir.DblLit, ir.SingleLit)):
            return repr(e.value)
        if isinstance(e, ir.HexLit):
            return f"(double)(short)0x{e.value:X}"
        if isinstance(e, ir.Var):
            return self.var(e.name)
        if isinstance(e, ir.ArrayRef):
            return self.aref(e)
        if isinstance(e, ir.Neg):
            return f"(-({self.num(e.operand)}))"
        if isinstance(e, ir.Not):
            return f"tb_not({self.num(e.operand)})"
        if isinstance(e, ir.Group):
            return f"({self.num(e.inner)})"
        if isinstance(e, ir.BinOp):
            if e.op in "+-*/":
                return f"({self.num(e.lhs)} {e.op} {self.num(e.rhs)})"
            if e.op == "^":
                return f"pow({self.num(e.lhs)}, {self.num(e.rhs)})"
            if e.op in _INT_BINOPS:
                return f"{_INT_BINOPS[e.op]}({self.num(e.lhs)}, {self.num(e.rhs)})"
            raise _Unsupported(f"operator {e.op}")
        if isinstance(e, (ir.RelOp, ir.LogOp)):
            return f"({self.cond(e)} ? -1.0 : 0.0)"  # TB truth value
        if isinstance(e, ir.Call):
            return self.call(e, _NUM_FUNCS)
        if isinstance(e, ir.FnCall):
            return self.fncall(e)
        if isinstance(e, ir.Nullary):
            if e.name in _NULLARY:
                return _NULLARY[e.name]
            raise _Unsupported(f"intrinsic {e.name}")
        raise _Unsupported(f"expression {type(e).__name__}")

    def _nullary_str(self, e) -> str:
        if e.name in _NULLARY_STR:
            return _NULLARY_STR[e.name]
        raise _Unsupported(f"string intrinsic {e.name}")

    def s(self, e) -> str:
        """Render e as a C char*-valued expression."""
        if isinstance(e, _Raw):
            return e.code
        if isinstance(e, ir.StrLit):
            return _cstr(e.value)
        if isinstance(e, ir.Var):
            return self.var(e.name)
        if isinstance(e, ir.ArrayRef):
            return self.aref(e)
        if isinstance(e, ir.Group):
            return f"({self.s(e.inner)})"
        if isinstance(e, ir.BinOp) and e.op == "+":
            return f"tb_cat({self.s(e.lhs)}, {self.s(e.rhs)})"
        if isinstance(e, ir.Call):
            return self.call(e, _STR_FUNCS)
        if isinstance(e, ir.Nullary):
            return self._nullary_str(e)
        raise _Unsupported(f"string expression {type(e).__name__}")

    def call(self, e, table) -> str:
        # arity-keyed template; each arg renders by its own inferred type
        key = (e.name, len(e.args))
        if key not in table:
            raise _Unsupported(f"intrinsic {e.name}/{len(e.args)}")
        args = [self.s(a) if _is_str(a) else self.num(a) for a in e.args]
        return table[key].format(*args)

    def fncall(self, e) -> str:
        if e.name.endswith("$"):
            raise _Unsupported("string DEF FN")
        if e.name not in self.fn_names:
            raise _Unsupported(f"call to undefined {e.name}")
        return f"fn_{_base(e.name)}({', '.join(self.num(a) for a in e.args)})"

    def aref(self, e) -> str:
        ty, dims, rank = self.array(e.name, len(e.indices))
        if rank != len(e.indices):
            raise _Unsupported(f"rank mismatch on array {e.name}")
        _, pre, _ = _VTYPES[ty]
        m = "a" + pre + _base(e.name)
        idx = [f"(long)tb_cint({self.num(i)})" for i in e.indices]
        if rank == 1:
            return f"{m}[{idx[0]}]"
        stride = f"{dims[1] + 1}" if dims is not None else f"{m}_n2"
        return f"{m}[({idx[0]}) * {stride} + ({idx[1]})]"

    def cond(self, e) -> str:
        if isinstance(e, ir.RelOp):
            op = {"=": "==", "<>": "!="}.get(e.op, e.op)
            if _is_str(e.lhs) or _is_str(e.rhs):
                return f"(strcmp(tb_s({self.s(e.lhs)}), tb_s({self.s(e.rhs)})) {op} 0)"
            return f"({self.num(e.lhs)} {op} {self.num(e.rhs)})"
        if isinstance(e, ir.LogOp):
            c = "&&" if e.op == "AND" else "||"
            return f"({self.cond(e.lhs)} {c} {self.cond(e.rhs)})"
        # numeric-valued condition: TB nonzero = true
        return f"({self.num(e)} != 0)"

    # --- statements ---

    def assign(self, target, value) -> str:
        if isinstance(target, ir.Var):
            dst, ty = self.var(target.name), _suffix_ty(target.name)
        elif isinstance(target, ir.ArrayRef):
            dst, ty = self.aref(target), self.array(target.name, len(target.indices))[0]
        else:
            raise _Unsupported(f"assign target {type(target).__name__}")
        if ty == "STR":
            return f"{dst} = {self.s(value)};"
        return f"{dst} = {_STORE_CAST[ty].format(self.num(value))};"

    def gen_print(self, s) -> list[str]:
        if s.file is not None:
            raise _Unsupported("PRINT #n")
        out = []
        for item in s.items:
            if isinstance(item, ir.Call) and item.name in ("TAB", "SPC"):
                out.append(f"tb_{item.name.lower()}({self.num(item.args[0])});")
            elif _is_str(item):
                out.append(f"tb_ps(tb_s({self.s(item)}));")
            else:
                out.append(f"tb_pn({self.num(item)});")
        if s.newline:
            out.append("tb_nl();")
        return out

    def gen_body(self, body, loops) -> list[str]:
        out = []
        i = 0
        body = list(body)
        while i < len(body):
            out.extend(self.gen(body[i], loops, None))
            i += 1
        return out

    def gen(self, s, loops, idx) -> list[str]:
        """C lines for one statement. `loops` is the open FOR/DO/WHILE label stack
        (shared across nesting so flat FOR..NEXT pairs match); `idx` is the
        top-level statement index or None inside a block body."""
        if isinstance(s, ir.Assign):
            return [self.assign(s.target, s.value)]
        if isinstance(s, ir.Print):
            return self.gen_print(s)
        if isinstance(s, ir.End):
            return ["exit(0);"]
        if isinstance(s, (ir.Tron, ir.Troff)):
            return []
        if isinstance(s, ir.Goto):
            return [f"goto L{s.target};"]
        if isinstance(s, ir.IfGoto):
            return [f"if {self.cond(s.cond)} goto L{s.target};"]
        if isinstance(s, ir.Gosub):
            n = self.uid()
            return [f"tb_gstack[tb_gsp++] = &&R{n}; goto L{s.target}; R{n}:;"]
        if isinstance(s, ir.Return):
            return ["goto *tb_gstack[--tb_gsp];"]
        if isinstance(s, ir.OnGoto) or isinstance(s, ir.OnGosub):
            n = self.uid()
            lines = [f"switch ((int)tb_cint({self.num(s.selector)})) {{"]
            for k, t in enumerate(s.targets, 1):
                if isinstance(s, ir.OnGoto):
                    lines.append(f"case {k}: goto L{t};")
                else:
                    lines.append(f"case {k}: tb_gstack[tb_gsp++] = &&R{n}; goto L{t};")
            lines.append("}")
            if isinstance(s, ir.OnGosub):
                lines.append(f"R{n}:;")
            return lines
        if isinstance(s, ir.For):
            n = self.uid()
            v = self.var(s.var.name)
            lim, st = f"tb_lim{n}", f"tb_st{n}"
            self.vars[lim] = f"static double {lim} = 0;"
            self.vars[st] = f"static double {st} = 0;"
            loops.append(("FOR", n, s.var.name))
            return [
                self.assign(s.var, s.init),
                f"{lim} = {self.num(s.limit)}; {st} = {self.num(s.step)};",
                f"FCHK{n}: if (!({st} >= 0 ? {v} <= {lim} : {v} >= {lim})) goto FDONE{n};",
            ]
        if isinstance(s, ir.NextStmt):
            for j in range(len(loops) - 1, -1, -1):
                if loops[j][0] == "FOR" and loops[j][2] == s.var.name:
                    _, n, _ = loops.pop(j)
                    v = self.var(s.var.name)
                    cast = _STORE_CAST[_suffix_ty(s.var.name)]
                    stv = f"{v} = {cast.format(f'{v} + tb_st{n}')};"
                    return [stv, f"goto FCHK{n};", f"FDONE{n}:;"]
            raise _Unsupported(f"NEXT {s.var.name} without open FOR")
        if isinstance(s, ir.While):
            n = self.uid()
            loops.append(("WHILE", n, None))
            return [f"WTOP{n}: if (!{self.cond(s.cond)}) goto WDONE{n};"]
        if isinstance(s, ir.Wend):
            for j in range(len(loops) - 1, -1, -1):
                if loops[j][0] == "WHILE":
                    _, n, _ = loops.pop(j)
                    return [f"goto WTOP{n};", f"WDONE{n}:;"]
            raise _Unsupported("WEND without open WHILE")
        if isinstance(s, ir.Do):
            n = self.uid()
            loops.append(("DO", n, None))
            top = [f"DTOP{n}:;"]
            if s.kind == "WHILE":
                top.append(f"if (!{self.cond(s.cond)}) goto DDONE{n};")
            elif s.kind == "UNTIL":
                top.append(f"if {self.cond(s.cond)} goto DDONE{n};")
            return top
        if isinstance(s, ir.Loop):
            for j in range(len(loops) - 1, -1, -1):
                if loops[j][0] == "DO":
                    _, n, _ = loops.pop(j)
                    if s.kind == "WHILE":
                        return [f"if {self.cond(s.cond)} goto DTOP{n};", f"DDONE{n}:;"]
                    if s.kind == "UNTIL":
                        return [f"if (!{self.cond(s.cond)}) goto DTOP{n};", f"DDONE{n}:;"]
                    return [f"goto DTOP{n};", f"DDONE{n}:;"]
            raise _Unsupported("LOOP without open DO")
        if isinstance(s, ir.ExitFor):
            for kind, n, _ in reversed(loops):
                if kind == "FOR":
                    return [f"goto FDONE{n};"]
            raise _Unsupported("EXIT FOR outside FOR")
        if isinstance(s, ir.ExitLoop):
            for kind, n, _ in reversed(loops):
                if kind == "DO":
                    return [f"goto DDONE{n};"]
            raise _Unsupported("EXIT LOOP outside DO")
        if isinstance(s, ir.IfInline):
            return [f"if {self.cond(s.cond)} {{", *self.gen_body(s.body, loops), "}"]
        if isinstance(s, ir.IfBlock):
            lines = []
            for k, (cond, body) in enumerate(s.arms):
                kw = "if" if k == 0 else "} else if"
                lines.append(f"{kw} {self.cond(cond)} {{")
                lines.extend(self.gen_body(body, loops))
            if s.else_body is not None:
                lines.append("} else {")
                lines.extend(self.gen_body(s.else_body, loops))
            lines.append("}")
            return lines
        if isinstance(s, ir.SelectCase):
            n = self.uid()
            is_str = _is_str(s.selector)
            sel = f"tb_sel{n}"
            self.vars[sel] = f"static {'char *' if is_str else 'double '}{sel} = {'0' if is_str else '0'};"
            lines = [f"{sel} = {self.s(s.selector) if is_str else self.num(s.selector)};"]

            def guard(g) -> str:
                if isinstance(g, ir.CaseValue):
                    if is_str:
                        return f"(strcmp(tb_s({sel}), tb_s({self.s(g.value)})) == 0)"
                    return f"({sel} == {self.num(g.value)})"
                if isinstance(g, ir.CaseRange):
                    if is_str:
                        return (
                            f"(strcmp(tb_s({sel}), tb_s({self.s(g.lo)})) >= 0 && "
                            f"strcmp(tb_s({sel}), tb_s({self.s(g.hi)})) <= 0)"
                        )
                    return f"({sel} >= {self.num(g.lo)} && {sel} <= {self.num(g.hi)})"
                if isinstance(g, ir.CaseIs):
                    op = {"=": "==", "<>": "!="}.get(g.op, g.op)
                    if is_str:
                        return f"(strcmp(tb_s({sel}), tb_s({self.s(g.value)})) {op} 0)"
                    return f"({sel} {op} {self.num(g.value)})"
                raise _Unsupported(f"case guard {type(g).__name__}")

            for k, arm in enumerate(s.arms):
                kw = "if" if k == 0 else "} else if"
                lines.append(f"{kw} ({' || '.join(guard(g) for g in arm.guards)}) {{")
                lines.extend(self.gen_body(arm.body, loops))
            if s.case_else is not None:
                lines.append("} else {")
                lines.extend(self.gen_body(s.case_else, loops))
            lines.append("}")
            return lines
        if isinstance(s, ir.Dim):
            out = []
            for name, bounds in ((s.name, s.bounds), *s.also):
                out.extend(self.dim_array(name, bounds))
            return out
        if isinstance(s, ir.OptionBase):
            return []  # arrays always allocate 0..ub, valid for base 0 and 1
        if isinstance(s, ir.Data):
            if idx is not None:
                self.data_offset[idx] = len(self.data)
            self.data.extend((it.text, it.is_str) for it in s.items)
            return []
        if isinstance(s, ir.Read):
            out = []
            for t in s.targets:
                ty = (
                    _suffix_ty(t.name)
                    if isinstance(t, (ir.Var, ir.ArrayRef))
                    else "NUM"
                )
                src = (
                    "tb_dup(tb_data[tb_data_p++])"
                    if ty == "STR"
                    else "tb_val(tb_data[tb_data_p++])"
                )
                out.append(self.assign(t, _Raw(src, ty == "STR")))
            return out
        if isinstance(s, ir.Restore):
            off = 0 if s.target is None else self.data_offset.get(s.target)
            if off is None:
                raise _Unsupported("RESTORE to a non-DATA statement")
            return [f"tb_data_p = {off};"]
        if isinstance(s, ir.Input):
            fn = "tb_input_str" if _suffix_ty(s.var.name) == "STR" else "tb_input_num"
            prompt = _cstr(s.prompt.value) if s.prompt is not None else "NULL"
            mark = "0" if (s.prompt is not None and s.comma) else "1"
            return [self.assign(s.var, _Raw(f"{fn}({prompt}, {mark})", fn.endswith("str")))]
        if isinstance(s, ir.LineInput):
            prompt = _cstr(s.prompt.value) if s.prompt is not None else "NULL"
            return [self.assign(s.var, _Raw(f"tb_input_str({prompt}, 0)", True))]
        if isinstance(s, ir.Swap):
            a, b = self.var(s.a.name), self.var(s.b.name)
            ta, tb_ = _suffix_ty(s.a.name), _suffix_ty(s.b.name)
            if ta != tb_:
                raise _Unsupported("SWAP across types")
            cty, _, _ = _VTYPES[ta]
            return [f"{{ {cty} t = {a}; {a} = {b}; {b} = t; }}"]
        if isinstance(s, ir.Beep):
            return ['tb_ps("\\a");']
        if isinstance(s, ir.Cls):
            return ['tb_ps("\\033[2J\\033[H"); tb_col = 0;']
        if isinstance(s, ir.Delay):
            return [f"tb_delay({self.num(s.secs)});"]
        if isinstance(s, ir.Randomize):
            return [f"srand((unsigned)tb_i({self.num(s.seed)}));"]
        if isinstance(s, ir.MidAssign):
            tgt = self.var(s.target.name)
            n = self.uid()
            return [
                f"{{ char *t{n} = tb_dup(tb_s({tgt})); const char *m{n} = tb_s({self.s(s.source)});",
                f"  long p{n} = tb_i({self.num(s.start)}) - 1, L{n} = (long)strlen(t{n});",
                f"  for (long k{n} = 0; m{n}[k{n}] && p{n} + k{n} < L{n}; k{n}++) t{n}[p{n} + k{n}] = m{n}[k{n}];",
                f"  {tgt} = t{n}; }}",
            ]
        if isinstance(s, ir.DefFn):
            self.gen_deffn(s)
            return []
        raise _Unsupported(f"statement {type(s).__name__}")

    def gen_deffn(self, s) -> None:
        if s.is_block:
            raise _Unsupported("multi-line DEF FN")
        if s.name.endswith("$") or any(p.endswith("$") for p in s.params):
            raise _Unsupported("string DEF FN")
        old = self.params
        self.params = {p: f"p_{_base(p)}" for p in s.params}
        try:
            body = self.num(s.body)
        finally:
            self.params = old
        args = ", ".join(f"double p_{_base(p)}" for p in s.params) or "void"
        self.fns.append(f"static double fn_{_base(s.name)}({args}) {{ return {body}; }}")
        self.fn_names.add(s.name)

    # --- whole program ---

    def build(self) -> str:
        # collect label targets across the whole tree
        def walk(node):
            if isinstance(node, (ir.Goto, ir.IfGoto, ir.Gosub)):
                if isinstance(node.target, int):
                    self.labels.add(node.target)
            if isinstance(node, (ir.OnGoto, ir.OnGosub)):
                self.labels.update(t for t in node.targets if isinstance(t, int))
            for f in getattr(node, "__dataclass_fields__", ()):
                v = getattr(node, f)
                for item in v if isinstance(v, tuple) else (v,):
                    if hasattr(item, "__dataclass_fields__"):
                        walk(item)

        for st in self.stmts:
            walk(st)

        body: list[str] = []
        loops: list[tuple[str, int, str | None]] = []
        for i, st in enumerate(self.stmts):
            if i in self.labels:
                body.append(f"L{i}:;")
            body.extend(self.gen(st, loops, i))
        if loops:
            raise _Unsupported(f"unclosed loop(s): {[k for k, *_ in loops]}")

        parts = [_PRELUDE]
        if self.data:
            items = ", ".join(_cstr(t) for t, _ in self.data)
            parts.append(f"static const char *tb_data[] = {{ {items} }};")
            parts.append("static int tb_data_p = 0;")
        for name, (ty, dims, rank) in sorted(self.arrays.items()):
            cty, pre, _ = _VTYPES[ty]
            sep = "" if cty.endswith("*") else " "
            m = f"a{pre}{_base(name)}"
            if dims is not None:
                size = " * ".join(str(d + 1) for d in dims)
                parts.append(f"static {cty}{sep}{m}[{size}] = {{0}};")
            else:
                parts.append(f"static {cty}{sep}*{m} = 0;")
                parts.extend(f"static long {m}_n{k + 1} = 0;" for k in range(rank))
        parts.extend(self.vars[k] for k in sorted(self.vars))
        parts.extend(self.fns)
        parts.append("int main(void) {")
        parts.extend("    " + ln for ln in body)
        parts.append("    return 0;")
        parts.append("}")
        return "\n".join(parts) + "\n"


def emit_c(stmts) -> str:
    """Typed IR statements -> a self-contained C translation unit (gcc/clang).

    Raises ValueError for programs using constructs outside the implemented
    vocabulary -- fail-loud, like the decoder."""
    return _Gen(stmts).build()
