"""Experimental native-recompile back end: typed IR statements -> portable C.

Where emit0 targets the original Borland toolchain byte-for-byte, this back end
targets MODERN platforms: the generated translation unit is self-contained
(the runtime fragments in c0_runtime/ are embedded verbatim, no external
headers beyond libc/libm/Win32) and compiles with gcc or clang on any modern
OS -- `cc out.c -lm` on POSIX, MinGW-w64 gcc or clang on Windows (the runtime
carries #ifdef _WIN32 paths for its terminal/keyboard/timing bits).
GOSUB/RETURN use the labels-as-values extension, so gcc/clang specifically,
not MSVC.

Two variants of the output shape (see emit_c): `standalone=False` emits an
#include of tb_runtime.h instead of embedding the runtime, for linking many
programs against one libtbrt.a (`make` in c0_runtime/); `sdl=True` selects
the SDL2 video backend, presenting the graphics framebuffer in a real
window with the window's keyboard feeding INKEY$/INSTAT.

Fidelity is behavioral, not byte-exact, and deliberately fail-loud in the
repo's style: an IR node, intrinsic, or type combination outside the
implemented vocabulary raises ValueError rather than mistranslating. The
implemented semantics follow the Turbo Basic handbook:

- unsuffixed and `!` variables are C `float` (TB singles), `%` is `short`
  with CINT banker's rounding on store, `#` is `double`, `$` is a heap
  C string (allocations are never freed -- recompiled programs are
  short-lived by assumption);
- \\ MOD AND OR XOR NOT operate on CINT-rounded 16-bit integers;
- PRINT reproduces the GW-BASIC family layout: sign-or-space before a
  number, trailing space after, `.5` without a leading zero, 7 significant
  digits (single precision), 14-column comma zones untouched (the decoder
  never produces comma items -- TAB/SPC arrive as Call items);
- FOR/WHILE/DO compile to explicit test/jump label pairs so EXIT FOR /
  EXIT LOOP and cross-statement GOTO keep working exactly as in the flat IR.

Machine access runs against the emulated real-mode machine in
machine.c: PEEK/POKE/DEF SEG/BLOAD/BSAVE address a private zeroed 1 MiB
array, OUT/INP are 64 K port latches, WAIT returns at once, REG is real
storage with a no-op CALL INTERRUPT, CHAIN execs the named file, and
CALL ABSOLUTE transpiles but aborts if reached (there is no machine code
to run).

Unsupported (raises): string DEF FN, DIM rank > 2, and any intrinsic not
listed in _NUM_FUNCS/_STR_FUNCS.
"""

from __future__ import annotations

from importlib.resources import files as _res_files

from tbx import ir

# The C runtime lives beside this module in c0_runtime/ as standalone units:
# each .c includes tb_runtime.h and compiles on its own, so the runtime also
# builds as an ordinary C library. emit amalgamates header + fragments
# (stripping the include lines) into one self-contained translation unit.
# Order matters (later fragments call earlier ones), hence an explicit
# manifest rather than a directory glob.
_RUNTIME_FRAGMENTS = (
    "core.c",      # error trapping, console PRINT, clock, numbers, strings, INPUT
    "fileio.c",    # sequential/random-access file I/O, WRITE, PRINT USING, MKx$/CVx
    "terminal.c",  # RND, INSTAT, ANSI terminal control, INKEY$, FILES, BIN$
    "graphics.c",  # framebuffer graphics: SCREEN, PSET, LINE, CIRCLE, PAINT, DRAW...
    "play.c",      # PLAY: MML decoding to the WAV-file surrogate
    "events.c",    # ON TIMER polling, MTIMER, the GOSUB label stack
    "machine.c",   # emulated real-mode memory, ports, REG buffer, CHAIN
    "sdl.c",       # optional SDL2 window (-DTB_SDL=1); empty otherwise
)


def _amalgamate() -> str:
    d = _res_files("tbx") / "c0_runtime"
    parts = ["/* generated by tbx --emit-c : Turbo Basic recompiled to C */\n"]
    parts.append((d / "tb_runtime.h").read_text())
    for name in _RUNTIME_FRAGMENTS:
        parts.append((d / name).read_text().replace('#include "tb_runtime.h"\n', "", 1))
    return "".join(parts)


_PRELUDE = _amalgamate()

# name -> (c_call, arity); {0}... are the rendered numeric/string args in order.
_NUM_FUNCS = {
    ("SQR", 1): "sqrt({0})",
    ("ABS", 1): "fabs({0})",
    ("SIN", 1): "sin({0})",
    ("COS", 1): "cos({0})",
    ("TAN", 1): "tan({0})",
    ("ATN", 1): "atan({0})",
    ("EXP", 1): "exp({0})",
    ("LOG", 1): "log({0})",
    ("LOG2", 1): "log2({0})",
    ("LOG10", 1): "log10({0})",
    ("INT", 1): "floor({0})",
    ("FIX", 1): "trunc({0})",
    ("SGN", 1): "tb_sgn({0})",
    ("CINT", 1): "tb_cint({0})",
    ("CSNG", 1): "(double)(float)({0})",
    ("CDBL", 1): "({0})",
    ("LEN", 1): "tb_len({0})",
    ("ASC", 1): "tb_asc({0})",
    ("VAL", 1): "tb_val({0})",
    ("INSTR", 2): "tb_instr(1, {0}, {1})",
    ("INSTR", 3): "tb_instr({0}, {1}, {2})",
    ("CEIL", 1): "ceil({0})",
    ("CLNG", 1): "tb_cint({0})",
    ("CVI", 1): "tb_cvi({0})",
    ("CVL", 1): "tb_cvl({0})",
    ("CVS", 1): "tb_cvs({0})",
    ("CVD", 1): "tb_cvd({0})",
    ("RND", 1): "tb_rndf({0})",
    ("PMAP", 2): "tb_pmap({0}, {1})",
    # SCREEN(row,col) reads a text cell; there is no text buffer on this
    # host, so every cell reads as a blank
    ("SCREEN", 2): "32.0",
    # joystick / light pen / music queue: devices absent on a modern host
    ("STICK", 1): "0.0",
    ("STRIG", 1): "0.0",
    # ... but PEN errors while PEN OFF (t1_penf dosout)
    ("PEN", 1): "tb_penf()",
    ("PLAY", 1): "0.0",
    # VARPTR: a DGROUP offset with no modern counterpart
    ("VARPTR", 1): "0.0",
    ("POS", 1): "(double)(tb_cols[0] + 1)",
    ("POINT", 2): "tb_pointf({0}, {1})",
    ("EOF", 1): "tb_eof({0})",
    ("LOF", 1): "tb_lof({0})",
    # printer head position: nothing has ever been printed on a modern host
    ("LPOS", 1): "1.0",
    # free memory: meaningless on a modern host; a fixed roomy answer keeps
    # low-memory guard code on its happy path
    ("FRE", 1): "65536.0",
    # machine access reads the emulated machine in machine.c: POKEd memory
    # and OUT-latched ports read back, everything else reads 0
    ("PEEK", 1): "tb_peek({0})",
    ("INP", 1): "tb_inp({0})",
    ("REG", 1): "tb_regget({0})",
}
_STR_FUNCS = {
    ("CHR$", 1): "tb_chr({0})",
    ("STR$", 1): "tb_strS({0})",
    ("SPACE$", 1): "tb_space({0})",
    ("STRING$", 2): "tb_stringS({0}, {1})",  # string-2nd-arg form special-cased in call()
    ("INPUT$", 1): "tb_inputS({0})",
    ("INPUT$", 2): "tb_inputSF({0}, {1})",
    ("LEFT$", 2): "tb_left({0}, {1})",
    ("RIGHT$", 2): "tb_right({0}, {1})",
    ("MID$", 2): "tb_mid({0}, {1}, -1)",
    ("MID$", 3): "tb_mid({0}, {1}, {2})",
    ("MKI$", 1): "tb_mki({0})",
    ("MKL$", 1): "tb_mkl({0})",
    ("MKS$", 1): "tb_mks({0})",
    ("MKD$", 1): "tb_mkd({0})",
    ("UCASE$", 1): "tb_ucase({0})",
    ("LCASE$", 1): "tb_lcase({0})",
    ("LTRIM$", 1): "tb_ltrim({0})",
    ("RTRIM$", 1): "tb_rtrim({0})",
    ("HEX$", 1): "tb_hex({0})",
    ("OCT$", 1): "tb_oct({0})",
    ("BIN$", 1): "tb_bin({0})",
}
_NULLARY = {
    "TIMER": "tb_timer()",
    "CSRLIN": "(double)(tb_row + 1)",
    "RND": "tb_rnd()",
    "INSTAT": "tb_instat()",
    "MTIMER": "tb_mtread()",
    # error address: a DOS code offset with no modern counterpart
    "ERADR": "0.0",
}
_NULLARY_STR = {
    "DATE$": "tb_dateS()",
    "TIME$": "tb_timeS()",
    "INKEY$": "tb_inkey()",
    "COMMAND$": "tb_commandS()",
}

# variable C types by TB suffix: (c type, mangle prefix, zero)
_VTYPES = {
    "NUM": ("float", "f_", "0"),
    "SGL": ("float", "f_", "0"),
    "INT": ("short", "i_", "0"),
    "LNG": ("int", "l_", "0"),  # TB `&` long: 32-bit signed
    "DBL": ("double", "d_", "0"),
    "STR": ("tb_str", "s_", "{0, 0}"),
}
# store conversion applied on assignment, per TB variable type
_STORE_CAST = {
    "NUM": "(float)({0})",
    "SGL": "(float)({0})",
    "INT": "(short)tb_cint({0})",
    "LNG": "(int)tb_cint({0})",
    "DBL": "({0})",
}
# ... and with the IDE Overflow toggle ON (Program.toggles 'O'): integer
# stores range-check to TB error 6 instead of wrapping
_STORE_CAST_OVF = {**_STORE_CAST, "INT": "tb_ichk({0})", "LNG": "tb_lchk({0})"}

_INT_BINOPS = {"\\": "tb_idiv", "MOD": "tb_mod", "AND": "tb_and", "OR": "tb_or", "XOR": "tb_xor"}


def _suffix_ty(name: str) -> str:
    return {"%": "INT", "&": "LNG", "!": "SGL", "#": "DBL", "$": "STR"}.get(name[-1], "NUM")


def _base(name: str) -> str:
    return name.rstrip("%&!#$")


def _cstr(s: str) -> str:
    out = ['"']
    for ch in s:
        if ch in '"\\':
            out.append("\\" + ch)
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            out.append(f'\\{ord(ch):03o}')
    out.append('"')
    return "".join(out)


class _Raw:
    """A pre-rendered C fragment standing in for an Expr in assign()."""

    def __init__(self, code: str, is_str: bool):
        self.code = code
        self.is_str = is_str


def _is_str(e) -> bool:
    if isinstance(e, _Raw):
        return e.is_str
    if isinstance(e, ir.StrLit):
        return True
    if isinstance(e, (ir.Var, ir.ArrayRef, ir.Call, ir.FnCall, ir.Nullary)):
        return e.name.endswith("$")
    if isinstance(e, ir.BinOp) and e.op == "+":
        return _is_str(e.lhs)
    if isinstance(e, ir.Group):
        return _is_str(e.inner)
    return False


class _Unsupported(ValueError):
    """Fail-loud refusal to translate. The remaining raise sites fall into
    three classes (graduation-plan phase 2.5 sweep):

    1. Internal-consistency guards, unreachable from decoded IR: the decoder
       is itself fail-loud over the same vocabulary, so mismatched NEXT/WEND/
       LOOP, undefined FN/SUB calls, arity/rank mismatches, RESTORE to a
       non-DATA index, unknown statement/expression nodes and the like can
       only arise from hand-built IR, never from a corpus EXE.
    2. TB-illegal constructs the compiler rejects at compile time (nested
       SUB, SWAP across types): no EXE can witness them.
    3. TB-legal but unwitnessed corners, each with the probe status in a
       comment at the site (DIM rank > 3, GOSUB out of a SUB body,
       OnGoto/OnGosub/Resume inside procedures, jumps into procedure
       bodies): these stay refusals -- never mistranslations -- until a
       probe pins the semantics and a fixture witnesses the bytes.
    """


class _Gen:
    """One translation: collects declarations while rendering the body."""

    def __init__(self, stmts, standalone: bool = True):
        self.stmts = list(stmts)
        self.standalone = standalone
        self.orig_lines = getattr(stmts, "lines", None)
        self.vars: dict[str, str] = {}  # mangled -> C declaration
        # name -> (ty, dims, rank); dims is a tuple of (lo, hi) int pairs for a
        # compile-time DIM, or None for a runtime (variable-bound) DIM
        self.arrays: dict[str, tuple[str, tuple[tuple[int, int], ...] | None, int]] = {}
        self.option_base = 0  # current OPTION BASE for int-bound DIMs
        self.fns: list[str] = []  # hoisted inline DEF FN definitions
        self.fn_names: set[str] = set()
        self.fn_params: dict[str, tuple[str, ...]] = {}  # FN name -> params
        self.def_str = False  # the open DEF FN body is string-valued
        self.data: list[tuple[str, bool]] = []
        self.data_offset: dict[int, int] = {}  # top-level stmt index -> data cursor
        self.labels: set[int] = set()
        self.n = 0  # unique-label counter
        self.params: dict[str, str] = {}  # active DEF FN / SUB param name -> C lvalue
        self.subs: dict[str, tuple[str, ...]] = {}  # SUB name -> params
        self.in_sub = False
        self.sub_idx: int | None = None  # top-level index of the open SubDef
        self.in_def = False  # inside a multi-line DEF FN body
        # main labels referenced from inside SUB bodies (GOTO/ON ERROR out of
        # a SUB, witnessed t1_subgoto/t1_suberr): main() stores &&L{t} into a
        # tb_xl{t} pointer at startup, and a cross-function GOTO longjmps back
        # into main's dispatch (setjmp value 2; tb_error uses 1)
        self.xlabels: set[int] = set()
        self.uses_xgoto = False
        self.body_labels: set[tuple[int, int]] = set()  # BodyLine jump targets
        self.uses_eh = False  # ON ERROR / RESUME / ERROR / ERR / ERL present
        self.uses_timer = False  # ON TIMER present: poll at statement boundaries
        self.uses_clear = False  # CLEAR / RUN present: generate tb_clear_all()
        # IDE Options toggles ride on Program.toggles and are honored as
        # compiled, like TB: Bounds gates subscript checks (error 9),
        # Overflow gates integer-store checks (error 6); both default OFF
        tg = getattr(stmts, "toggles", "")
        self.bounds = "B" in tg
        self.overflow = "O" in tg

    def uid(self) -> int:
        self.n += 1
        return self.n

    # --- naming / declarations ---

    def var(self, name: str) -> str:
        if name in self.params:
            return self.params[name]
        # Inside a SUB this is a local static (TB's default, witnessed
        # t1_subdef: values persist across calls) or a SHARED main variable
        # (t1_subsh) -- either way the decoder gave the slot a program-unique
        # name, so one file-scope static per name is exactly TB's storage.
        cty, pre, zero = _VTYPES[_suffix_ty(name)]
        m = pre + _base(name)
        self.vars.setdefault(m, f"static {cty}{'' if cty.endswith('*') else ' '}{m} = {zero};")
        return m

    def array(self, name: str, rank: int):
        if name not in self.arrays:
            self.dim_array(name, (10,) * rank)  # implicit DIM x(10[,10])
        return self.arrays[name]

    def dim_array(self, name: str, bounds) -> list[str]:
        """Register array `name`; returns the allocation code (empty when static).

        Each DIM bound is an int upper bound (lower comes from OPTION BASE), an
        explicit `(lo, hi)` pair (`DIM A(0:4)`), or Exprs for runtime bounds."""
        rank = len(bounds)
        if rank > 4:
            raise _Unsupported("DIM rank > 4 (no witness)")
        ty = _suffix_ty(name)
        norm = [b if isinstance(b, tuple) else (self.option_base, b) for b in bounds]
        if all(isinstance(lo, int) and isinstance(hi, int) for lo, hi in norm):
            self.arrays[name] = (ty, tuple(norm), rank)
            return []
        # runtime bounds: heap allocation at the DIM statement
        self.arrays[name] = (ty, None, rank)
        _, pre, _ = _VTYPES[ty]
        m = "a" + pre + _base(name)
        code = []
        for k, (lo, hi) in enumerate(norm, 1):
            lo_c = str(lo) if isinstance(lo, int) else f"(long)tb_cint({self.num(lo)})"
            hi_c = str(hi) if isinstance(hi, int) else f"(long)tb_cint({self.num(hi)})"
            code.append(f"{m}_lo{k} = {lo_c}; {m}_n{k} = {hi_c} - {m}_lo{k} + 1;")
        total = " * ".join(f"{m}_n{k}" for k in range(1, rank + 1))
        code.append(f"{m} = tb_calloc({total}, sizeof *{m});")
        return code

    # --- expressions ---

    def num(self, e) -> str:
        """Render e as a C double-valued expression."""
        if isinstance(e, _Raw):
            return e.code
        if _is_str(e):
            raise _Unsupported(f"string expression where a number is needed: {e!r}")
        if isinstance(e, ir.Lit):
            return repr(float(e.value)) if isinstance(e.value, float) else str(e.value)
        if isinstance(e, (ir.DblLit, ir.SingleLit)):
            return repr(e.value)
        if isinstance(e, ir.HexLit):
            return f"(double)(short)0x{e.value:X}"
        if isinstance(e, ir.Var):
            return self.var(e.name)
        if isinstance(e, ir.ArrayRef):
            return self.aref(e)
        if isinstance(e, ir.Neg):
            return f"(-({self.num(e.operand)}))"
        if isinstance(e, ir.Not):
            return f"tb_not({self.num(e.operand)})"
        if isinstance(e, ir.Group):
            return f"({self.num(e.inner)})"
        if isinstance(e, (ir.Err, ir.Erl)):
            return "(double)tb_err" if isinstance(e, ir.Err) else "(double)tb_erl"
        if isinstance(e, ir.VarSeg):
            return "0.0"  # a real-mode segment; no modern counterpart
        if isinstance(e, ir.BinOp):
            if e.op == "/":
                return f"tb_div({self.num(e.lhs)}, {self.num(e.rhs)})"
            if e.op in "+-*":
                return f"({self.num(e.lhs)} {e.op} {self.num(e.rhs)})"
            if e.op == "^":
                return f"pow({self.num(e.lhs)}, {self.num(e.rhs)})"
            if e.op in _INT_BINOPS:
                return f"{_INT_BINOPS[e.op]}({self.num(e.lhs)}, {self.num(e.rhs)})"
            if e.op in ("=", "<>", "<", "<=", ">", ">="):
                # comparison in value position: TB truth is -1/0
                return f"({self.cond(ir.RelOp(e.op, e.lhs, e.rhs))} ? -1.0 : 0.0)"
            raise _Unsupported(f"operator {e.op}")
        if isinstance(e, (ir.RelOp, ir.LogOp)):
            return f"({self.cond(e)} ? -1.0 : 0.0)"  # TB truth value
        if isinstance(e, ir.Call):
            if e.name in ("UBOUND", "LBOUND"):
                return self.bound(e)
            return self.call(e, _NUM_FUNCS)
        if isinstance(e, ir.FnCall):
            return self.fncall(e)
        if isinstance(e, ir.Nullary):
            if e.name in _NULLARY:
                return _NULLARY[e.name]
            raise _Unsupported(f"intrinsic {e.name}")
        raise _Unsupported(f"expression {type(e).__name__}")

    def _nullary_str(self, e) -> str:
        if e.name in _NULLARY_STR:
            return _NULLARY_STR[e.name]
        raise _Unsupported(f"string intrinsic {e.name}")

    def s(self, e) -> str:
        """Render e as a C tb_str-valued expression."""
        if isinstance(e, _Raw):
            return e.code
        if isinstance(e, ir.StrLit):
            return f"TB_S({_cstr(e.value)})"
        if isinstance(e, ir.Var):
            return self.var(e.name)
        if isinstance(e, ir.ArrayRef):
            return self.aref(e)
        if isinstance(e, ir.Group):
            return f"({self.s(e.inner)})"
        if isinstance(e, ir.BinOp) and e.op == "+":
            return f"tb_cat({self.s(e.lhs)}, {self.s(e.rhs)})"
        if isinstance(e, ir.Call):
            return self.call(e, _STR_FUNCS)
        if isinstance(e, ir.Nullary):
            return self._nullary_str(e)
        if isinstance(e, ir.FnCall) and e.name.endswith("$"):
            return self.fncall(e)
        raise _Unsupported(f"string expression {type(e).__name__}")

    def call(self, e, table) -> str:
        if e.name == "STRING$" and len(e.args) == 2 and _is_str(e.args[1]):
            # STRING$(n, s$) overload: repeat s$'s first character
            return f"tb_stringSS({self.num(e.args[0])}, {self.s(e.args[1])})"
        # arity-keyed template; each arg renders by its own inferred type
        key = (e.name, len(e.args))
        if key not in table:
            raise _Unsupported(f"intrinsic {e.name}/{len(e.args)}")
        args = [self.s(a) if _is_str(a) else self.num(a) for a in e.args]
        return table[key].format(*args)

    def opt(self, e) -> tuple[str, str]:
        """(has_flag, value) C argument pair for an optional numeric operand."""
        return ("1", self.num(e)) if e is not None else ("0", "0")

    def acap(self, name: str) -> tuple[str, str]:
        """(buffer, capacity-in-bytes) C expressions for a blit array."""
        ty, dims, rank = self.array(name, 1)
        if ty == "STR":
            raise _Unsupported("GET/PUT on a string array")
        _, pre, _ = _VTYPES[ty]
        m = "a" + pre + _base(name)
        if dims is not None:
            return m, f"(long)sizeof {m}"
        n = " * ".join(f"{m}_n{k}" for k in range(1, rank + 1))
        return m, f"({n}) * (long)sizeof *{m}"

    def bound(self, e) -> str:
        # UBOUND(A(k)) / LBOUND(A(k)): the "index" is the dimension number
        (arg,) = e.args
        if not (isinstance(arg, ir.ArrayRef) and isinstance(arg.indices[0], ir.Lit)):
            raise _Unsupported(f"{e.name} with a non-constant dimension")
        k = int(arg.indices[0].value)
        ty, dims, rank = self.array(arg.name, 1)
        if not 1 <= k <= rank:
            raise _Unsupported(f"{e.name} dimension {k} of rank-{rank} array")
        _, pre, _ = _VTYPES[ty]
        m = "a" + pre + _base(arg.name)
        if dims is not None:
            lo, hi = dims[k - 1]
            return f"{lo if e.name == 'LBOUND' else hi}.0"
        if e.name == "LBOUND":
            return f"(double){m}_lo{k}"
        return f"(double)({m}_lo{k} + {m}_n{k} - 1)"

    def fncall(self, e) -> str:
        if e.name not in self.fn_names:
            raise _Unsupported(f"call to undefined {e.name}")
        params = self.fn_params[e.name]
        if len(params) != len(e.args):
            raise _Unsupported(f"{e.name}: arity mismatch")
        args = [
            self.s(a) if p.endswith("$") else self.num(a)
            for p, a in zip(params, e.args)
        ]
        return f"fn_{_base(e.name)}({', '.join(args)})"

    def aref(self, e) -> str:
        # array names are slot-unique too: a SUB-local array got its own DIM
        # inside the body (t1_subad), a SHARED one is the main array (t1_subarr)
        ty, dims, rank = self.array(e.name, len(e.indices))
        if rank != len(e.indices):
            raise _Unsupported(f"rank mismatch on array {e.name}")
        _, pre, _ = _VTYPES[ty]
        m = "a" + pre + _base(e.name)
        idx = []
        for k, i in enumerate(e.indices, 1):
            lo = str(dims[k - 1][0]) if dims is not None else f"{m}_lo{k}"
            raw = f"(long)tb_cint({self.num(i)})"
            if self.bounds:
                n = (
                    str(dims[k - 1][1] - dims[k - 1][0] + 1)
                    if dims is not None
                    else f"{m}_n{k}"
                )
                idx.append(f"tb_bix({raw}, {lo}, {n})")
            else:
                idx.append(f"({raw} - {lo})")
        if rank == 1:
            return f"{m}[{idx[0]}]"
        # row-major private layout; TB's own is column-major, but the order
        # is unobservable short of byte-level blits over rank>=2 arrays
        def ext(k):
            return str(dims[k - 1][1] - dims[k - 1][0] + 1) if dims is not None else f"{m}_n{k}"

        flat = idx[0]
        for k in range(2, rank + 1):
            flat = f"({flat}) * {ext(k)} + ({idx[k - 1]})"
        return f"{m}[{flat}]"

    def cond(self, e) -> str:
        if isinstance(e, ir.RelOp):
            op = {"=": "==", "<>": "!="}.get(e.op, e.op)
            if _is_str(e.lhs) or _is_str(e.rhs):
                return f"(tb_cmp({self.s(e.lhs)}, {self.s(e.rhs)}) {op} 0)"
            return f"({self.num(e.lhs)} {op} {self.num(e.rhs)})"
        if isinstance(e, ir.LogOp):
            c = "&&" if e.op == "AND" else "||"
            return f"({self.cond(e.lhs)} {c} {self.cond(e.rhs)})"
        # numeric-valued condition: TB nonzero = true
        return f"({self.num(e)} != 0)"

    # --- statements ---

    def assign(self, target, value) -> str:
        if isinstance(target, ir.Var):
            dst, ty = self.var(target.name), _suffix_ty(target.name)
        elif isinstance(target, ir.ArrayRef):
            dst, ty = self.aref(target), self.array(target.name, len(target.indices))[0]
        else:
            raise _Unsupported(f"assign target {type(target).__name__}")
        if ty == "STR":
            # every string slot owns a heap copy (tb_sstore frees the old
            # one) -- EXCEPT a DEF FN by-value param, whose current value is
            # the caller's (arena/literal) buffer and must not be freed
            if (
                isinstance(target, ir.Var)
                and target.name in self.params
                and not self.in_sub
            ):
                return f"{dst} = {self.s(value)};"
            return f"{dst} = tb_sstore({dst}, {self.s(value)});"
        return f"{dst} = {self.store_cast(ty).format(self.num(value))};"

    def store_cast(self, ty: str) -> str:
        return (_STORE_CAST_OVF if self.overflow else _STORE_CAST)[ty]

    def gen_print(self, s) -> list[str]:
        out = []
        if s.file is not None:
            out.append(f"tb_out = tb_file({s.file}); tb_ch = {s.file};")
        cs = s.commas or (0,) * (len(s.items) + 1)
        out.extend(["tb_zone();"] * cs[0])
        for i, item in enumerate(s.items):
            if isinstance(item, ir.Call) and item.name in ("TAB", "SPC"):
                out.append(f"tb_{item.name.lower()}({self.num(item.args[0])});")
            elif _is_str(item):
                out.append(f"tb_pss({self.s(item)});")
            else:
                out.append(f"tb_pn({self.num(item)});")
            out.extend(["tb_zone();"] * cs[i + 1])
        if s.newline:
            out.append("tb_nl();")
        if s.file is not None:
            out.append("tb_out = stdout; tb_ch = 0;")
        return out

    def gen_write(self, s) -> list[str]:
        out = []
        if s.file is not None:
            out.append(f"tb_out = tb_file({s.file}); tb_ch = {s.file};")
        for k, item in enumerate(s.items):
            if k:
                out.append('tb_ps(",");')
            if _is_str(item):
                out.append(f"tb_wstr({self.s(item)});")
            else:
                out.append(f"tb_wnum({self.num(item)});")
        out.append("tb_nl();")
        if s.file is not None:
            out.append("tb_out = stdout; tb_ch = 0;")
        return out

    def gen_body(self, body, loops) -> list[str]:
        out = []
        i = 0
        body = list(body)
        while i < len(body):
            out.extend(self.gen(body[i], loops, None))
            i += 1
        return out

    def gen(self, s, loops, idx) -> list[str]:
        """C lines for one statement. `loops` is the open FOR/DO/WHILE label stack
        (shared across nesting so flat FOR..NEXT pairs match); `idx` is the
        top-level statement index or None inside a block body."""
        if self.in_def and isinstance(
            s,
            (ir.Goto, ir.IfGoto, ir.Gosub, ir.Return, ir.OnGoto, ir.OnGosub,
             ir.OnError, ir.Resume),
        ):
            raise _Unsupported(f"{type(s).__name__} inside a DEF FN (targets main labels)")
        if self.in_sub and isinstance(
            s, (ir.OnGoto, ir.OnGosub, ir.Resume)
        ):
            raise _Unsupported(f"{type(s).__name__} inside a SUB")
        if self.in_sub and isinstance(s, (ir.Goto, ir.IfGoto, ir.Gosub, ir.OnError)):
            return self.gen_sub_flow(s)
        if isinstance(s, ir.FnResult):
            if not self.in_def:
                raise _Unsupported("FN result store outside DEF FN")
            v = self.s(s.value) if self.def_str else self.num(s.value)
            return [f"fn_result = {v};"]
        if isinstance(s, ir.ExitDef):
            if not self.in_def:
                raise _Unsupported("EXIT DEF outside DEF FN")
            return ["return fn_result;"]
        if isinstance(s, ir.Assign):
            return [self.assign(s.target, s.value)]
        if isinstance(s, ir.Print):
            return self.gen_print(s)
        if isinstance(s, ir.Write):
            return self.gen_write(s)
        if isinstance(s, ir.End):
            return ["exit(0);"]
        if isinstance(s, (ir.Tron, ir.Troff, ir.DefType)):
            return []
        if isinstance(s, (ir.Goto, ir.IfGoto, ir.Gosub)) and isinstance(
            s.target, ir.BodyLine
        ):
            if isinstance(s, (ir.Goto, ir.IfGoto)) and isinstance(
                self.stmts[s.target.stmt], ir.IfBlock
            ):
                # numbered line inside a main-level block IF (t1_blkgoto):
                # C labels are function-scoped, so a plain goto lands inside
                # the if body with the same semantics as TB
                g = f"goto LB{s.target.stmt}_{s.target.phys};"
                if isinstance(s, ir.IfGoto):
                    return [f"if {self.cond(s.cond)} {{ {g} }}"]
                return [g]
            raise _Unsupported("jump into a procedure body from main")
        if isinstance(s, ir.Goto):
            return [f"goto L{s.target};"]
        if isinstance(s, ir.IfGoto):
            return [f"if {self.cond(s.cond)} goto L{s.target};"]
        if isinstance(s, ir.Gosub):
            n = self.uid()
            return [f"tb_gstack[tb_gsp++] = &&R{n}; goto L{s.target}; R{n}:;"]
        if isinstance(s, ir.Return):
            return ["goto *tb_gstack[--tb_gsp];"]
        if isinstance(s, ir.OnGoto) or isinstance(s, ir.OnGosub):
            n = self.uid()
            lines = [f"switch ((int)tb_cint({self.num(s.selector)})) {{"]
            for k, t in enumerate(s.targets, 1):
                if isinstance(s, ir.OnGoto):
                    lines.append(f"case {k}: goto L{t};")
                else:
                    lines.append(f"case {k}: tb_gstack[tb_gsp++] = &&R{n}; goto L{t};")
            lines.append("}")
            if isinstance(s, ir.OnGosub):
                lines.append(f"R{n}:;")
            return lines
        if isinstance(s, ir.For):
            n = self.uid()
            v = self.var(s.var.name)
            lim, st = f"tb_lim{n}", f"tb_st{n}"
            self.vars[lim] = f"static double {lim} = 0;"
            self.vars[st] = f"static double {st} = 0;"
            loops.append(("FOR", n, s.var.name))
            return [
                self.assign(s.var, s.init),
                f"{lim} = {self.num(s.limit)}; {st} = {self.num(s.step)};",
                f"FCHK{n}: if (!({st} >= 0 ? {v} <= {lim} : {v} >= {lim})) goto FDONE{n};",
            ]
        if isinstance(s, ir.NextStmt):
            for j in range(len(loops) - 1, -1, -1):
                if loops[j][0] == "FOR" and loops[j][2] == s.var.name:
                    _, n, _ = loops.pop(j)
                    v = self.var(s.var.name)
                    cast = self.store_cast(_suffix_ty(s.var.name))
                    stv = f"{v} = {cast.format(f'{v} + tb_st{n}')};"
                    return [stv, f"goto FCHK{n};", f"FDONE{n}:;"]
            raise _Unsupported(f"NEXT {s.var.name} without open FOR")
        if isinstance(s, ir.While):
            n = self.uid()
            loops.append(("WHILE", n, None))
            return [f"WTOP{n}: if (!{self.cond(s.cond)}) goto WDONE{n};"]
        if isinstance(s, ir.Wend):
            for j in range(len(loops) - 1, -1, -1):
                if loops[j][0] == "WHILE":
                    _, n, _ = loops.pop(j)
                    return [f"goto WTOP{n};", f"WDONE{n}:;"]
            raise _Unsupported("WEND without open WHILE")
        if isinstance(s, ir.Do):
            n = self.uid()
            loops.append(("DO", n, None))
            top = [f"DTOP{n}:;"]
            if s.kind == "WHILE":
                top.append(f"if (!{self.cond(s.cond)}) goto DDONE{n};")
            elif s.kind == "UNTIL":
                top.append(f"if {self.cond(s.cond)} goto DDONE{n};")
            return top
        if isinstance(s, ir.Loop):
            for j in range(len(loops) - 1, -1, -1):
                if loops[j][0] == "DO":
                    _, n, _ = loops.pop(j)
                    if s.kind == "WHILE":
                        return [f"if {self.cond(s.cond)} goto DTOP{n};", f"DDONE{n}:;"]
                    if s.kind == "UNTIL":
                        return [f"if (!{self.cond(s.cond)}) goto DTOP{n};", f"DDONE{n}:;"]
                    return [f"goto DTOP{n};", f"DDONE{n}:;"]
            raise _Unsupported("LOOP without open DO")
        if isinstance(s, ir.ExitFor):
            for kind, n, _ in reversed(loops):
                if kind == "FOR":
                    return [f"goto FDONE{n};"]
            raise _Unsupported("EXIT FOR outside FOR")
        if isinstance(s, ir.ExitLoop):
            for kind, n, _ in reversed(loops):
                if kind == "DO":
                    return [f"goto DDONE{n};"]
            raise _Unsupported("EXIT LOOP outside DO")
        if isinstance(s, ir.IfInline):
            return [f"if {self.cond(s.cond)} {{", *self.gen_body(s.body, loops), "}"]
        if isinstance(s, ir.IfBlock):
            lines = []
            for k, (cond, body) in enumerate(s.arms):
                kw = "if" if k == 0 else "} else if"
                lines.append(f"{kw} {self.cond(cond)} {{")
                if (
                    idx is not None
                    and k == 0
                    and any((idx, p) in self.body_labels for p in range(1, 99))
                ):
                    # a numbered interior line is jump-targeted (t1_blkgoto);
                    # phys p = body statement p-1, single-arm only (the
                    # decoder resolves BodyLine only for that shape)
                    for p, b in enumerate(body, 1):
                        if (idx, p) in self.body_labels:
                            lines.append(f"LB{idx}_{p}:;")
                        if isinstance(b, ir.IfBlock):
                            # The decoder's BodyLine phys now counts flat
                            # through a NESTED single-arm block too (wild
                            # inv87.exe), but that phys numbering doesn't
                            # match this loop's local per-body `p` -- c0
                            # would need to thread a phys offset into the
                            # nested block to find ITS OWN interior labels,
                            # which isn't implemented. Fail loud rather than
                            # silently emit an unreachable `goto`.
                            raise _Unsupported(
                                "body-line label inside a nested block IF"
                            )
                        lines.extend(self.gen(b, loops, None))
                    continue
                lines.extend(self.gen_body(body, loops))
            if s.else_body is not None:
                lines.append("} else {")
                lines.extend(self.gen_body(s.else_body, loops))
            lines.append("}")
            return lines
        if isinstance(s, ir.SelectCase):
            n = self.uid()
            is_str = _is_str(s.selector)
            sel = f"tb_sel{n}"
            self.vars[sel] = (
                f"static tb_str {sel} = {{0, 0}};"
                if is_str
                else f"static double {sel} = 0;"
            )
            lines = [f"{sel} = {self.s(s.selector) if is_str else self.num(s.selector)};"]

            def guard(g) -> str:
                if isinstance(g, ir.CaseValue):
                    if is_str:
                        return f"(tb_cmp({sel}, {self.s(g.value)}) == 0)"
                    return f"({sel} == {self.num(g.value)})"
                if isinstance(g, ir.CaseRange):
                    if is_str:
                        return (
                            f"(tb_cmp({sel}, {self.s(g.lo)}) >= 0 && "
                            f"tb_cmp({sel}, {self.s(g.hi)}) <= 0)"
                        )
                    return f"({sel} >= {self.num(g.lo)} && {sel} <= {self.num(g.hi)})"
                if isinstance(g, ir.CaseIs):
                    op = {"=": "==", "<>": "!="}.get(g.op, g.op)
                    if is_str:
                        return f"(tb_cmp({sel}, {self.s(g.value)}) {op} 0)"
                    return f"({sel} {op} {self.num(g.value)})"
                raise _Unsupported(f"case guard {type(g).__name__}")

            for k, arm in enumerate(s.arms):
                kw = "if" if k == 0 else "} else if"
                lines.append(f"{kw} ({' || '.join(guard(g) for g in arm.guards)}) {{")
                lines.extend(self.gen_body(arm.body, loops))
            if s.case_else is not None:
                lines.append("} else {")
                lines.extend(self.gen_body(s.case_else, loops))
            lines.append("}")
            return lines
        if isinstance(s, ir.Dim):
            out = []
            for name, bounds in ((s.name, s.bounds), *s.also):
                out.extend(self.dim_array(name, bounds))
            return out
        if isinstance(s, ir.OptionBase):
            self.option_base = s.n  # lower bound of subsequent int-bound DIMs
            return []
        if isinstance(s, ir.Data):
            if idx is not None:
                self.data_offset[idx] = len(self.data)
            self.data.extend((it.text, it.is_str) for it in s.items)
            return []
        if isinstance(s, ir.Read):
            out = []
            for t in s.targets:
                ty = (
                    _suffix_ty(t.name)
                    if isinstance(t, (ir.Var, ir.ArrayRef))
                    else "NUM"
                )
                src = (
                    "tb_borrow(tb_data[tb_data_p++])"
                    if ty == "STR"
                    else "tb_val(tb_borrow(tb_data[tb_data_p++]))"
                )
                out.append(self.assign(t, _Raw(src, ty == "STR")))
            return out
        if isinstance(s, ir.Restore):
            off = 0 if s.target is None else self.data_offset.get(s.target)
            if off is None:
                raise _Unsupported("RESTORE to a non-DATA statement")
            return [f"tb_data_p = {off};"]
        if isinstance(s, ir.Input):
            prompt = (
                f"TB_S({_cstr(s.prompt.value)})"
                if s.prompt is not None
                else "((tb_str){0, 0})"
            )
            mark = 0 if (s.prompt is not None and s.comma) else 1
            if s.semi:  # `INPUT;` keeps the cursor on the line (bit 1)
                mark |= 2
            if isinstance(s.var, tuple):  # multi-target: one line, CSV fields
                out = [f"tb_input_begin({prompt}, {mark});"]
                for v in s.var:
                    is_str = _suffix_ty(v.name) == "STR"
                    nfn = "tb_input_next_str" if is_str else "tb_input_next_num"
                    out.append(self.assign(v, _Raw(f"{nfn}()", is_str)))
                return out
            fn = "tb_input_str" if _suffix_ty(s.var.name) == "STR" else "tb_input_num"
            return [self.assign(s.var, _Raw(f"{fn}({prompt}, {mark})", fn.endswith("str")))]
        if isinstance(s, ir.LineInput):
            if s.file is not None:
                return [
                    self.assign(s.var, _Raw(f"tb_finput_line({s.file})", True))
                ]
            prompt = (
                f"TB_S({_cstr(s.prompt.value)})"
                if s.prompt is not None
                else "((tb_str){0, 0})"
            )
            return [self.assign(s.var, _Raw(f"tb_input_str({prompt}, 0)", True))]
        if isinstance(s, ir.Swap):
            def _lv(v):
                if isinstance(v, ir.Var):
                    return self.var(v.name), _suffix_ty(v.name)
                if isinstance(v, ir.ArrayRef):
                    return self.aref(v), self.array(v.name, len(v.indices))[0]
                raise _Unsupported(f"SWAP operand {type(v).__name__}")

            a, ta = _lv(s.a)
            b, tb_ = _lv(s.b)
            if ta != tb_:
                raise _Unsupported("SWAP across types")
            cty, _, _ = _VTYPES[ta]
            return [f"{{ {cty} t = {a}; {a} = {b}; {b} = t; }}"]
        if isinstance(s, ir.Beep):
            return ['tb_ps("\\a");']
        if isinstance(s, ir.Cls):
            return [
                'tb_esc("\\033[2J\\033[H"); tb_cols[0] = 0; tb_row = 0;',
                "if (tb_fb) { memset(tb_fb, 0, (size_t)tb_gw * tb_gh); tb_present(); }",
            ]
        if isinstance(s, ir.Delay):
            return [f"tb_delay({self.num(s.secs)});"]
        if isinstance(s, ir.Randomize):
            return [f"tb_randomize({self.num(s.seed)});"]
        if isinstance(s, ir.MidAssign):
            # in-place overlay: the target keeps its length; the owned
            # buffer is writable, so patch it directly
            tgt = self.var(s.target.name)
            n = self.uid()
            return [
                f"{{ tb_str m{n} = {self.s(s.source)};",
                f"  long p{n} = tb_i({self.num(s.start)}) - 1;",
                f"  for (long k{n} = 0; k{n} < m{n}.n && p{n} + k{n} < {tgt}.n; k{n}++)"
                f" {tgt}.p[p{n} + k{n}] = m{n}.p[k{n}]; }}",
            ]
        if isinstance(s, ir.DefFn):
            self.gen_deffn(s)
            return []
        if isinstance(s, ir.SubDef):
            self.gen_subdef(s, idx)
            return []
        if isinstance(s, ir.Shared):
            # scope declaration only: the decoder already resolved every name
            # to its program-unique slot, so there is nothing to generate
            return []
        if isinstance(s, ir.Common):
            # declaration only under c0: variables are file-scope globals
            # anyway, and tb_chain (a documented surrogate) does not carry
            # COMMON values into the chained program
            return []
        if isinstance(s, ir.Local):
            # true per-call locals need real (non-static) C storage, re-zeroed
            # every call -- the SUB-local declaration pass below doesn't
            # distinguish that from the default local-and-static scoping yet
            raise _Unsupported("LOCAL statement (per-call SUB locals)")
        if isinstance(s, ir.CallStmt):
            return self.gen_call(s)
        if isinstance(s, ir.ExitSub):
            if not self.in_sub:
                raise _Unsupported("EXIT SUB outside SUB")
            return ["return;"]
        if isinstance(s, ir.Open):
            if s.mode.value.upper() == "R":
                rl = "128" if s.reclen is None else f"tb_i({self.num(s.reclen)})"
                return [f"tb_open_r({s.num}, {self.s(s.file)}, {rl});"]
            if s.reclen is not None:
                # sequential-mode reclen is only a DOS buffer-size hint
                raise _Unsupported(f"OPEN {s.mode.value!r} with reclen")
            mode = {"I": '"r"', "O": '"w"', "A": '"a"'}.get(s.mode.value.upper())
            if mode is None:
                raise _Unsupported(f"OPEN mode {s.mode.value!r}")
            return [f"tb_open({mode}, {s.num}, {self.s(s.file)});"]
        if isinstance(s, ir.Field):
            out = [f"tb_field_start({s.num});"]
            for w, v in s.fields:
                out.append(
                    f"tb_field_reg({s.num}, &{self.var(v.name)}, tb_i({self.num(w)}));"
                )
            return out
        if isinstance(s, (ir.Lset, ir.Rset)):
            right = int(isinstance(s, ir.Rset))
            return [f"tb_lsetrset(&{self.var(s.target.name)}, {self.s(s.source)}, {right});"]
        if isinstance(s, ir.Get):
            return [f"tb_getrec({s.num}, {self.num(s.pos)});"]
        if isinstance(s, ir.Put):
            return [f"tb_putrec({s.num}, {self.num(s.pos)});"]
        if isinstance(s, ir.Seek):
            # SEEK on a random-mode channel is TB error 54 (t1_seek dosout)
            return [f"tb_seek({s.num}, {self.num(s.pos)});"]
        if isinstance(s, ir.Close):
            if s.num is None:  # bare CLOSE: all channels, like RESET
                return ["tb_reset();"]
            n = s.num if isinstance(s.num, int) else f"tb_i({self.num(s.num)})"
            return [f"tb_close({n});"]
        if isinstance(s, ir.Reset):
            return ["tb_reset();"]
        if isinstance(s, ir.InputFile):
            out = []
            for t in s.vars:
                is_s = _suffix_ty(t.name) == "STR"
                fn = "tb_finput_str" if is_s else "tb_finput_num"
                out.append(self.assign(t, _Raw(f"{fn}({s.num})", is_s)))
            return out
        if isinstance(s, ir.OnError):
            if s.target is None:
                return ["tb_handler = 0;"]
            self.labels.add(s.target)
            return [f"tb_handler = &&L{s.target};"]
        if isinstance(s, ir.Resume):
            if s.target is not None:
                self.labels.add(s.target)
                return [f"goto L{s.target};"]
            return ["goto *tb_next;" if s.next_ else "goto *tb_stmt;"]
        if isinstance(s, ir.ErrorStmt):
            return [f"tb_error((int)tb_cint({self.num(s.code)}));"]
        if isinstance(s, ir.Erase):
            ty, dims, rank = self.array(s.name, 1)
            _, pre, _ = _VTYPES[ty]
            m = "a" + pre + _base(s.name)
            if dims is not None:
                return [f"memset({m}, 0, sizeof {m});"]
            return [f"free({m}); {m} = 0;"]
        if isinstance(s, ir.Key):
            return []  # soft-key display line: no modern-terminal counterpart
        if isinstance(s, ir.KeyDef):
            # F-key macro definitions feed the BIOS keyboard buffer; there is
            # no modern-terminal counterpart (same surrogate as KEY ON/OFF)
            return []
        if isinstance(s, ir.Locate):
            out = [f"tb_locate({self.num(s.row)}, {self.num(s.col)});"]
            if s.cursor is not None:
                out.append(
                    f'tb_ps(tb_i({self.num(s.cursor)}) ? "\\033[?25h" : "\\033[?25l");'
                )
            return out
        if isinstance(s, ir.Color):
            if s.border is not None:
                # CGA/EGA text-mode border color: no visible effect in the
                # PPM/SDL framebuffer surrogate (the border strip is outside
                # the captured display), but silently dropping a value the
                # source explicitly set would mistranslate -- fail loud.
                raise _Unsupported("COLOR border argument")
            fg = self.num(s.fg) if s.fg is not None else "0"
            bg = self.num(s.bg) if s.bg is not None else "0"
            has_fg = "1" if s.fg is not None else "0"
            has_bg = "1" if s.bg is not None else "0"
            return [f"tb_color({has_fg}, {fg}, {has_bg}, {bg});"]
        if isinstance(s, ir.Shell):
            return [f"if (system(tb_cs({self.s(s.cmd)}))) {{}}"]
        if isinstance(s, ir.Chdir):
            # a missing path is TB error 76 (witnessed: t1_chdir dosout)
            return [f"tb_chdir({self.s(s.path)});"]
        if isinstance(s, ir.Environ):
            # putenv keeps the pointer: hand it an owned heap copy
            return [f"putenv(tb_sstore((tb_str){{0, 0}}, {self.s(s.s)}).p);"]
        if isinstance(s, ir.Kill):
            # a missing file is TB error 53 (witnessed: t1_kill dosout)
            return [f"if (remove(tb_cs({self.s(s.file)}))) tb_error(53);"]
        if isinstance(s, ir.Name):
            # a missing source file is TB error 53 (witnessed: t1_name dosout)
            return [f"if (rename(tb_cs({self.s(s.old)}), tb_cs({self.s(s.new)}))) tb_error(53);"]
        if isinstance(s, ir.Files):
            return [f"tb_files_({self.s(s.spec)});"]
        if isinstance(s, ir.DateTimeSet):
            fn = "tb_set_date" if s.name == "DATE$" else "tb_set_time"
            return [f"{fn}({self.s(s.value)});"]
        if isinstance(s, ir.Screen):
            # burst (composite-monitor color) has no meaning on the
            # framebuffer surrogate; page args only as the single page 0
            for pg in (s.apage, s.vpage):
                if pg is not None and pg != ir.Lit(0):
                    raise _Unsupported("SCREEN page argument (single-page surrogate)")
            return [f"tb_screen({self.num(s.mode)});"]
        if isinstance(s, ir.Pset):
            hc, c = self.opt(s.color)
            return [
                f"tb_pset({self.num(s.x)}, {self.num(s.y)}, {int(s.step)}, "
                f"{hc}, {c}, {int(s.preset)});"
            ]
        if isinstance(s, ir.LineStmt):
            hc, c = self.opt(s.color)
            style = (
                f"(unsigned)tb_i({self.num(s.style)})" if s.style is not None else "0xFFFFu"
            )
            return [
                f"tb_linestmt({self.num(s.x1)}, {self.num(s.y1)}, {int(s.step1)}, "
                f"{self.num(s.x2)}, {self.num(s.y2)}, {int(s.step2)}, "
                f"{hc}, {c}, {int(s.box != '')}, {int(s.box == 'BF')}, {style});"
            ]
        if isinstance(s, ir.Circle):
            hc, c = self.opt(s.color)
            sa = self.num(s.start) if s.start is not None else "0"
            ea = self.num(s.end) if s.end is not None else "0"
            asp = self.num(s.aspect) if s.aspect is not None else "-1"
            return [
                f"tb_circle({self.num(s.x)}, {self.num(s.y)}, {self.num(s.r)}, "
                f"{int(s.step)}, {hc}, {c}, {sa}, {ea}, {asp});"
            ]
        if isinstance(s, ir.Paint):
            if s.paint is not None and _is_str(s.paint):
                raise _Unsupported("PAINT tile pattern")
            hp, p = self.opt(s.paint)
            hb, b = self.opt(s.border)
            return [f"tb_paint({self.num(s.x)}, {self.num(s.y)}, {hp}, {p}, {hb}, {b});"]
        if isinstance(s, ir.GetGfx):
            m, cap = self.acap(s.array)
            return [
                f"tb_getgfx({m}, {cap}, {self.num(s.x1)}, {self.num(s.y1)}, "
                f"{self.num(s.x2)}, {self.num(s.y2)});"
            ]
        if isinstance(s, ir.PutGfx):
            try:
                action = {None: 0, "XOR": 0, "PSET": 1, "PRESET": 2, "AND": 3, "OR": 4}[
                    s.action
                ]
            except KeyError:
                raise _Unsupported(f"PUT action {s.action}") from None
            m, cap = self.acap(s.array)
            return [f"tb_putgfx({m}, {cap}, {self.num(s.x)}, {self.num(s.y)}, {action});"]
        if isinstance(s, ir.View):
            hc, c = self.opt(s.color)
            hb, b = self.opt(s.border)
            return [
                f"tb_view(1, {self.num(s.x1)}, {self.num(s.y1)}, {self.num(s.x2)}, "
                f"{self.num(s.y2)}, {int(s.screen)}, {hc}, {c}, {hb}, {b});"
            ]
        if isinstance(s, ir.Window):
            return [
                f"tb_window(1, {self.num(s.x1)}, {self.num(s.y1)}, {self.num(s.x2)}, "
                f"{self.num(s.y2)}, {int(s.screen)});"
            ]
        if isinstance(s, ir.Draw):
            return [f"tb_draw({self.s(s.cmd)});"]
        if isinstance(s, ir.OnTrap):
            if s.event == "TIMER":
                return [
                    f"tb_timer_hdl = &&L{s.target}; tb_timer_iv = {self.num(s.n)}; "
                    "tb_timer_due_at = tb_mono() + tb_timer_iv;"
                ]
            # COM/KEY/PEN/PLAY have no event source on a modern host: the
            # handler can never fire, so installing only takes its address.
            # The dead handler's RETURN is still a goto*, and clang rejects
            # indirect goto in a function with no &&label expression at all.
            return [
                f"if (0) tb_gstack[tb_gsp++] = &&L{s.target};"
                f"  /* ON {s.event} GOSUB: no {s.event} event source on this host */"
            ]
        if isinstance(s, ir.TrapCtl):
            if s.event == "TIMER":
                if s.mode == "ON":
                    return ["tb_timer_on = 1; tb_timer_due_at = tb_mono() + tb_timer_iv;"]
                return ["tb_timer_on = 0;"]
            if s.event == "PEN":
                # tracked so PEN(n) can error while OFF (t1_penf dosout)
                return [f"tb_pen_on = {int(s.mode == 'ON')};"]
            return [f"/* {s.event} {s.mode}: no {s.event} event source on this host */"]
        if isinstance(s, ir.Clear):
            self.uses_clear = True
            return ["tb_clear_all();"]
        if isinstance(s, ir.Run):
            if s.file is not None:
                raise _Unsupported("RUN file$ (loads a different program)")
            self.uses_clear = True
            out = ["tb_clear_all();"]
            if self.data:
                out.append("tb_data_p = 0;")
            out.append("goto L0;")
            return out
        if isinstance(s, ir.Palette):
            return [
                f"tb_pal[tb_i({self.num(s.attr)}) & 15] = "
                f"(int)tb_i({self.num(s.color)}) & 15; tb_present();"
            ]
        if isinstance(s, ir.Mtimer):
            return ["tb_mt0 = tb_mono();"]
        if isinstance(s, ir.Lprint):
            # LPRINT reaches the printer, never the screen (t1_lprint dosout:
            # empty). Sink: TB_LPRINT_TXT=file captures it, else discarded.
            # Channel 15 keeps its own TAB/SPC column like a real LPT.
            return [
                "tb_out = tb_lpt(); tb_ch = 15;",
                *self.gen_print(ir.Print(items=s.items, newline=s.newline)),
                "tb_out = stdout; tb_ch = 0;",
            ]
        if isinstance(s, ir.PrintUsing):
            out = []
            if s.lprint:  # LPRINT USING: printer sink, same as ir.Lprint
                out.append("tb_out = tb_lpt(); tb_ch = 15;")
            elif s.file is not None:
                out.append(f"tb_out = tb_file({s.file}); tb_ch = {s.file};")
            out.append(f"tb_pu_begin({self.s(s.fmt)});")
            out.extend(
                f"tb_pu_sval({self.s(v)});" if _is_str(v) else f"tb_pu_val({self.num(v)});"
                for v in s.values
            )
            out.append("tb_pu_flush();")
            if s.newline:
                out.append("tb_nl();")
            if s.lprint or s.file is not None:
                out.append("tb_out = stdout; tb_ch = 0;")
            return out
        if isinstance(s, ir.Mkdir):
            return [f"tb_mkdir({self.s(s.path)});"]
        if isinstance(s, ir.Rmdir):
            # a missing directory is TB error 75 (witnessed: t1_rmdir dosout)
            return [f"tb_rmdir({self.s(s.path)});"]
        if isinstance(s, ir.Play):
            # decode the MML to PCM; TB_PLAY_WAV=out.wav dumps it at exit
            return [f"tb_play({self.s(s.music)});"]
        if isinstance(s, ir.KeyList):
            # KEY LIST prints the twelve (empty) soft keys (t1_keylist dosout)
            n = self.uid()
            return [
                f'for (int k{n} = 1; k{n} <= 12; k{n}++) '
                f'{{ char b{n}[8]; sprintf(b{n}, "F%d ", k{n}); tb_ps(b{n}); tb_nl(); }}'
            ]
        if isinstance(s, (ir.Sound, ir.Width)):
            # no audio device or fixed-width console here
            return [f"/* {type(s).__name__}: no device counterpart on this host */"]
        if isinstance(s, ir.Poke):
            return [f"tb_poke({self.num(s.addr)}, {self.num(s.value)});"]
        if isinstance(s, ir.Out):
            return [f"tb_outp({self.num(s.port)}, {self.num(s.value)});"]
        if isinstance(s, ir.Wait):
            xr = self.num(s.xor) if s.xor is not None else "0"
            return [f"tb_wait({self.num(s.port)}, {self.num(s.mask)}, {xr});"]
        if isinstance(s, ir.DefSeg):
            has, seg = self.opt(s.seg)
            return [f"tb_defseg({has}, {seg});"]
        if isinstance(s, ir.RegSet):
            return [f"tb_regset({self.num(s.n)}, {self.num(s.value)});"]
        if isinstance(s, ir.CallInterrupt):
            return [f"tb_callint({self.num(s.n)});"]
        if isinstance(s, ir.CallAbsolute):
            # transpiles, then aborts if reached: the emulated memory never
            # holds runnable machine code
            return [f"tb_callabs({self.num(s.addr)});"]
        if isinstance(s, ir.Bload):
            off = "0" if s.offset is None else self.num(s.offset)
            return [f"tb_bload({self.s(s.file)}, {off});"]
        if isinstance(s, ir.Bsave):
            return [
                f"tb_bsave({self.s(s.file)}, {self.num(s.offset)}, "
                f"{self.num(s.length)});"
            ]
        if isinstance(s, ir.Chain):
            return [f"tb_chain({self.s(s.file)});"]
        raise _Unsupported(f"statement {type(s).__name__}")

    def gen_deffn(self, s) -> None:
        is_str = s.name.endswith("$")
        old = self.params
        self.params = {p: f"p_{_base(p)}" for p in s.params}
        args = ", ".join(
            f"{'tb_str ' if p.endswith('$') else 'double '}p_{_base(p)}"
            for p in s.params
        ) or "void"
        rty, zero = ("tb_str ", "{0, 0}") if is_str else ("double ", "0")
        try:
            if not s.is_block:
                body = self.s(s.body) if is_str else self.num(s.body)
                self.fns.append(
                    f"static {rty}fn_{_base(s.name)}({args}) {{ return {body}; }}"
                )
            else:
                self.in_def = True
                self.def_str = is_str
                try:
                    lines = self.gen_body(s.body, [])
                finally:
                    self.in_def = False
                self.fns.append(
                    "\n".join(
                        [
                            f"static {rty}fn_{_base(s.name)}({args}) {{",
                            f"    {rty}fn_result = {zero};",
                            *("    " + ln for ln in lines),
                            "    return fn_result;",
                            "}",
                        ]
                    )
                )
        finally:
            self.params = old
        self.fn_names.add(s.name)
        self.fn_params[s.name] = s.params

    def gen_subdef(self, s, idx) -> None:
        if self.in_sub:
            raise _Unsupported("nested SUB")
        self.subs[s.name] = s.params
        old = self.params
        self.params = {p: f"(*p_{_base(p)})" for p in s.params}
        self.in_sub = True
        self.sub_idx = idx
        try:
            body, loops, multi = [], [], False
            for k, b in enumerate(s.body):
                if (idx, k + 1) in self.body_labels:
                    # a GOSUB/GOTO targets this body physical line (t1_subgsb);
                    # phys == k+1 only holds while every prior body statement
                    # is single-line, as the decoder enforced at fold time
                    if multi:
                        raise _Unsupported(
                            "body-line label past a multi-line statement in SUB"
                        )
                    body.append(f"LB{idx}_{k + 1}:;")
                if isinstance(b, (ir.IfBlock, ir.SelectCase)):
                    multi = True
                body.extend(self.gen(b, loops, None))
            if loops:
                raise _Unsupported("unclosed loop in SUB body")
        finally:
            self.in_sub = False
            self.sub_idx = None
            self.params = old
        sig = []
        for p in s.params:
            cty, _, _ = _VTYPES[_suffix_ty(p)]
            sig.append(f"{cty}{'' if cty.endswith('*') else ' '}*p_{_base(p)}")
        head = f"static void sub_{_base(s.name)}({', '.join(sig) or 'void'}) {{"
        self.fns.append("\n".join([head, *("    " + ln for ln in body), "}"]))

    def gen_sub_flow(self, s) -> list[str]:
        """GOTO/GOSUB/ON ERROR inside a SUB body (witnessed t1_subgoto,
        t1_subgsb, t1_suberr). Body-line targets stay function-local labels;
        main-label targets go through the tb_xl* pointers. GOSUB can only
        target the SUB's own body: labels-as-values cannot RETURN into
        another function, and no probe witnesses TB accepting more."""
        if isinstance(s, ir.OnError):
            if s.target is None:
                return ["tb_handler = 0;"]
            if isinstance(s.target, ir.BodyLine):
                raise _Unsupported("ON ERROR GOTO a procedure body line")
            return [f"tb_handler = {self.xlabel(s.target)};"]
        if isinstance(s, ir.Gosub):
            if not isinstance(s.target, ir.BodyLine) or s.target.stmt != self.sub_idx:
                raise _Unsupported("GOSUB out of a SUB body (no witness)")
            n = self.uid()
            return [
                f"tb_gstack[tb_gsp++] = &&R{n}; "
                f"goto LB{s.target.stmt}_{s.target.phys}; R{n}:;"
            ]
        if isinstance(s.target, ir.BodyLine):  # Goto / IfGoto within this SUB
            if s.target.stmt != self.sub_idx:
                raise _Unsupported("GOTO into another procedure body")
            g = f"goto LB{s.target.stmt}_{s.target.phys};"
        else:
            self.uses_xgoto = True
            g = f"tb_xgoto = {self.xlabel(s.target)}; longjmp(tb_env, 2);"
        if isinstance(s, ir.IfGoto):
            return [f"if {self.cond(s.cond)} {{ {g} }}"]
        return [g]

    def xlabel(self, t: int) -> str:
        self.xlabels.add(t)
        return f"tb_xl{t}"

    def gen_call(self, s) -> list[str]:
        if s.name not in self.subs:
            raise _Unsupported(f"CALL to unknown SUB {s.name}")
        params = self.subs[s.name]
        if len(params) != len(s.args):
            raise _Unsupported(f"CALL {s.name}: arity mismatch")
        tmps, args = [], []
        for p, a in zip(params, s.args):
            ty = _suffix_ty(p)
            # a plain variable (or array element) of matching type passes by
            # reference, TB semantics (zz_sub1); anything else by value copy
            if isinstance(a, ir.Var) and _suffix_ty(a.name) == ty:
                args.append(f"&{self.var(a.name)}")
            elif (
                isinstance(a, ir.ArrayRef)
                and not self.in_sub
                and self.array(a.name, len(a.indices))[0] == ty
            ):
                args.append(f"&{self.aref(a)}")
            else:
                cty, _, _ = _VTYPES[ty]
                t = f"t{self.uid()}"
                if ty == "STR":
                    # the temp must be an OWNED slot: the SUB may assign
                    # through the reference (tb_sstore frees the old buffer)
                    val = f"tb_sstore((tb_str){{0, 0}}, {self.s(a)})"
                else:
                    val = self.store_cast(ty).format(self.num(a))
                tmps.append(f"{cty}{'' if cty.endswith('*') else ' '}{t} = {val};")
                args.append(f"&{t}")
        call = f"sub_{_base(s.name)}({', '.join(args)});"
        if tmps:
            frees = [
                f"free({t.split()[1]}.p);"
                for t in tmps
                if t.startswith("tb_str ")
            ]
            return ["{", *tmps, call, *frees, "}"]
        return [call]

    # --- whole program ---

    def build(self) -> str:
        # collect label targets and error-handling usage across the whole tree
        def walk(node):
            if isinstance(node, (ir.Goto, ir.IfGoto, ir.Gosub)):
                if isinstance(node.target, int):
                    self.labels.add(node.target)
                elif isinstance(node.target, ir.BodyLine):
                    self.body_labels.add((node.target.stmt, node.target.phys))
            if isinstance(node, (ir.OnGoto, ir.OnGosub)):
                self.labels.update(t for t in node.targets if isinstance(t, int))
            if isinstance(node, (ir.OnError, ir.Resume)):
                self.uses_eh = True
                if isinstance(node.target, int):
                    self.labels.add(node.target)
            if isinstance(node, (ir.ErrorStmt, ir.Err, ir.Erl)):
                self.uses_eh = True
            if isinstance(node, ir.OnTrap):
                if isinstance(node.target, int):
                    self.labels.add(node.target)
                if node.event == "TIMER":
                    self.uses_timer = True
            if isinstance(node, ir.Run) and node.file is None:
                self.labels.add(0)
            for f in getattr(node, "__dataclass_fields__", ()):
                v = getattr(node, f)
                for item in v if isinstance(v, tuple) else (v,):
                    if hasattr(item, "__dataclass_fields__"):
                        walk(item)

        for st in self.stmts:
            walk(st)

        body: list[str] = []
        loops: list[tuple[str, int, str | None]] = []
        for i, st in enumerate(self.stmts):
            # ERL/tb_erl reports the emitted source's line numbers
            # (Program.lines when the error-trap table pinned them, else
            # 10, 20, ... -- the same rule emit0 applies)
            ln = self.orig_lines[i] if self.orig_lines is not None else 10 * (i + 1)
            if self.uses_eh:
                # every statement gets a label plus RESUME bookkeeping
                body.append(f"L{i}:;")
                body.append(f"tb_stmt = &&L{i}; tb_next = &&L{i + 1}; tb_erl = {ln};")
            else:
                if i in self.labels:
                    body.append(f"L{i}:;")
                body.append(f"tb_erl = {ln};")
            if self.uses_timer:
                # TB checks pending traps between statements
                body.append(
                    f"if (tb_timer_due()) {{ tb_gstack[tb_gsp++] = &&T{i}; "
                    f"goto *tb_timer_hdl; }} T{i}:;"
                )
            # statement boundary: release string-expression temporaries
            # (top level only -- SUB/DEF FN bodies run inside the caller's
            # statement, so their temps must survive until it ends)
            body.append("tb_sr();")
            body.extend(self.gen(st, loops, i))
        if self.uses_eh:
            body.append(f"L{len(self.stmts)}:;")
        if loops:
            raise _Unsupported(f"unclosed loop(s): {[k for k, *_ in loops]}")

        parts = [
            _PRELUDE
            if self.standalone
            else "/* generated by tbx --emit-c --no-runtime : link against"
            ' libtbrt.a (make in c0_runtime/) */\n#include "tb_runtime.h"\n'
        ]
        if self.data:
            items = ", ".join(_cstr(t) for t, _ in self.data)
            parts.append(f"static const char *tb_data[] = {{ {items} }};")
            parts.append("static int tb_data_p = 0;")
        for name, (ty, dims, rank) in sorted(self.arrays.items()):
            cty, pre, _ = _VTYPES[ty]
            sep = "" if cty.endswith("*") else " "
            m = f"a{pre}{_base(name)}"
            if dims is not None:
                size = " * ".join(str(hi - lo + 1) for lo, hi in dims)
                parts.append(f"static {cty}{sep}{m}[{size}] = {{0}};")
            else:
                parts.append(f"static {cty}{sep}*{m} = 0;")
                for k in range(1, rank + 1):
                    parts.append(f"static long {m}_lo{k} = 0, {m}_n{k} = 0;")
        parts.extend(self.vars[k] for k in sorted(self.vars))
        for t in sorted(self.xlabels):
            parts.append(f"static void *tb_xl{t};")
        if self.uses_xgoto:
            parts.append("static void *tb_xgoto;")
        if self.uses_clear:
            parts.append("static void tb_clear_all(void);")
        parts.extend(self.fns)
        parts.append("int main(int argc, char **argv) {")
        parts.append("    tb_argc = argc; tb_argv = argv;")
        for t in sorted(self.xlabels):
            # main-label addresses for GOTO/ON ERROR inside SUB bodies
            parts.append(f"    tb_xl{t} = &&L{t};")
        if self.uses_xgoto:
            # tb_error longjmps with 1, a cross-function GOTO with 2
            parts.append(
                "    switch (setjmp(tb_env)) "
                "{ case 1: goto *tb_handler; case 2: goto *tb_xgoto; default:; }"
            )
        elif self.uses_eh:
            # tb_error longjmps here; the installed handler label takes over
            parts.append("    if (setjmp(tb_env)) goto *tb_handler;")
        parts.extend("    " + ln for ln in body)
        parts.append("    return 0;")
        parts.append("}")
        if self.uses_clear:
            clr = ["static void tb_clear_all(void) {", "    tb_reset();"]
            for m in sorted(self.vars):
                if "tb_str" in self.vars[m]:
                    clr.append(f"    free({m}.p); {m} = (tb_str){{0, 0}};")
                else:
                    clr.append(f"    {m} = 0;")
            for name, (ty, dims, rank) in sorted(self.arrays.items()):
                _, pre, _ = _VTYPES[ty]
                m = f"a{pre}{_base(name)}"
                if dims is not None:
                    clr.append(f"    memset({m}, 0, sizeof {m});")
                else:
                    clr.append(f"    free({m}); {m} = 0;")
                    clr.extend(
                        f"    {m}_lo{k} = 0; {m}_n{k} = 0;" for k in range(1, rank + 1)
                    )
            clr.append("}")
            parts.extend(clr)
        return "\n".join(parts) + "\n"


def emit_c(stmts, standalone: bool = True, sdl: bool = False) -> str:
    """Typed IR statements -> a C translation unit (gcc/clang).

    `standalone=True` (the default) embeds the runtime fragments so the
    output compiles alone with `cc out.c -lm`. `standalone=False` emits
    `#include "tb_runtime.h"` instead, for linking against the runtime
    built as a library (`make` in c0_runtime/ produces libtbrt.a).

    `sdl=True` turns on the SDL2 video backend (#define TB_SDL 1): graphics
    render into a real window instead of the PPM-at-exit surrogate. Build
    with `cc out.c -lm $(sdl2-config --cflags --libs)` (or, non-standalone,
    a `make SDL=1` runtime library).

    Raises ValueError for programs using constructs outside the implemented
    vocabulary -- fail-loud, like the decoder."""
    text = _Gen(stmts, standalone).build()
    return "#define TB_SDL 1\n" + text if sdl else text
