"""Experimental native-recompile back end: typed IR statements -> portable C.

Where emit0 targets the original Borland toolchain byte-for-byte, this back end
targets MODERN platforms: the generated translation unit is self-contained
(embedded runtime prelude, no external headers beyond libc/libm) and compiles
with gcc or clang on any modern OS (`cc out.c -lm`). GOSUB/RETURN use the
labels-as-values extension, so gcc/clang specifically, not MSVC.

Fidelity is behavioral, not byte-exact, and deliberately fail-loud in the
repo's style: an IR node, intrinsic, or type combination outside the
implemented vocabulary raises ValueError rather than mistranslating. The
implemented semantics follow the Turbo Basic handbook:

- unsuffixed and `!` variables are C `float` (TB singles), `%` is `short`
  with CINT banker's rounding on store, `#` is `double`, `$` is a heap
  C string (allocations are never freed -- recompiled programs are
  short-lived by assumption);
- \\ MOD AND OR XOR NOT operate on CINT-rounded 16-bit integers;
- PRINT reproduces the GW-BASIC family layout: sign-or-space before a
  number, trailing space after, `.5` without a leading zero, 7 significant
  digits (single precision), 14-column comma zones untouched (the decoder
  never produces comma items -- TAB/SPC arrive as Call items);
- FOR/WHILE/DO compile to explicit test/jump label pairs so EXIT FOR /
  EXIT LOOP and cross-statement GOTO keep working exactly as in the flat IR.

Unsupported (raises): file I/O, graphics/sound/events, error trapping,
PRINT USING, SUB/CALL and block DEF FN, RUN, CHAIN, machine access
(PEEK/POKE/OUT/CALL ABSOLUTE...), and any intrinsic not listed in
_NUM_FUNCS/_STR_FUNCS.
"""

from __future__ import annotations

from tbx import ir

_PRELUDE = r"""/* generated by tbx --emit-c : Turbo Basic recompiled to C */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <time.h>
#include <setjmp.h>
#include <unistd.h>
#include <fcntl.h>
#include <termios.h>
#include <dirent.h>
#include <fnmatch.h>
#include <poll.h>
#include <sys/stat.h>
#ifndef FNM_CASEFOLD
#define FNM_CASEFOLD 0
#endif

/* --- error trapping (ON ERROR GOTO / ERR / ERL / RESUME) --- */
static jmp_buf tb_env;
static void *tb_handler = 0;  /* installed handler label, 0 = none */
static void *tb_stmt = 0;     /* start of current statement (RESUME) */
static void *tb_next = 0;     /* following statement (RESUME NEXT) */
static int tb_err = 0, tb_erl = 0;
static void tb_error(int n) {
    tb_err = n;
    if (tb_handler) longjmp(tb_env, 1);
    fprintf(stderr, "\nError %d in line %d\n", n, tb_erl);
    exit(n);
}

static FILE *tb_out = 0;  /* current PRINT sink; stdout unless PRINT #n */
static int tb_ch = 0;     /* current PRINT channel: 0 = console, n = file #n */
static int tb_cols[16];   /* print column per channel (TAB/POS) */
static int tb_row = 0;    /* console cursor row (CSRLIN), LOCATE-aware */
#define tb_col tb_cols[tb_ch]
static void tb_ps(const char *s) {
    if (!tb_out) tb_out = stdout;
    for (; *s; s++) {
        fputc(*s, tb_out);
        if (*s == '\n') {
            tb_col = 0;
            if (tb_ch == 0) tb_row++;
        } else {
            tb_col++;
        }
    }
}
static void tb_nl(void) { tb_ps("\n"); }
static const char *tb_s(const char *s) { return s ? s : ""; }
/* --- clock offsets (DATE$/TIME$ assignment shifts a process-local clock) --- */
static double tb_clk_off = 0;
static time_t tb_now_wall(void) { return time(NULL) + (time_t)tb_clk_off; }
static struct tm *tb_now_tm(void) { time_t t = tb_now_wall(); return localtime(&t); }
static void tb_set_time(const char *s) {
    int h = 0, m = 0, sec = 0;
    sscanf(tb_s(s), "%d:%d:%d", &h, &m, &sec);
    struct tm *lt = tb_now_tm();
    tb_clk_off += (h * 3600 + m * 60 + sec)
        - (lt->tm_hour * 3600 + lt->tm_min * 60 + lt->tm_sec);
}
static void tb_set_date(const char *s) {
    int mo = 1, d = 1, y = 1980;
    sscanf(tb_s(s), "%d-%d-%d", &mo, &d, &y);
    struct tm want = *tb_now_tm();
    want.tm_mon = mo - 1; want.tm_mday = d; want.tm_year = y - 1900;
    tb_clk_off += difftime(mktime(&want), tb_now_wall());
}
/* GW-BASIC family number image: integral -> no point; else 7 significant
   digits (single precision) with the leading zero of "0.5" stripped. */
static void tb_fmt(double v, char *out) {
    if (v == floor(v) && fabs(v) < 1e15) { sprintf(out, "%.0f", v); return; }
    char b[48]; sprintf(b, "%.7G", v);
    char *p = b, *o = out;
    if (*p == '-') *o++ = *p++;
    if (p[0] == '0' && p[1] == '.') p++;
    strcpy(o, p);
}
static void tb_pn(double v) {
    char b[64]; tb_fmt(v, b);
    if (v >= 0) tb_ps(" ");
    tb_ps(b); tb_ps(" ");
}
static void tb_tab(double n) { while (tb_col < (int)n - 1) tb_ps(" "); }
static void tb_spc(double n) { for (int i = 0; i < (int)n; i++) tb_ps(" "); }
/* CINT: round half to even (the x87/IEEE default nearbyint mode). */
static double tb_cint(double v) { return nearbyint(v); }
static long tb_i(double v) { return (long)tb_cint(v); }
static double tb_div(double a, double b) { if (b == 0) tb_error(11); return a / b; }
static double tb_idiv(double a, double b) { if (tb_i(b) == 0) tb_error(11); return (double)(tb_i(a) / tb_i(b)); }
static double tb_mod(double a, double b) { if (tb_i(b) == 0) tb_error(11); return (double)(tb_i(a) % tb_i(b)); }
static double tb_and(double a, double b) { return (double)(short)(tb_i(a) & tb_i(b)); }
static double tb_or(double a, double b) { return (double)(short)(tb_i(a) | tb_i(b)); }
static double tb_xor(double a, double b) { return (double)(short)(tb_i(a) ^ tb_i(b)); }
static double tb_not(double a) { return (double)(short)~tb_i(a); }
static double tb_sgn(double v) { return v > 0 ? 1 : v < 0 ? -1 : 0; }
static double tb_timer(void) {
    struct tm *lt = tb_now_tm();
    return lt->tm_hour * 3600.0 + lt->tm_min * 60.0 + lt->tm_sec;
}
static void tb_delay(double secs) {
    struct timespec ts = { (time_t)secs, (long)((secs - (long)secs) * 1e9) };
    nanosleep(&ts, NULL);
}
static char *tb_alloc(size_t n) {
    char *p = malloc(n + 1);
    if (!p) { fputs("out of memory\n", stderr); exit(1); }
    p[n] = 0; return p;
}
static char *tb_dup(const char *s) { char *p = tb_alloc(strlen(s)); strcpy(p, s); return p; }
static char *tb_cat(const char *a, const char *b) {
    a = tb_s(a); b = tb_s(b);
    char *p = tb_alloc(strlen(a) + strlen(b));
    strcpy(p, a); strcat(p, b); return p;
}
static double tb_len(const char *s) { return (double)strlen(tb_s(s)); }
static double tb_asc(const char *s) { return (double)(unsigned char)tb_s(s)[0]; }
static double tb_val(const char *s) { return strtod(tb_s(s), NULL); }
static char *tb_chr(double c) { char *p = tb_alloc(1); p[0] = (char)tb_i(c); return p; }
static char *tb_strS(double v) {
    char b[64]; tb_fmt(v, b);
    char *p = tb_alloc(strlen(b) + 1);
    if (v >= 0) { p[0] = ' '; strcpy(p + 1, b); } else strcpy(p, b);
    return p;
}
static char *tb_space(double n) {
    long k = tb_i(n) < 0 ? 0 : tb_i(n);
    char *p = tb_alloc(k); memset(p, ' ', k); return p;
}
static char *tb_stringS(double n, double c) {
    long k = tb_i(n) < 0 ? 0 : tb_i(n);
    char *p = tb_alloc(k); memset(p, (char)tb_i(c), k); return p;
}
static char *tb_left(const char *s, double n) {
    s = tb_s(s); size_t L = strlen(s), k = tb_i(n) < 0 ? 0 : (size_t)tb_i(n);
    if (k > L) k = L;
    char *p = tb_alloc(k); memcpy(p, s, k); return p;
}
static char *tb_right(const char *s, double n) {
    s = tb_s(s); size_t L = strlen(s), k = tb_i(n) < 0 ? 0 : (size_t)tb_i(n);
    if (k > L) k = L;
    return tb_dup(s + (L - k));
}
static char *tb_mid(const char *s, double start, double len) {
    s = tb_s(s); size_t L = strlen(s);
    long st = tb_i(start); if (st < 1) st = 1;
    if ((size_t)st > L) return tb_dup("");
    size_t avail = L - (st - 1), k = len < 0 ? avail : (size_t)tb_i(len);
    if (k > avail) k = avail;
    char *p = tb_alloc(k); memcpy(p, s + st - 1, k); return p;
}
static double tb_instr(double start, const char *a, const char *b) {
    a = tb_s(a); b = tb_s(b);
    long st = tb_i(start); if (st < 1) st = 1;
    if ((size_t)st > strlen(a)) return 0;
    const char *hit = strstr(a + st - 1, b);
    return hit ? (double)(hit - a + 1) : 0;
}
static char *tb_ucase(const char *s) {
    char *p = tb_dup(tb_s(s));
    for (char *q = p; *q; q++) if (*q >= 'a' && *q <= 'z') *q -= 32;
    return p;
}
static char *tb_lcase(const char *s) {
    char *p = tb_dup(tb_s(s));
    for (char *q = p; *q; q++) if (*q >= 'A' && *q <= 'Z') *q += 32;
    return p;
}
static char *tb_ltrim(const char *s) { s = tb_s(s); while (*s == ' ') s++; return tb_dup(s); }
static char *tb_rtrim(const char *s) {
    char *p = tb_dup(tb_s(s));
    for (size_t L = strlen(p); L && p[L - 1] == ' '; L--) p[L - 1] = 0;
    return p;
}
static char *tb_hex(double v) { char b[24]; sprintf(b, "%lX", tb_i(v) & 0xFFFF); return tb_dup(b); }
static char *tb_oct(double v) { char b[24]; sprintf(b, "%lo", tb_i(v) & 0xFFFF); return tb_dup(b); }
static double tb_input_num(const char *prompt, int mark) {
    if (prompt) tb_ps(prompt);
    if (mark) tb_ps("? ");
    char line[256];
    if (!fgets(line, sizeof line, stdin)) return 0;
    tb_col = 0;
    return strtod(line, NULL);
}
static char *tb_input_str(const char *prompt, int mark) {
    if (prompt) tb_ps(prompt);
    if (mark) tb_ps("? ");
    char line[256];
    if (!fgets(line, sizeof line, stdin)) return tb_dup("");
    tb_col = 0;
    line[strcspn(line, "\r\n")] = 0;
    return tb_dup(line);
}
static char *tb_dateS(void) {
    struct tm *lt = tb_now_tm(); char b[40];
    sprintf(b, "%02d-%02d-%04d", lt->tm_mon + 1, lt->tm_mday, lt->tm_year + 1900);
    return tb_dup(b);
}
static char *tb_timeS(void) {
    struct tm *lt = tb_now_tm(); char b[16];
    sprintf(b, "%02d:%02d:%02d", lt->tm_hour, lt->tm_min, lt->tm_sec);
    return tb_dup(b);
}
static void *tb_calloc(long n, size_t w) {
    void *p = calloc(n > 0 ? n : 1, w);
    if (!p) { fputs("out of memory\n", stderr); exit(1); }
    return p;
}
/* --- sequential file I/O --- */
static FILE *tb_files[16];
static FILE *tb_file(int n) {
    if (n < 1 || n > 15 || !tb_files[n]) tb_error(52);  /* bad file number */
    return tb_files[n];
}
static void tb_open(const char *mode, int n, const char *name) {
    if (n < 1 || n > 15) tb_error(52);
    if (tb_files[n]) tb_error(55);                       /* file already open */
    FILE *f = fopen(tb_s(name), mode);
    if (!f) tb_error(53);                                /* file not found */
    tb_files[n] = f;
}
/* random access: fixed 128-byte records (the calibrated OPEN reclen),
   FIELD vars snapshot the record buffer on GET and write into it on LSET/RSET */
static char *tb_recbuf[16];
static long tb_reclen[16], tb_fieldoff[16];
typedef struct { int file; char **var; long off, w; } tb_fielddef;
static tb_fielddef tb_fields[128];
static int tb_nfields = 0;
static void tb_drop_fields(int n) {
    int k = 0;
    for (int i = 0; i < tb_nfields; i++)
        if (tb_fields[i].file != n) tb_fields[k++] = tb_fields[i];
    tb_nfields = k;
}
static void tb_close(int n) {
    if (n >= 1 && n <= 15 && tb_files[n]) {
        fclose(tb_files[n]); tb_files[n] = 0;
        free(tb_recbuf[n]); tb_recbuf[n] = 0;
        tb_drop_fields(n);
    }
}
static void tb_reset(void) { for (int i = 1; i < 16; i++) tb_close(i); }
static void tb_open_r(int n, const char *name) {
    if (n < 1 || n > 15) tb_error(52);
    if (tb_files[n]) tb_error(55);
    FILE *f = fopen(tb_s(name), "r+b");
    if (!f) f = fopen(tb_s(name), "w+b");
    if (!f) tb_error(53);
    tb_files[n] = f;
    tb_reclen[n] = 128;
    tb_recbuf[n] = tb_alloc(128);
    memset(tb_recbuf[n], ' ', 128);
}
static double tb_eof(double n) {
    FILE *f = ((int)n >= 1 && (int)n <= 15) ? tb_files[(int)n] : 0;
    if (!f) return -1;
    int c = fgetc(f);
    if (c == EOF) return -1;
    ungetc(c, f);
    return 0;
}
static double tb_finput_num(int n) {
    FILE *f = tb_file(n); double v = 0;
    if (fscanf(f, " %lf", &v) != 1) tb_error(62);        /* input past end */
    int c = fgetc(f);
    if (c != ',' && c != EOF && c != '\n') ungetc(c, f);
    return v;
}
static char *tb_finput_str(int n) {
    FILE *f = tb_file(n); int c;
    while ((c = fgetc(f)) == ' ') ;
    if (c == EOF) tb_error(62);
    char buf[256]; size_t k = 0;
    if (c == '"') {
        while ((c = fgetc(f)) != EOF && c != '"') if (k < 255) buf[k++] = (char)c;
        c = fgetc(f);                                    /* separator after quote */
    } else {
        while (c != EOF && c != ',' && c != '\n') {
            if (c != '\r' && k < 255) buf[k++] = (char)c;
            c = fgetc(f);
        }
    }
    if (c != ',' && c != EOF && c != '\n') ungetc(c, f);
    buf[k] = 0;
    return tb_dup(buf);
}
static void tb_field_start(int n) {
    tb_file(n);
    tb_fieldoff[n] = 0;
    tb_drop_fields(n);
}
static void tb_field_reg(int n, char **var, long w) {
    if (tb_nfields >= 128 || !tb_recbuf[n] || tb_fieldoff[n] + w > tb_reclen[n])
        tb_error(50);                                    /* field overflow */
    tb_fields[tb_nfields++] = (tb_fielddef){n, var, tb_fieldoff[n], w};
    tb_fieldoff[n] += w;
    *var = tb_space(w);
}
static void tb_lsetrset(char **var, const char *src, int right) {
    src = tb_s(src);
    tb_fielddef *fd = 0;
    for (int i = 0; i < tb_nfields; i++)
        if (tb_fields[i].var == var) { fd = &tb_fields[i]; break; }
    long w = fd ? fd->w : (long)strlen(tb_s(*var));
    long L = (long)strlen(src);
    if (L > w) L = w;
    char *out = tb_alloc(w);
    memset(out, ' ', w);
    memcpy(right ? out + (w - L) : out, src, L);
    if (fd) memcpy(tb_recbuf[fd->file] + fd->off, out, w);
    *var = out;
}
static void tb_getrec(int n, double rec) {
    FILE *f = tb_file(n);
    if (!tb_recbuf[n]) tb_error(52);
    fseek(f, (long)(tb_i(rec) - 1) * tb_reclen[n], SEEK_SET);
    memset(tb_recbuf[n], 0, (size_t)tb_reclen[n]);
    if (fread(tb_recbuf[n], 1, (size_t)tb_reclen[n], f)) {}
    for (int i = 0; i < tb_nfields; i++)
        if (tb_fields[i].file == n) {
            char *v = tb_alloc(tb_fields[i].w);
            memcpy(v, tb_recbuf[n] + tb_fields[i].off, tb_fields[i].w);
            *tb_fields[i].var = v;
        }
}
static void tb_putrec(int n, double rec) {
    FILE *f = tb_file(n);
    if (!tb_recbuf[n]) tb_error(52);
    fseek(f, (long)(tb_i(rec) - 1) * tb_reclen[n], SEEK_SET);
    fwrite(tb_recbuf[n], 1, (size_t)tb_reclen[n], f);
    fflush(f);
}
/* WRITE layout: comma separators, quoted strings, numbers without padding */
static void tb_wnum(double v) { char b[64]; tb_fmt(v, b); tb_ps(b); }
static void tb_wstr(const char *s) { tb_ps("\""); tb_ps(tb_s(s)); tb_ps("\""); }
/* PRINT USING: the # / . / + numeric-field subset; other format characters
   raise error 5 rather than misformat */
static const char *tb_puf = "";
static size_t tb_pup = 0;
static void tb_pu_begin(const char *f) { tb_puf = tb_s(f); tb_pup = 0; }
static void tb_pu_val(double v) {
    const char *f = tb_puf;
    size_t L = strlen(f);
    int guard = 0;
    if (!L) tb_error(5);
    for (;; tb_pup++) {                                  /* literals up to the field */
        if (tb_pup >= L) { tb_pup = 0; if (guard++) tb_error(5); }
        char c = f[tb_pup];
        if (c == '#' || (c == '+' && tb_pup + 1 < L && f[tb_pup + 1] == '#')) break;
        if (strchr("^!\\&_$*", c)) tb_error(5);
        char b[2] = {c, 0}; tb_ps(b);
    }
    int plus = f[tb_pup] == '+';
    if (plus) tb_pup++;
    int iw = 0, dw = -1;
    while (tb_pup < L && f[tb_pup] == '#') { iw++; tb_pup++; }
    if (tb_pup < L && f[tb_pup] == '.') {
        tb_pup++; dw = 0;
        while (tb_pup < L && f[tb_pup] == '#') { dw++; tb_pup++; }
    }
    char num[80];
    snprintf(num, 64, "%.*f", dw < 0 ? 0 : dw, v);
    if (dw == 0) strcat(num, ".");
    if (plus && v >= 0) { memmove(num + 1, num, strlen(num) + 1); num[0] = '+'; }
    int width = iw + (dw >= 0 ? 1 + dw : 0) + (plus ? 1 : 0);
    int pad = width - (int)strlen(num);
    if (pad < 0) tb_ps("%");                             /* field overflow, GW-style */
    for (; pad > 0; pad--) tb_ps(" ");
    tb_ps(num);
}
/* MKx$/CVx: raw little-endian bytes in a string. Caveat of the C string
   model: interior zero bytes truncate, so round trips through string ops
   are only exact when the encoded bytes avoid embedded NULs. */
static char *tb_mkbytes(const void *p, size_t n) {
    char *s = tb_alloc(n); memcpy(s, p, n); return s;
}
static void tb_cvbytes(const char *s, void *out, size_t n) {
    s = tb_s(s);
    size_t L = strlen(s);
    if (L > n) L = n;
    memset(out, 0, n); memcpy(out, s, L);
}
static char *tb_mki(double v) { short x = (short)tb_i(v); return tb_mkbytes(&x, 2); }
static char *tb_mkl(double v) { int x = (int)tb_i(v); return tb_mkbytes(&x, 4); }
static char *tb_mks(double v) { float x = (float)v; return tb_mkbytes(&x, 4); }
static char *tb_mkd(double v) { return tb_mkbytes(&v, 8); }
static double tb_cvi(const char *s) { short x; tb_cvbytes(s, &x, 2); return x; }
static double tb_cvl(const char *s) { int x; tb_cvbytes(s, &x, 4); return x; }
static double tb_cvs(const char *s) { float x; tb_cvbytes(s, &x, 4); return x; }
static double tb_cvd(const char *s) { double x; tb_cvbytes(s, &x, 8); return x; }
static double tb_rnd(void) { return rand() / ((double)RAND_MAX + 1); }
static double tb_instat(void) {
    struct pollfd p = {0, POLLIN, 0};
    return poll(&p, 1, 0) > 0 ? -1 : 0;
}
/* --- terminal control (ANSI mapping of the CGA text interface) --- */
/* ANSI escapes bypass tb_ps so they don't disturb column tracking */
static void tb_esc(const char *s) { fputs(s, stdout); }
static void tb_locate(double r, double c) {
    char b[32]; sprintf(b, "\033[%d;%dH", (int)r, (int)c);
    tb_esc(b); tb_cols[0] = (int)c - 1; tb_row = (int)r - 1;
}
static const int tb_cga[8] = {0, 4, 2, 6, 1, 5, 3, 7};  /* CGA -> ANSI hue */
static int tb_fg = 3;                                    /* graphics foreground */
static void tb_color(int has_fg, double fg, int has_bg, double bg) {
    char b[24];
    if (has_fg) {
        int f = (int)fg & 15;
        sprintf(b, "\033[%s3%dm", f > 7 ? "1;" : "22;", tb_cga[f & 7]);
        tb_esc(b); tb_fg = f;
    }
    if (has_bg) { sprintf(b, "\033[4%dm", tb_cga[(int)bg & 7]); tb_esc(b); }
}
static char *tb_inkey(void) {
    int fl = fcntl(0, F_GETFL);
    struct termios old, raw;
    int tty = isatty(0);
    if (tty) {
        tcgetattr(0, &old); raw = old;
        raw.c_lflag &= ~(unsigned)(ICANON | ECHO);
        tcsetattr(0, TCSANOW, &raw);
    }
    fcntl(0, F_SETFL, fl | O_NONBLOCK);
    char ch; long n = read(0, &ch, 1);
    fcntl(0, F_SETFL, fl);
    if (tty) tcsetattr(0, TCSANOW, &old);
    if (n != 1) return tb_dup("");
    char b[2] = {ch, 0};
    return tb_dup(b);
}
static void tb_files_(const char *spec) {
    const char *pat = tb_s(spec);
    if (!*pat || !strcmp(pat, "*.*")) pat = "*";
    DIR *d = opendir(".");
    if (!d) tb_error(76);                                /* path not found */
    struct dirent *e;
    while ((e = readdir(d))) {
        if (e->d_name[0] == '.') continue;
        if (fnmatch(pat, e->d_name, FNM_CASEFOLD)) continue;
        tb_ps(e->d_name); tb_nl();
    }
    closedir(d);
}
static char *tb_bin(double v) {
    char b[20]; int k = 19; b[k] = 0;
    unsigned x = (unsigned)tb_i(v) & 0xFFFF;
    do { b[--k] = (char)('0' + (x & 1)); x >>= 1; } while (x);
    return tb_dup(b + k);
}
/* --- graphics: in-memory framebuffer with CGA/EGA geometry ---
   There is no screen on a headless modern host, so SCREEN n allocates a
   byte-per-pixel framebuffer instead; a first graphics call without SCREEN
   enters mode 1 (320x200) implicitly. Set TB_SCREEN_PPM=file.ppm to dump
   the final image (CGA palette) at exit. */
static int tb_gw = 0, tb_gh = 0, tb_maxattr = 3;
static unsigned char *tb_fb = 0;
static double tb_lastx = 0, tb_lasty = 0;                /* STEP reference */
static int tb_vx1, tb_vy1, tb_vx2, tb_vy2, tb_vabs = 0;  /* viewport */
static int tb_wset = 0, tb_wabs = 0;
static double tb_wx1, tb_wy1, tb_wx2, tb_wy2;            /* WINDOW rect */
static int tb_pal[16] = {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15};
static void tb_ppm_dump(void) {
    const char *path = getenv("TB_SCREEN_PPM");
    if (!path || !tb_fb) return;
    static const unsigned char pal[16][3] = {
        {0,0,0},{0,0,170},{0,170,0},{0,170,170},{170,0,0},{170,0,170},
        {170,85,0},{170,170,170},{85,85,85},{85,85,255},{85,255,85},
        {85,255,255},{255,85,85},{255,85,255},{255,255,85},{255,255,255}};
    FILE *f = fopen(path, "wb");
    if (!f) return;
    fprintf(f, "P6\n%d %d\n255\n", tb_gw, tb_gh);
    for (long i = 0; i < (long)tb_gw * tb_gh; i++)
        fwrite(pal[tb_pal[tb_fb[i] & 15] & 15], 1, 3, f);
    fclose(f);
}
static void tb_screen(double mode) {
    static const struct { int m, w, h, a; } md[] = {
        {1,320,200,3},{2,640,200,1},{7,320,200,15},{8,640,200,15},
        {9,640,350,15},{10,640,350,3}};
    int m = (int)mode;
    if (m == 0) { free(tb_fb); tb_fb = 0; tb_gw = tb_gh = 0; return; }
    for (unsigned i = 0; i < sizeof md / sizeof *md; i++)
        if (md[i].m == m) {
            tb_gw = md[i].w; tb_gh = md[i].h;
            tb_maxattr = md[i].a; tb_fg = md[i].a;
            free(tb_fb);
            tb_fb = tb_calloc((long)tb_gw * tb_gh, 1);
            tb_vx1 = tb_vy1 = 0; tb_vx2 = tb_gw - 1; tb_vy2 = tb_gh - 1;
            tb_vabs = tb_wset = 0; tb_lastx = tb_lasty = 0;
            static int reg = 0;
            if (!reg) { reg = 1; atexit(tb_ppm_dump); }
            return;
        }
    tb_error(5);                                         /* illegal function call */
}
static void tb_gfx(void) { if (!tb_fb) tb_screen(1); }
static void tb_map(double x, double y, long *px, long *py) {
    if (tb_wset) {
        x = tb_vx1 + (x - tb_wx1) * (tb_vx2 - tb_vx1) / (tb_wx2 - tb_wx1);
        y = tb_wabs
            ? tb_vy1 + (y - tb_wy1) * (tb_vy2 - tb_vy1) / (tb_wy2 - tb_wy1)
            : tb_vy1 + (tb_wy2 - y) * (tb_vy2 - tb_vy1) / (tb_wy2 - tb_wy1);
    } else if (!tb_vabs) { x += tb_vx1; y += tb_vy1; }
    *px = lround(x); *py = lround(y);
}
static void tb_px(long x, long y, int c) {
    if (!tb_fb || x < tb_vx1 || x > tb_vx2 || y < tb_vy1 || y > tb_vy2) return;
    tb_fb[y * tb_gw + x] = (unsigned char)(c & 15);
}
static double tb_pointf(double x, double y) {
    long px, py;
    tb_gfx(); tb_map(x, y, &px, &py);
    if (px < 0 || px >= tb_gw || py < 0 || py >= tb_gh) return -1;
    return tb_fb[py * tb_gw + px];
}
static void tb_step(double *x, double *y, int step) {
    if (step) { *x += tb_lastx; *y += tb_lasty; }
}
static void tb_pset(double x, double y, int step, int has_c, double c, int preset) {
    long px, py;
    tb_gfx(); tb_step(&x, &y, step);
    tb_map(x, y, &px, &py);
    tb_px(px, py, has_c ? (int)c : preset ? 0 : tb_fg);
    tb_lastx = x; tb_lasty = y;
}
static void tb_line_px(long x1, long y1, long x2, long y2, int c, unsigned style) {
    long dx = labs(x2 - x1), sx = x1 < x2 ? 1 : -1;
    long dy = -labs(y2 - y1), sy = y1 < y2 ? 1 : -1, err = dx + dy;
    unsigned bit = 0x8000;
    for (;;) {
        if (style & bit) tb_px(x1, y1, c);
        bit = bit >> 1 ? bit >> 1 : 0x8000;
        if (x1 == x2 && y1 == y2) break;
        long e2 = 2 * err;
        if (e2 >= dy) { err += dy; x1 += sx; }
        if (e2 <= dx) { err += dx; y1 += sy; }
    }
}
static void tb_linestmt(double x1, double y1, int s1, double x2, double y2, int s2,
                        int has_c, double c, int box, int fill, unsigned style) {
    long px1, py1, px2, py2;
    tb_gfx();
    tb_step(&x1, &y1, s1);
    tb_lastx = x1; tb_lasty = y1;                        /* second STEP chains */
    tb_step(&x2, &y2, s2);
    tb_map(x1, y1, &px1, &py1); tb_map(x2, y2, &px2, &py2);
    int col = has_c ? (int)c : tb_fg;
    if (fill) {
        if (py1 > py2) { long t = py1; py1 = py2; py2 = t; }
        for (long y = py1; y <= py2; y++) tb_line_px(px1, y, px2, y, col, style);
    } else if (box) {
        tb_line_px(px1, py1, px2, py1, col, style);
        tb_line_px(px2, py1, px2, py2, col, style);
        tb_line_px(px2, py2, px1, py2, col, style);
        tb_line_px(px1, py2, px1, py1, col, style);
    } else {
        tb_line_px(px1, py1, px2, py2, col, style);
    }
    tb_lastx = x2; tb_lasty = y2;
}
static void tb_circle(double x, double y, double r, int step, int has_c, double c,
                      double sa, double ea, double aspect) {
    long cx, cy;
    tb_gfx(); tb_step(&x, &y, step);
    tb_map(x, y, &cx, &cy);
    int col = has_c ? (int)c : tb_fg;
    double rx = r, ry = r;
    if (aspect <= 0) aspect = (4.0 / 3.0) * tb_gh / tb_gw;
    if (aspect < 1) ry = r * aspect; else rx = r / aspect;
    int line_s = sa < 0, line_e = ea < 0;
    sa = fabs(sa); ea = fabs(ea);
    if (ea <= sa && !(sa == 0 && ea == 0)) ea += 6.283185307179586;
    if (sa == 0 && ea == 0) ea = 6.283185307179586;
    double dt = 1.0 / (rx > ry ? rx : ry);
    if (dt > 0.05) dt = 0.05;
    for (double t = sa; t <= ea; t += dt)
        tb_px(lround(cx + rx * cos(t)), lround(cy - ry * sin(t)), col);
    if (line_s) tb_line_px(cx, cy, lround(cx + rx * cos(sa)), lround(cy - ry * sin(sa)), col, 0xFFFF);
    if (line_e) tb_line_px(cx, cy, lround(cx + rx * cos(ea)), lround(cy - ry * sin(ea)), col, 0xFFFF);
    tb_lastx = x; tb_lasty = y;
}
static void tb_paint(double x, double y, int has_p, double p, int has_b, double b) {
    long sx, sy;
    tb_gfx(); tb_map(x, y, &sx, &sy);
    int paint = has_p ? (int)p : tb_fg, border = has_b ? (int)b : paint;
    if (sx < 0 || sx >= tb_gw || sy < 0 || sy >= tb_gh) return;
    long cap = (long)tb_gw * tb_gh, n = 0;
    long *stack = tb_calloc(cap, sizeof(long));
    stack[n++] = sy * tb_gw + sx;
    while (n) {
        long i = stack[--n], px = i % tb_gw, py = i / tb_gw;
        if (px < tb_vx1 || px > tb_vx2 || py < tb_vy1 || py > tb_vy2) continue;
        if (tb_fb[i] == border || tb_fb[i] == paint) continue;
        tb_fb[i] = (unsigned char)paint;
        if (n + 4 <= cap) {
            if (px > 0) stack[n++] = i - 1;
            if (px < tb_gw - 1) stack[n++] = i + 1;
            if (py > 0) stack[n++] = i - tb_gw;
            if (py < tb_gh - 1) stack[n++] = i + tb_gw;
        }
    }
    free(stack);
}
/* GET/PUT blit: internal layout [long w][long h][one byte per pixel] laid
   into the array's storage, clipped to its capacity in bytes */
static void tb_getgfx(void *buf, long cap, double x1, double y1, double x2, double y2) {
    long px1, py1, px2, py2;
    tb_gfx(); tb_map(x1, y1, &px1, &py1); tb_map(x2, y2, &px2, &py2);
    if (px1 > px2) { long t = px1; px1 = px2; px2 = t; }
    if (py1 > py2) { long t = py1; py1 = py2; py2 = t; }
    long w = px2 - px1 + 1, h = py2 - py1 + 1;
    unsigned char *p = buf;
    if (cap < (long)(2 * sizeof(long))) tb_error(5);
    memcpy(p, &w, sizeof w); memcpy(p + sizeof w, &h, sizeof h);
    p += 2 * sizeof(long); cap -= 2 * sizeof(long);
    for (long y = 0; y < h; y++)
        for (long x = 0; x < w; x++) {
            if (cap-- <= 0) return;
            long fx = px1 + x, fy = py1 + y;
            *p++ = (fx >= 0 && fx < tb_gw && fy >= 0 && fy < tb_gh)
                       ? tb_fb[fy * tb_gw + fx] : 0;
        }
}
static void tb_putgfx(void *buf, long cap, double x, double y, int pset_action) {
    long px, py, w, h;
    tb_gfx(); tb_map(x, y, &px, &py);
    unsigned char *p = buf;
    if (cap < (long)(2 * sizeof(long))) tb_error(5);
    memcpy(&w, p, sizeof w); memcpy(&h, p + sizeof w, sizeof h);
    p += 2 * sizeof(long); cap -= 2 * sizeof(long);
    for (long dy = 0; dy < h; dy++)
        for (long dx = 0; dx < w; dx++) {
            if (cap-- <= 0) return;
            unsigned char v = *p++;
            long fx = px + dx, fy = py + dy;
            if (fx < 0 || fx >= tb_gw || fy < 0 || fy >= tb_gh) continue;
            unsigned char *dst = &tb_fb[fy * tb_gw + fx];
            /* action: 0=XOR (default), 1=PSET, 2=PRESET (complement), 3=AND, 4=OR */
            *dst = pset_action == 1 ? v
                 : pset_action == 2 ? (unsigned char)(~v & tb_maxattr)
                 : pset_action == 3 ? (unsigned char)(*dst & v)
                 : pset_action == 4 ? (unsigned char)(*dst | v)
                 : (unsigned char)((*dst ^ v) & 15);
        }
}
static void tb_view(int has_rect, double x1, double y1, double x2, double y2,
                    int absolute, int has_c, double c, int has_b, double b) {
    tb_gfx();
    if (!has_rect) {
        tb_vx1 = tb_vy1 = 0; tb_vx2 = tb_gw - 1; tb_vy2 = tb_gh - 1;
        tb_vabs = 0; return;
    }
    tb_vx1 = lround(x1); tb_vy1 = lround(y1);
    tb_vx2 = lround(x2); tb_vy2 = lround(y2);
    tb_vabs = absolute;
    if (has_c)
        for (long yy = tb_vy1; yy <= tb_vy2; yy++)
            for (long xx = tb_vx1; xx <= tb_vx2; xx++)
                if (xx >= 0 && xx < tb_gw && yy >= 0 && yy < tb_gh)
                    tb_fb[yy * tb_gw + xx] = (unsigned char)((int)c & 15);
    if (has_b) {
        int ox1 = tb_vx1, oy1 = tb_vy1, ox2 = tb_vx2, oy2 = tb_vy2;
        tb_vx1 = 0; tb_vy1 = 0; tb_vx2 = tb_gw - 1; tb_vy2 = tb_gh - 1;
        tb_line_px(ox1 - 1, oy1 - 1, ox2 + 1, oy1 - 1, (int)b, 0xFFFF);
        tb_line_px(ox2 + 1, oy1 - 1, ox2 + 1, oy2 + 1, (int)b, 0xFFFF);
        tb_line_px(ox2 + 1, oy2 + 1, ox1 - 1, oy2 + 1, (int)b, 0xFFFF);
        tb_line_px(ox1 - 1, oy2 + 1, ox1 - 1, oy1 - 1, (int)b, 0xFFFF);
        tb_vx1 = ox1; tb_vy1 = oy1; tb_vx2 = ox2; tb_vy2 = oy2;
    }
}
static void tb_window(int has_rect, double x1, double y1, double x2, double y2, int absolute) {
    tb_gfx();
    if (!has_rect) { tb_wset = 0; return; }
    tb_wset = 1; tb_wabs = absolute;
    tb_wx1 = x1; tb_wy1 = y1; tb_wx2 = x2; tb_wy2 = y2;
}
static void tb_draw(const char *cmd) {
    tb_gfx();
    const char *p = tb_s(cmd);
    double scale = 1;
    while (*p) {
        char op = *p >= 'a' && *p <= 'z' ? (char)(*p - 32) : *p;
        p++;
        if (op == ' ' || op == ';') continue;
        int blank = 0, back = 0;
        while (op == 'B' || op == 'N') {
            if (op == 'B') blank = 1; else back = 1;
            op = *p >= 'a' && *p <= 'z' ? (char)(*p - 32) : *p;
            if (!op) return;
            p++;
        }
        int rel = *p == '+' || *p == '-';
        long a = 0; int got = 0, neg = *p == '-';
        if (rel) p++;
        while (*p >= '0' && *p <= '9') { a = a * 10 + (*p++ - '0'); got = 1; }
        if (neg) a = -a;
        double n = (got ? a : 1) * scale;
        double dx = 0, dy = 0;
        switch (op) {
        case 'U': dy = -n; break;
        case 'D': dy = n; break;
        case 'L': dx = -n; break;
        case 'R': dx = n; break;
        case 'E': dx = n; dy = -n; break;
        case 'F': dx = n; dy = n; break;
        case 'G': dx = -n; dy = n; break;
        case 'H': dx = -n; dy = -n; break;
        case 'C': tb_fg = (int)a & 15; continue;
        case 'S': scale = a / 4.0; continue;
        case 'M': {
            /* M[+|-]x,y -- a signed x makes the whole move relative */
            if (*p == ',') p++;
            long b = 0; int neg2 = *p == '-';
            if (*p == '+' || *p == '-') p++;
            while (*p >= '0' && *p <= '9') b = b * 10 + (*p++ - '0');
            if (neg2) b = -b;
            if (rel) { dx = a; dy = b; }
            else { dx = a - tb_lastx; dy = b - tb_lasty; }
            break;
        }
        default: tb_error(5);
        }
        double nx = tb_lastx + dx, ny = tb_lasty + dy;
        if (!blank) {
            long ax, ay, bx, by;
            tb_map(tb_lastx, tb_lasty, &ax, &ay); tb_map(nx, ny, &bx, &by);
            tb_line_px(ax, ay, bx, by, tb_fg, 0xFFFF);
        }
        if (!back) { tb_lastx = nx; tb_lasty = ny; }
    }
}
static double tb_pmap(double v, double n) {
    long px, py;
    tb_gfx();
    switch ((int)n) {
    case 0: tb_map(v, 0, &px, &py); return (double)px;
    case 1: tb_map(0, v, &px, &py); return (double)py;
    case 2:
        if (!tb_wset) return v - (tb_vabs ? 0 : tb_vx1);
        return tb_wx1 + (v - tb_vx1) * (tb_wx2 - tb_wx1) / (tb_vx2 - tb_vx1);
    case 3:
        if (!tb_wset) return v - (tb_vabs ? 0 : tb_vy1);
        return tb_wabs
            ? tb_wy1 + (v - tb_vy1) * (tb_wy2 - tb_wy1) / (tb_vy2 - tb_vy1)
            : tb_wy2 - (v - tb_vy1) * (tb_wy2 - tb_wy1) / (tb_vy2 - tb_vy1);
    }
    tb_error(5);
    return 0;
}
/* --- ON TIMER trapping (polled at statement boundaries, like TB) --- */
static double tb_mono(void) {
    struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec + ts.tv_nsec / 1e9;
}
static double tb_mt0 = 0;  /* MTIMER epoch */
static double tb_mtread(void) { return (tb_mono() - tb_mt0) * 1e6; }
static void *tb_timer_hdl = 0;
static double tb_timer_iv = 0, tb_timer_due_at = 0;
static int tb_timer_on = 0;
static int tb_timer_due(void) {
    if (!tb_timer_on || !tb_timer_hdl || tb_mono() < tb_timer_due_at) return 0;
    tb_timer_due_at = tb_mono() + tb_timer_iv;
    return 1;
}
static void *tb_gstack[256];
static int tb_gsp = 0;
"""

# name -> (c_call, arity); {0}... are the rendered numeric/string args in order.
_NUM_FUNCS = {
    ("SQR", 1): "sqrt({0})",
    ("ABS", 1): "fabs({0})",
    ("SIN", 1): "sin({0})",
    ("COS", 1): "cos({0})",
    ("TAN", 1): "tan({0})",
    ("ATN", 1): "atan({0})",
    ("EXP", 1): "exp({0})",
    ("LOG", 1): "log({0})",
    ("LOG2", 1): "log2({0})",
    ("LOG10", 1): "log10({0})",
    ("INT", 1): "floor({0})",
    ("FIX", 1): "trunc({0})",
    ("SGN", 1): "tb_sgn({0})",
    ("CINT", 1): "tb_cint({0})",
    ("CSNG", 1): "(double)(float)({0})",
    ("CDBL", 1): "({0})",
    ("LEN", 1): "tb_len({0})",
    ("ASC", 1): "tb_asc({0})",
    ("VAL", 1): "tb_val({0})",
    ("INSTR", 2): "tb_instr(1, {0}, {1})",
    ("INSTR", 3): "tb_instr({0}, {1}, {2})",
    ("CEIL", 1): "ceil({0})",
    ("CLNG", 1): "tb_cint({0})",
    ("CVI", 1): "tb_cvi({0})",
    ("CVL", 1): "tb_cvl({0})",
    ("CVS", 1): "tb_cvs({0})",
    ("CVD", 1): "tb_cvd({0})",
    ("RND", 1): "tb_rnd()",
    ("PMAP", 2): "tb_pmap({0}, {1})",
    # SCREEN(row,col) reads a text cell; there is no text buffer on this
    # host, so every cell reads as a blank
    ("SCREEN", 2): "32.0",
    # joystick / light pen / music queue: devices absent on a modern host
    ("STICK", 1): "0.0",
    ("STRIG", 1): "0.0",
    ("PEN", 1): "0.0",
    ("PLAY", 1): "0.0",
    # VARPTR: a DGROUP offset with no modern counterpart
    ("VARPTR", 1): "0.0",
    ("POS", 1): "(double)(tb_cols[0] + 1)",
    ("POINT", 2): "tb_pointf({0}, {1})",
    ("EOF", 1): "tb_eof({0})",
    # printer head position: nothing has ever been printed on a modern host
    ("LPOS", 1): "1.0",
    # free memory: meaningless on a modern host; a fixed roomy answer keeps
    # low-memory guard code on its happy path
    ("FRE", 1): "65536.0",
}
_STR_FUNCS = {
    ("CHR$", 1): "tb_chr({0})",
    ("STR$", 1): "tb_strS({0})",
    ("SPACE$", 1): "tb_space({0})",
    ("STRING$", 2): "tb_stringS({0}, {1})",
    ("LEFT$", 2): "tb_left({0}, {1})",
    ("RIGHT$", 2): "tb_right({0}, {1})",
    ("MID$", 2): "tb_mid({0}, {1}, -1)",
    ("MID$", 3): "tb_mid({0}, {1}, {2})",
    ("MKI$", 1): "tb_mki({0})",
    ("MKL$", 1): "tb_mkl({0})",
    ("MKS$", 1): "tb_mks({0})",
    ("MKD$", 1): "tb_mkd({0})",
    ("UCASE$", 1): "tb_ucase({0})",
    ("LCASE$", 1): "tb_lcase({0})",
    ("LTRIM$", 1): "tb_ltrim({0})",
    ("RTRIM$", 1): "tb_rtrim({0})",
    ("HEX$", 1): "tb_hex({0})",
    ("OCT$", 1): "tb_oct({0})",
    ("BIN$", 1): "tb_bin({0})",
}
_NULLARY = {
    "TIMER": "tb_timer()",
    "CSRLIN": "(double)(tb_row + 1)",
    "RND": "tb_rnd()",
    "INSTAT": "tb_instat()",
    "MTIMER": "tb_mtread()",
    # error address: a DOS code offset with no modern counterpart
    "ERADR": "0.0",
}
_NULLARY_STR = {"DATE$": "tb_dateS()", "TIME$": "tb_timeS()", "INKEY$": "tb_inkey()"}

# variable C types by TB suffix: (c type, mangle prefix, zero)
_VTYPES = {
    "NUM": ("float", "f_", "0"),
    "SGL": ("float", "f_", "0"),
    "INT": ("short", "i_", "0"),
    "LNG": ("int", "l_", "0"),  # TB `&` long: 32-bit signed
    "DBL": ("double", "d_", "0"),
    "STR": ("char *", "s_", '""'),
}
# store conversion applied on assignment, per TB variable type
_STORE_CAST = {
    "NUM": "(float)({0})",
    "SGL": "(float)({0})",
    "INT": "(short)tb_cint({0})",
    "LNG": "(int)tb_cint({0})",
    "DBL": "({0})",
}

_INT_BINOPS = {"\\": "tb_idiv", "MOD": "tb_mod", "AND": "tb_and", "OR": "tb_or", "XOR": "tb_xor"}


def _suffix_ty(name: str) -> str:
    return {"%": "INT", "&": "LNG", "!": "SGL", "#": "DBL", "$": "STR"}.get(name[-1], "NUM")


def _base(name: str) -> str:
    return name.rstrip("%&!#$")


def _cstr(s: str) -> str:
    out = ['"']
    for ch in s:
        if ch in '"\\':
            out.append("\\" + ch)
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            out.append(f'\\{ord(ch):03o}')
    out.append('"')
    return "".join(out)


class _Raw:
    """A pre-rendered C fragment standing in for an Expr in assign()."""

    def __init__(self, code: str, is_str: bool):
        self.code = code
        self.is_str = is_str


def _is_str(e) -> bool:
    if isinstance(e, _Raw):
        return e.is_str
    if isinstance(e, ir.StrLit):
        return True
    if isinstance(e, (ir.Var, ir.ArrayRef, ir.Call, ir.FnCall, ir.Nullary)):
        return e.name.endswith("$")
    if isinstance(e, ir.BinOp) and e.op == "+":
        return _is_str(e.lhs)
    if isinstance(e, ir.Group):
        return _is_str(e.inner)
    return False


class _Unsupported(ValueError):
    pass


class _Gen:
    """One translation: collects declarations while rendering the body."""

    def __init__(self, stmts):
        self.stmts = list(stmts)
        self.orig_lines = getattr(stmts, "lines", None)
        self.vars: dict[str, str] = {}  # mangled -> C declaration
        # name -> (ty, dims, rank); dims is a tuple of (lo, hi) int pairs for a
        # compile-time DIM, or None for a runtime (variable-bound) DIM
        self.arrays: dict[str, tuple[str, tuple[tuple[int, int], ...] | None, int]] = {}
        self.option_base = 0  # current OPTION BASE for int-bound DIMs
        self.fns: list[str] = []  # hoisted inline DEF FN definitions
        self.fn_names: set[str] = set()
        self.data: list[tuple[str, bool]] = []
        self.data_offset: dict[int, int] = {}  # top-level stmt index -> data cursor
        self.labels: set[int] = set()
        self.n = 0  # unique-label counter
        self.params: dict[str, str] = {}  # active DEF FN / SUB param name -> C lvalue
        self.subs: dict[str, tuple[str, ...]] = {}  # SUB name -> params
        self.in_sub = False
        self.in_def = False  # inside a multi-line DEF FN body
        self.uses_eh = False  # ON ERROR / RESUME / ERROR / ERR / ERL present
        self.uses_timer = False  # ON TIMER present: poll at statement boundaries
        self.uses_clear = False  # CLEAR / RUN present: generate tb_clear_all()

    def uid(self) -> int:
        self.n += 1
        return self.n

    # --- naming / declarations ---

    def var(self, name: str) -> str:
        if name in self.params:
            return self.params[name]
        if self.in_sub:
            # no corpus witness pins TB's local/shared default for SUB-body
            # variables, so only parameters are allowed inside a SUB for now
            raise _Unsupported(f"non-parameter variable {name} in SUB")
        cty, pre, zero = _VTYPES[_suffix_ty(name)]
        m = pre + _base(name)
        self.vars.setdefault(m, f"static {cty}{'' if cty.endswith('*') else ' '}{m} = {zero};")
        return m

    def array(self, name: str, rank: int):
        if name not in self.arrays:
            self.dim_array(name, (10,) * rank)  # implicit DIM x(10[,10])
        return self.arrays[name]

    def dim_array(self, name: str, bounds) -> list[str]:
        """Register array `name`; returns the allocation code (empty when static).

        Each DIM bound is an int upper bound (lower comes from OPTION BASE), an
        explicit `(lo, hi)` pair (`DIM A(0:4)`), or Exprs for runtime bounds."""
        rank = len(bounds)
        if rank > 2:
            raise _Unsupported("DIM rank > 2")
        ty = _suffix_ty(name)
        norm = [b if isinstance(b, tuple) else (self.option_base, b) for b in bounds]
        if all(isinstance(lo, int) and isinstance(hi, int) for lo, hi in norm):
            self.arrays[name] = (ty, tuple(norm), rank)
            return []
        # runtime bounds: heap allocation at the DIM statement
        self.arrays[name] = (ty, None, rank)
        _, pre, _ = _VTYPES[ty]
        m = "a" + pre + _base(name)
        code = []
        for k, (lo, hi) in enumerate(norm, 1):
            lo_c = str(lo) if isinstance(lo, int) else f"(long)tb_cint({self.num(lo)})"
            hi_c = str(hi) if isinstance(hi, int) else f"(long)tb_cint({self.num(hi)})"
            code.append(f"{m}_lo{k} = {lo_c}; {m}_n{k} = {hi_c} - {m}_lo{k} + 1;")
        total = " * ".join(f"{m}_n{k}" for k in range(1, rank + 1))
        code.append(f"{m} = tb_calloc({total}, sizeof *{m});")
        return code

    # --- expressions ---

    def num(self, e) -> str:
        """Render e as a C double-valued expression."""
        if isinstance(e, _Raw):
            return e.code
        if _is_str(e):
            raise _Unsupported(f"string expression where a number is needed: {e!r}")
        if isinstance(e, ir.Lit):
            return repr(float(e.value)) if isinstance(e.value, float) else str(e.value)
        if isinstance(e, (ir.DblLit, ir.SingleLit)):
            return repr(e.value)
        if isinstance(e, ir.HexLit):
            return f"(double)(short)0x{e.value:X}"
        if isinstance(e, ir.Var):
            return self.var(e.name)
        if isinstance(e, ir.ArrayRef):
            return self.aref(e)
        if isinstance(e, ir.Neg):
            return f"(-({self.num(e.operand)}))"
        if isinstance(e, ir.Not):
            return f"tb_not({self.num(e.operand)})"
        if isinstance(e, ir.Group):
            return f"({self.num(e.inner)})"
        if isinstance(e, (ir.Err, ir.Erl)):
            return "(double)tb_err" if isinstance(e, ir.Err) else "(double)tb_erl"
        if isinstance(e, ir.VarSeg):
            return "0.0"  # a real-mode segment; no modern counterpart
        if isinstance(e, ir.BinOp):
            if e.op == "/":
                return f"tb_div({self.num(e.lhs)}, {self.num(e.rhs)})"
            if e.op in "+-*":
                return f"({self.num(e.lhs)} {e.op} {self.num(e.rhs)})"
            if e.op == "^":
                return f"pow({self.num(e.lhs)}, {self.num(e.rhs)})"
            if e.op in _INT_BINOPS:
                return f"{_INT_BINOPS[e.op]}({self.num(e.lhs)}, {self.num(e.rhs)})"
            if e.op in ("=", "<>", "<", "<=", ">", ">="):
                # comparison in value position: TB truth is -1/0
                return f"({self.cond(ir.RelOp(e.op, e.lhs, e.rhs))} ? -1.0 : 0.0)"
            raise _Unsupported(f"operator {e.op}")
        if isinstance(e, (ir.RelOp, ir.LogOp)):
            return f"({self.cond(e)} ? -1.0 : 0.0)"  # TB truth value
        if isinstance(e, ir.Call):
            if e.name in ("UBOUND", "LBOUND"):
                return self.bound(e)
            return self.call(e, _NUM_FUNCS)
        if isinstance(e, ir.FnCall):
            return self.fncall(e)
        if isinstance(e, ir.Nullary):
            if e.name in _NULLARY:
                return _NULLARY[e.name]
            raise _Unsupported(f"intrinsic {e.name}")
        raise _Unsupported(f"expression {type(e).__name__}")

    def _nullary_str(self, e) -> str:
        if e.name in _NULLARY_STR:
            return _NULLARY_STR[e.name]
        raise _Unsupported(f"string intrinsic {e.name}")

    def s(self, e) -> str:
        """Render e as a C char*-valued expression."""
        if isinstance(e, _Raw):
            return e.code
        if isinstance(e, ir.StrLit):
            return _cstr(e.value)
        if isinstance(e, ir.Var):
            return self.var(e.name)
        if isinstance(e, ir.ArrayRef):
            return self.aref(e)
        if isinstance(e, ir.Group):
            return f"({self.s(e.inner)})"
        if isinstance(e, ir.BinOp) and e.op == "+":
            return f"tb_cat({self.s(e.lhs)}, {self.s(e.rhs)})"
        if isinstance(e, ir.Call):
            return self.call(e, _STR_FUNCS)
        if isinstance(e, ir.Nullary):
            return self._nullary_str(e)
        raise _Unsupported(f"string expression {type(e).__name__}")

    def call(self, e, table) -> str:
        # arity-keyed template; each arg renders by its own inferred type
        key = (e.name, len(e.args))
        if key not in table:
            raise _Unsupported(f"intrinsic {e.name}/{len(e.args)}")
        args = [self.s(a) if _is_str(a) else self.num(a) for a in e.args]
        return table[key].format(*args)

    def opt(self, e) -> tuple[str, str]:
        """(has_flag, value) C argument pair for an optional numeric operand."""
        return ("1", self.num(e)) if e is not None else ("0", "0")

    def acap(self, name: str) -> tuple[str, str]:
        """(buffer, capacity-in-bytes) C expressions for a blit array."""
        ty, dims, rank = self.array(name, 1)
        if ty == "STR":
            raise _Unsupported("GET/PUT on a string array")
        _, pre, _ = _VTYPES[ty]
        m = "a" + pre + _base(name)
        if dims is not None:
            return m, f"(long)sizeof {m}"
        n = " * ".join(f"{m}_n{k}" for k in range(1, rank + 1))
        return m, f"({n}) * (long)sizeof *{m}"

    def bound(self, e) -> str:
        # UBOUND(A(k)) / LBOUND(A(k)): the "index" is the dimension number
        (arg,) = e.args
        if not (isinstance(arg, ir.ArrayRef) and isinstance(arg.indices[0], ir.Lit)):
            raise _Unsupported(f"{e.name} with a non-constant dimension")
        k = int(arg.indices[0].value)
        ty, dims, rank = self.array(arg.name, 1)
        if not 1 <= k <= rank:
            raise _Unsupported(f"{e.name} dimension {k} of rank-{rank} array")
        _, pre, _ = _VTYPES[ty]
        m = "a" + pre + _base(arg.name)
        if dims is not None:
            lo, hi = dims[k - 1]
            return f"{lo if e.name == 'LBOUND' else hi}.0"
        if e.name == "LBOUND":
            return f"(double){m}_lo{k}"
        return f"(double)({m}_lo{k} + {m}_n{k} - 1)"

    def fncall(self, e) -> str:
        if e.name.endswith("$"):
            raise _Unsupported("string DEF FN")
        if e.name not in self.fn_names:
            raise _Unsupported(f"call to undefined {e.name}")
        return f"fn_{_base(e.name)}({', '.join(self.num(a) for a in e.args)})"

    def aref(self, e) -> str:
        if self.in_sub:
            raise _Unsupported("array access inside SUB (no SHARED witness)")
        ty, dims, rank = self.array(e.name, len(e.indices))
        if rank != len(e.indices):
            raise _Unsupported(f"rank mismatch on array {e.name}")
        _, pre, _ = _VTYPES[ty]
        m = "a" + pre + _base(e.name)
        idx = []
        for k, i in enumerate(e.indices, 1):
            lo = str(dims[k - 1][0]) if dims is not None else f"{m}_lo{k}"
            idx.append(f"((long)tb_cint({self.num(i)}) - {lo})")
        if rank == 1:
            return f"{m}[{idx[0]}]"
        stride = (
            str(dims[1][1] - dims[1][0] + 1) if dims is not None else f"{m}_n2"
        )
        return f"{m}[({idx[0]}) * {stride} + ({idx[1]})]"

    def cond(self, e) -> str:
        if isinstance(e, ir.RelOp):
            op = {"=": "==", "<>": "!="}.get(e.op, e.op)
            if _is_str(e.lhs) or _is_str(e.rhs):
                return f"(strcmp(tb_s({self.s(e.lhs)}), tb_s({self.s(e.rhs)})) {op} 0)"
            return f"({self.num(e.lhs)} {op} {self.num(e.rhs)})"
        if isinstance(e, ir.LogOp):
            c = "&&" if e.op == "AND" else "||"
            return f"({self.cond(e.lhs)} {c} {self.cond(e.rhs)})"
        # numeric-valued condition: TB nonzero = true
        return f"({self.num(e)} != 0)"

    # --- statements ---

    def assign(self, target, value) -> str:
        if isinstance(target, ir.Var):
            dst, ty = self.var(target.name), _suffix_ty(target.name)
        elif isinstance(target, ir.ArrayRef):
            dst, ty = self.aref(target), self.array(target.name, len(target.indices))[0]
        else:
            raise _Unsupported(f"assign target {type(target).__name__}")
        if ty == "STR":
            return f"{dst} = {self.s(value)};"
        return f"{dst} = {_STORE_CAST[ty].format(self.num(value))};"

    def gen_print(self, s) -> list[str]:
        out = []
        if s.file is not None:
            out.append(f"tb_out = tb_file({s.file}); tb_ch = {s.file};")
        for item in s.items:
            if isinstance(item, ir.Call) and item.name in ("TAB", "SPC"):
                out.append(f"tb_{item.name.lower()}({self.num(item.args[0])});")
            elif _is_str(item):
                out.append(f"tb_ps(tb_s({self.s(item)}));")
            else:
                out.append(f"tb_pn({self.num(item)});")
        if s.newline:
            out.append("tb_nl();")
        if s.file is not None:
            out.append("tb_out = stdout; tb_ch = 0;")
        return out

    def gen_write(self, s) -> list[str]:
        out = []
        if s.file is not None:
            out.append(f"tb_out = tb_file({s.file}); tb_ch = {s.file};")
        for k, item in enumerate(s.items):
            if k:
                out.append('tb_ps(",");')
            if _is_str(item):
                out.append(f"tb_wstr({self.s(item)});")
            else:
                out.append(f"tb_wnum({self.num(item)});")
        out.append("tb_nl();")
        if s.file is not None:
            out.append("tb_out = stdout; tb_ch = 0;")
        return out

    def gen_body(self, body, loops) -> list[str]:
        out = []
        i = 0
        body = list(body)
        while i < len(body):
            out.extend(self.gen(body[i], loops, None))
            i += 1
        return out

    def gen(self, s, loops, idx) -> list[str]:
        """C lines for one statement. `loops` is the open FOR/DO/WHILE label stack
        (shared across nesting so flat FOR..NEXT pairs match); `idx` is the
        top-level statement index or None inside a block body."""
        if (self.in_sub or self.in_def) and isinstance(
            s,
            (ir.Goto, ir.IfGoto, ir.Gosub, ir.Return, ir.OnGoto, ir.OnGosub,
             ir.OnError, ir.Resume),
        ):
            raise _Unsupported(f"{type(s).__name__} inside a procedure (targets main labels)")
        if isinstance(s, ir.FnResult):
            if not self.in_def:
                raise _Unsupported("FN result store outside DEF FN")
            return [f"fn_result = {self.num(s.value)};"]
        if isinstance(s, ir.ExitDef):
            if not self.in_def:
                raise _Unsupported("EXIT DEF outside DEF FN")
            return ["return fn_result;"]
        if isinstance(s, ir.Assign):
            return [self.assign(s.target, s.value)]
        if isinstance(s, ir.Print):
            return self.gen_print(s)
        if isinstance(s, ir.Write):
            return self.gen_write(s)
        if isinstance(s, ir.End):
            return ["exit(0);"]
        if isinstance(s, (ir.Tron, ir.Troff)):
            return []
        if isinstance(s, ir.Goto):
            return [f"goto L{s.target};"]
        if isinstance(s, ir.IfGoto):
            return [f"if {self.cond(s.cond)} goto L{s.target};"]
        if isinstance(s, ir.Gosub):
            n = self.uid()
            return [f"tb_gstack[tb_gsp++] = &&R{n}; goto L{s.target}; R{n}:;"]
        if isinstance(s, ir.Return):
            return ["goto *tb_gstack[--tb_gsp];"]
        if isinstance(s, ir.OnGoto) or isinstance(s, ir.OnGosub):
            n = self.uid()
            lines = [f"switch ((int)tb_cint({self.num(s.selector)})) {{"]
            for k, t in enumerate(s.targets, 1):
                if isinstance(s, ir.OnGoto):
                    lines.append(f"case {k}: goto L{t};")
                else:
                    lines.append(f"case {k}: tb_gstack[tb_gsp++] = &&R{n}; goto L{t};")
            lines.append("}")
            if isinstance(s, ir.OnGosub):
                lines.append(f"R{n}:;")
            return lines
        if isinstance(s, ir.For):
            n = self.uid()
            v = self.var(s.var.name)
            lim, st = f"tb_lim{n}", f"tb_st{n}"
            self.vars[lim] = f"static double {lim} = 0;"
            self.vars[st] = f"static double {st} = 0;"
            loops.append(("FOR", n, s.var.name))
            return [
                self.assign(s.var, s.init),
                f"{lim} = {self.num(s.limit)}; {st} = {self.num(s.step)};",
                f"FCHK{n}: if (!({st} >= 0 ? {v} <= {lim} : {v} >= {lim})) goto FDONE{n};",
            ]
        if isinstance(s, ir.NextStmt):
            for j in range(len(loops) - 1, -1, -1):
                if loops[j][0] == "FOR" and loops[j][2] == s.var.name:
                    _, n, _ = loops.pop(j)
                    v = self.var(s.var.name)
                    cast = _STORE_CAST[_suffix_ty(s.var.name)]
                    stv = f"{v} = {cast.format(f'{v} + tb_st{n}')};"
                    return [stv, f"goto FCHK{n};", f"FDONE{n}:;"]
            raise _Unsupported(f"NEXT {s.var.name} without open FOR")
        if isinstance(s, ir.While):
            n = self.uid()
            loops.append(("WHILE", n, None))
            return [f"WTOP{n}: if (!{self.cond(s.cond)}) goto WDONE{n};"]
        if isinstance(s, ir.Wend):
            for j in range(len(loops) - 1, -1, -1):
                if loops[j][0] == "WHILE":
                    _, n, _ = loops.pop(j)
                    return [f"goto WTOP{n};", f"WDONE{n}:;"]
            raise _Unsupported("WEND without open WHILE")
        if isinstance(s, ir.Do):
            n = self.uid()
            loops.append(("DO", n, None))
            top = [f"DTOP{n}:;"]
            if s.kind == "WHILE":
                top.append(f"if (!{self.cond(s.cond)}) goto DDONE{n};")
            elif s.kind == "UNTIL":
                top.append(f"if {self.cond(s.cond)} goto DDONE{n};")
            return top
        if isinstance(s, ir.Loop):
            for j in range(len(loops) - 1, -1, -1):
                if loops[j][0] == "DO":
                    _, n, _ = loops.pop(j)
                    if s.kind == "WHILE":
                        return [f"if {self.cond(s.cond)} goto DTOP{n};", f"DDONE{n}:;"]
                    if s.kind == "UNTIL":
                        return [f"if (!{self.cond(s.cond)}) goto DTOP{n};", f"DDONE{n}:;"]
                    return [f"goto DTOP{n};", f"DDONE{n}:;"]
            raise _Unsupported("LOOP without open DO")
        if isinstance(s, ir.ExitFor):
            for kind, n, _ in reversed(loops):
                if kind == "FOR":
                    return [f"goto FDONE{n};"]
            raise _Unsupported("EXIT FOR outside FOR")
        if isinstance(s, ir.ExitLoop):
            for kind, n, _ in reversed(loops):
                if kind == "DO":
                    return [f"goto DDONE{n};"]
            raise _Unsupported("EXIT LOOP outside DO")
        if isinstance(s, ir.IfInline):
            return [f"if {self.cond(s.cond)} {{", *self.gen_body(s.body, loops), "}"]
        if isinstance(s, ir.IfBlock):
            lines = []
            for k, (cond, body) in enumerate(s.arms):
                kw = "if" if k == 0 else "} else if"
                lines.append(f"{kw} {self.cond(cond)} {{")
                lines.extend(self.gen_body(body, loops))
            if s.else_body is not None:
                lines.append("} else {")
                lines.extend(self.gen_body(s.else_body, loops))
            lines.append("}")
            return lines
        if isinstance(s, ir.SelectCase):
            n = self.uid()
            is_str = _is_str(s.selector)
            sel = f"tb_sel{n}"
            self.vars[sel] = f"static {'char *' if is_str else 'double '}{sel} = {'0' if is_str else '0'};"
            lines = [f"{sel} = {self.s(s.selector) if is_str else self.num(s.selector)};"]

            def guard(g) -> str:
                if isinstance(g, ir.CaseValue):
                    if is_str:
                        return f"(strcmp(tb_s({sel}), tb_s({self.s(g.value)})) == 0)"
                    return f"({sel} == {self.num(g.value)})"
                if isinstance(g, ir.CaseRange):
                    if is_str:
                        return (
                            f"(strcmp(tb_s({sel}), tb_s({self.s(g.lo)})) >= 0 && "
                            f"strcmp(tb_s({sel}), tb_s({self.s(g.hi)})) <= 0)"
                        )
                    return f"({sel} >= {self.num(g.lo)} && {sel} <= {self.num(g.hi)})"
                if isinstance(g, ir.CaseIs):
                    op = {"=": "==", "<>": "!="}.get(g.op, g.op)
                    if is_str:
                        return f"(strcmp(tb_s({sel}), tb_s({self.s(g.value)})) {op} 0)"
                    return f"({sel} {op} {self.num(g.value)})"
                raise _Unsupported(f"case guard {type(g).__name__}")

            for k, arm in enumerate(s.arms):
                kw = "if" if k == 0 else "} else if"
                lines.append(f"{kw} ({' || '.join(guard(g) for g in arm.guards)}) {{")
                lines.extend(self.gen_body(arm.body, loops))
            if s.case_else is not None:
                lines.append("} else {")
                lines.extend(self.gen_body(s.case_else, loops))
            lines.append("}")
            return lines
        if isinstance(s, ir.Dim):
            out = []
            for name, bounds in ((s.name, s.bounds), *s.also):
                out.extend(self.dim_array(name, bounds))
            return out
        if isinstance(s, ir.OptionBase):
            self.option_base = s.n  # lower bound of subsequent int-bound DIMs
            return []
        if isinstance(s, ir.Data):
            if idx is not None:
                self.data_offset[idx] = len(self.data)
            self.data.extend((it.text, it.is_str) for it in s.items)
            return []
        if isinstance(s, ir.Read):
            out = []
            for t in s.targets:
                ty = (
                    _suffix_ty(t.name)
                    if isinstance(t, (ir.Var, ir.ArrayRef))
                    else "NUM"
                )
                src = (
                    "tb_dup(tb_data[tb_data_p++])"
                    if ty == "STR"
                    else "tb_val(tb_data[tb_data_p++])"
                )
                out.append(self.assign(t, _Raw(src, ty == "STR")))
            return out
        if isinstance(s, ir.Restore):
            off = 0 if s.target is None else self.data_offset.get(s.target)
            if off is None:
                raise _Unsupported("RESTORE to a non-DATA statement")
            return [f"tb_data_p = {off};"]
        if isinstance(s, ir.Input):
            fn = "tb_input_str" if _suffix_ty(s.var.name) == "STR" else "tb_input_num"
            prompt = _cstr(s.prompt.value) if s.prompt is not None else "NULL"
            mark = "0" if (s.prompt is not None and s.comma) else "1"
            return [self.assign(s.var, _Raw(f"{fn}({prompt}, {mark})", fn.endswith("str")))]
        if isinstance(s, ir.LineInput):
            prompt = _cstr(s.prompt.value) if s.prompt is not None else "NULL"
            return [self.assign(s.var, _Raw(f"tb_input_str({prompt}, 0)", True))]
        if isinstance(s, ir.Swap):
            a, b = self.var(s.a.name), self.var(s.b.name)
            ta, tb_ = _suffix_ty(s.a.name), _suffix_ty(s.b.name)
            if ta != tb_:
                raise _Unsupported("SWAP across types")
            cty, _, _ = _VTYPES[ta]
            return [f"{{ {cty} t = {a}; {a} = {b}; {b} = t; }}"]
        if isinstance(s, ir.Beep):
            return ['tb_ps("\\a");']
        if isinstance(s, ir.Cls):
            return [
                'tb_esc("\\033[2J\\033[H"); tb_cols[0] = 0; tb_row = 0;',
                "if (tb_fb) memset(tb_fb, 0, (size_t)tb_gw * tb_gh);",
            ]
        if isinstance(s, ir.Delay):
            return [f"tb_delay({self.num(s.secs)});"]
        if isinstance(s, ir.Randomize):
            return [f"srand((unsigned)tb_i({self.num(s.seed)}));"]
        if isinstance(s, ir.MidAssign):
            tgt = self.var(s.target.name)
            n = self.uid()
            return [
                f"{{ char *t{n} = tb_dup(tb_s({tgt})); const char *m{n} = tb_s({self.s(s.source)});",
                f"  long p{n} = tb_i({self.num(s.start)}) - 1, L{n} = (long)strlen(t{n});",
                f"  for (long k{n} = 0; m{n}[k{n}] && p{n} + k{n} < L{n}; k{n}++) t{n}[p{n} + k{n}] = m{n}[k{n}];",
                f"  {tgt} = t{n}; }}",
            ]
        if isinstance(s, ir.DefFn):
            self.gen_deffn(s)
            return []
        if isinstance(s, ir.SubDef):
            self.gen_subdef(s)
            return []
        if isinstance(s, ir.CallStmt):
            return self.gen_call(s)
        if isinstance(s, ir.ExitSub):
            if not self.in_sub:
                raise _Unsupported("EXIT SUB outside SUB")
            return ["return;"]
        if isinstance(s, ir.Open):
            if s.mode.value.upper() == "R":
                return [f"tb_open_r({s.num}, {self.s(s.file)});"]
            mode = {"I": '"r"', "O": '"w"', "A": '"a"'}.get(s.mode.value.upper())
            if mode is None:
                raise _Unsupported(f"OPEN mode {s.mode.value!r}")
            return [f"tb_open({mode}, {s.num}, {self.s(s.file)});"]
        if isinstance(s, ir.Field):
            out = [f"tb_field_start({s.num});"]
            for w, v in s.fields:
                out.append(
                    f"tb_field_reg({s.num}, &{self.var(v.name)}, tb_i({self.num(w)}));"
                )
            return out
        if isinstance(s, (ir.Lset, ir.Rset)):
            right = int(isinstance(s, ir.Rset))
            return [f"tb_lsetrset(&{self.var(s.target.name)}, {self.s(s.source)}, {right});"]
        if isinstance(s, ir.Get):
            return [f"tb_getrec({s.num}, {self.num(s.pos)});"]
        if isinstance(s, ir.Put):
            return [f"tb_putrec({s.num}, {self.num(s.pos)});"]
        if isinstance(s, ir.Seek):
            return [f"fseek(tb_file({s.num}), (long)tb_i({self.num(s.pos)}) - 1, SEEK_SET);"]
        if isinstance(s, ir.Close):
            return [f"tb_close({s.num});"]
        if isinstance(s, ir.Reset):
            return ["tb_reset();"]
        if isinstance(s, ir.InputFile):
            out = []
            for t in s.vars:
                is_s = _suffix_ty(t.name) == "STR"
                fn = "tb_finput_str" if is_s else "tb_finput_num"
                out.append(self.assign(t, _Raw(f"{fn}({s.num})", is_s)))
            return out
        if isinstance(s, ir.OnError):
            if s.target is None:
                return ["tb_handler = 0;"]
            self.labels.add(s.target)
            return [f"tb_handler = &&L{s.target};"]
        if isinstance(s, ir.Resume):
            if s.target is not None:
                self.labels.add(s.target)
                return [f"goto L{s.target};"]
            return ["goto *tb_next;" if s.next_ else "goto *tb_stmt;"]
        if isinstance(s, ir.ErrorStmt):
            return [f"tb_error((int)tb_cint({self.num(s.code)}));"]
        if isinstance(s, ir.Erase):
            ty, dims, rank = self.array(s.name, 1)
            _, pre, _ = _VTYPES[ty]
            m = "a" + pre + _base(s.name)
            if dims is not None:
                return [f"memset({m}, 0, sizeof {m});"]
            return [f"free({m}); {m} = 0;"]
        if isinstance(s, ir.Key):
            return []  # soft-key display line: no modern-terminal counterpart
        if isinstance(s, ir.Locate):
            out = [f"tb_locate({self.num(s.row)}, {self.num(s.col)});"]
            if s.cursor is not None:
                out.append(
                    f'tb_ps(tb_i({self.num(s.cursor)}) ? "\\033[?25h" : "\\033[?25l");'
                )
            return out
        if isinstance(s, ir.Color):
            fg = self.num(s.fg) if s.fg is not None else "0"
            bg = self.num(s.bg) if s.bg is not None else "0"
            has_fg = "1" if s.fg is not None else "0"
            has_bg = "1" if s.bg is not None else "0"
            return [f"tb_color({has_fg}, {fg}, {has_bg}, {bg});"]
        if isinstance(s, ir.Shell):
            return [f"if (system({self.s(s.cmd)})) {{}}"]
        if isinstance(s, ir.Chdir):
            return [f"if (chdir({self.s(s.path)})) {{}}"]
        if isinstance(s, ir.Environ):
            return [f"putenv(tb_dup({self.s(s.s)}));"]
        if isinstance(s, ir.Kill):
            return [f"remove({self.s(s.file)});"]
        if isinstance(s, ir.Name):
            return [f"rename({self.s(s.old)}, {self.s(s.new)});"]
        if isinstance(s, ir.Files):
            return [f"tb_files_({self.s(s.spec)});"]
        if isinstance(s, ir.DateTimeSet):
            fn = "tb_set_date" if s.name == "DATE$" else "tb_set_time"
            return [f"{fn}({self.s(s.value)});"]
        if isinstance(s, ir.Screen):
            return [f"tb_screen({self.num(s.mode)});"]
        if isinstance(s, ir.Pset):
            hc, c = self.opt(s.color)
            return [
                f"tb_pset({self.num(s.x)}, {self.num(s.y)}, {int(s.step)}, "
                f"{hc}, {c}, {int(s.preset)});"
            ]
        if isinstance(s, ir.LineStmt):
            hc, c = self.opt(s.color)
            style = (
                f"(unsigned)tb_i({self.num(s.style)})" if s.style is not None else "0xFFFFu"
            )
            return [
                f"tb_linestmt({self.num(s.x1)}, {self.num(s.y1)}, {int(s.step1)}, "
                f"{self.num(s.x2)}, {self.num(s.y2)}, {int(s.step2)}, "
                f"{hc}, {c}, {int(s.box != '')}, {int(s.box == 'BF')}, {style});"
            ]
        if isinstance(s, ir.Circle):
            hc, c = self.opt(s.color)
            sa = self.num(s.start) if s.start is not None else "0"
            ea = self.num(s.end) if s.end is not None else "0"
            asp = self.num(s.aspect) if s.aspect is not None else "-1"
            return [
                f"tb_circle({self.num(s.x)}, {self.num(s.y)}, {self.num(s.r)}, "
                f"{int(s.step)}, {hc}, {c}, {sa}, {ea}, {asp});"
            ]
        if isinstance(s, ir.Paint):
            hp, p = self.opt(s.paint)
            hb, b = self.opt(s.border)
            return [f"tb_paint({self.num(s.x)}, {self.num(s.y)}, {hp}, {p}, {hb}, {b});"]
        if isinstance(s, ir.GetGfx):
            m, cap = self.acap(s.array)
            return [
                f"tb_getgfx({m}, {cap}, {self.num(s.x1)}, {self.num(s.y1)}, "
                f"{self.num(s.x2)}, {self.num(s.y2)});"
            ]
        if isinstance(s, ir.PutGfx):
            try:
                action = {None: 0, "XOR": 0, "PSET": 1, "PRESET": 2, "AND": 3, "OR": 4}[
                    s.action
                ]
            except KeyError:
                raise _Unsupported(f"PUT action {s.action}") from None
            m, cap = self.acap(s.array)
            return [f"tb_putgfx({m}, {cap}, {self.num(s.x)}, {self.num(s.y)}, {action});"]
        if isinstance(s, ir.View):
            hc, c = self.opt(s.color)
            hb, b = self.opt(s.border)
            return [
                f"tb_view(1, {self.num(s.x1)}, {self.num(s.y1)}, {self.num(s.x2)}, "
                f"{self.num(s.y2)}, {int(s.screen)}, {hc}, {c}, {hb}, {b});"
            ]
        if isinstance(s, ir.Window):
            return [
                f"tb_window(1, {self.num(s.x1)}, {self.num(s.y1)}, {self.num(s.x2)}, "
                f"{self.num(s.y2)}, {int(s.screen)});"
            ]
        if isinstance(s, ir.Draw):
            return [f"tb_draw({self.s(s.cmd)});"]
        if isinstance(s, ir.OnTrap):
            if s.event == "TIMER":
                return [
                    f"tb_timer_hdl = &&L{s.target}; tb_timer_iv = {self.num(s.n)}; "
                    "tb_timer_due_at = tb_mono() + tb_timer_iv;"
                ]
            # COM/KEY/PEN/PLAY have no event source on a modern host: the
            # handler is installable but can never fire, so installing is a no-op
            return [f"/* ON {s.event} GOSUB: no {s.event} event source on this host */"]
        if isinstance(s, ir.TrapCtl):
            if s.event == "TIMER":
                if s.mode == "ON":
                    return ["tb_timer_on = 1; tb_timer_due_at = tb_mono() + tb_timer_iv;"]
                return ["tb_timer_on = 0;"]
            return [f"/* {s.event} {s.mode}: no {s.event} event source on this host */"]
        if isinstance(s, ir.Clear):
            self.uses_clear = True
            return ["tb_clear_all();"]
        if isinstance(s, ir.Run):
            self.uses_clear = True
            out = ["tb_clear_all();"]
            if self.data:
                out.append("tb_data_p = 0;")
            out.append("goto L0;")
            return out
        if isinstance(s, ir.Palette):
            return [f"tb_pal[tb_i({self.num(s.attr)}) & 15] = (int)tb_i({self.num(s.color)}) & 15;"]
        if isinstance(s, ir.Mtimer):
            return ["tb_mt0 = tb_mono();"]
        if isinstance(s, ir.Lprint):
            # no printer on a modern host: LPRINT falls back to the console
            return self.gen_print(ir.Print(items=s.items, newline=s.newline))
        if isinstance(s, ir.PrintUsing):
            out = []
            if s.file is not None:
                out.append(f"tb_out = tb_file({s.file}); tb_ch = {s.file};")
            out.append(f"tb_pu_begin({self.s(s.fmt)});")
            out.extend(f"tb_pu_val({self.num(v)});" for v in s.values)
            if s.newline:
                out.append("tb_nl();")
            if s.file is not None:
                out.append("tb_out = stdout; tb_ch = 0;")
            return out
        if isinstance(s, ir.Mkdir):
            return [f"if (mkdir({self.s(s.path)}, 0777)) {{}}"]
        if isinstance(s, ir.Rmdir):
            return [f"if (rmdir({self.s(s.path)})) {{}}"]
        if isinstance(s, (ir.KeyList, ir.Play, ir.Sound, ir.Width)):
            # no soft-key display, audio device, or fixed-width console here
            return [f"/* {type(s).__name__}: no device counterpart on this host */"]
        raise _Unsupported(f"statement {type(s).__name__}")

    def gen_deffn(self, s) -> None:
        if s.name.endswith("$") or any(p.endswith("$") for p in s.params):
            raise _Unsupported("string DEF FN")
        old = self.params
        self.params = {p: f"p_{_base(p)}" for p in s.params}
        args = ", ".join(f"double p_{_base(p)}" for p in s.params) or "void"
        try:
            if not s.is_block:
                body = self.num(s.body)
                self.fns.append(
                    f"static double fn_{_base(s.name)}({args}) {{ return {body}; }}"
                )
            else:
                self.in_def = True
                try:
                    lines = self.gen_body(s.body, [])
                finally:
                    self.in_def = False
                self.fns.append(
                    "\n".join(
                        [
                            f"static double fn_{_base(s.name)}({args}) {{",
                            "    double fn_result = 0;",
                            *("    " + ln for ln in lines),
                            "    return fn_result;",
                            "}",
                        ]
                    )
                )
        finally:
            self.params = old
        self.fn_names.add(s.name)

    def gen_subdef(self, s) -> None:
        if self.in_sub:
            raise _Unsupported("nested SUB")
        self.subs[s.name] = s.params
        old = self.params
        self.params = {p: f"(*p_{_base(p)})" for p in s.params}
        self.in_sub = True
        try:
            body = self.gen_body(s.body, [])
        finally:
            self.in_sub = False
            self.params = old
        sig = []
        for p in s.params:
            cty, _, _ = _VTYPES[_suffix_ty(p)]
            sig.append(f"{cty}{'' if cty.endswith('*') else ' '}*p_{_base(p)}")
        head = f"static void sub_{_base(s.name)}({', '.join(sig) or 'void'}) {{"
        self.fns.append("\n".join([head, *("    " + ln for ln in body), "}"]))

    def gen_call(self, s) -> list[str]:
        if s.name not in self.subs:
            raise _Unsupported(f"CALL to unknown SUB {s.name}")
        params = self.subs[s.name]
        if len(params) != len(s.args):
            raise _Unsupported(f"CALL {s.name}: arity mismatch")
        tmps, args = [], []
        for p, a in zip(params, s.args):
            ty = _suffix_ty(p)
            # a plain variable (or array element) of matching type passes by
            # reference, TB semantics (zz_sub1); anything else by value copy
            if isinstance(a, ir.Var) and _suffix_ty(a.name) == ty:
                args.append(f"&{self.var(a.name)}")
            elif (
                isinstance(a, ir.ArrayRef)
                and not self.in_sub
                and self.array(a.name, len(a.indices))[0] == ty
            ):
                args.append(f"&{self.aref(a)}")
            else:
                cty, _, _ = _VTYPES[ty]
                t = f"t{self.uid()}"
                val = self.s(a) if ty == "STR" else _STORE_CAST[ty].format(self.num(a))
                tmps.append(f"{cty}{'' if cty.endswith('*') else ' '}{t} = {val};")
                args.append(f"&{t}")
        call = f"sub_{_base(s.name)}({', '.join(args)});"
        if tmps:
            return ["{", *tmps, call, "}"]
        return [call]

    # --- whole program ---

    def build(self) -> str:
        # collect label targets and error-handling usage across the whole tree
        def walk(node):
            if isinstance(node, (ir.Goto, ir.IfGoto, ir.Gosub)):
                if isinstance(node.target, int):
                    self.labels.add(node.target)
            if isinstance(node, (ir.OnGoto, ir.OnGosub)):
                self.labels.update(t for t in node.targets if isinstance(t, int))
            if isinstance(node, (ir.OnError, ir.Resume)):
                self.uses_eh = True
                if isinstance(node.target, int):
                    self.labels.add(node.target)
            if isinstance(node, (ir.ErrorStmt, ir.Err, ir.Erl)):
                self.uses_eh = True
            if isinstance(node, ir.OnTrap):
                if isinstance(node.target, int):
                    self.labels.add(node.target)
                if node.event == "TIMER":
                    self.uses_timer = True
            if isinstance(node, ir.Run):
                self.labels.add(0)
            for f in getattr(node, "__dataclass_fields__", ()):
                v = getattr(node, f)
                for item in v if isinstance(v, tuple) else (v,):
                    if hasattr(item, "__dataclass_fields__"):
                        walk(item)

        for st in self.stmts:
            walk(st)

        body: list[str] = []
        loops: list[tuple[str, int, str | None]] = []
        for i, st in enumerate(self.stmts):
            # ERL/tb_erl reports the emitted source's line numbers
            # (Program.lines when the error-trap table pinned them, else
            # 10, 20, ... -- the same rule emit0 applies)
            ln = self.orig_lines[i] if self.orig_lines is not None else 10 * (i + 1)
            if self.uses_eh:
                # every statement gets a label plus RESUME bookkeeping
                body.append(f"L{i}:;")
                body.append(f"tb_stmt = &&L{i}; tb_next = &&L{i + 1}; tb_erl = {ln};")
            else:
                if i in self.labels:
                    body.append(f"L{i}:;")
                body.append(f"tb_erl = {ln};")
            if self.uses_timer:
                # TB checks pending traps between statements
                body.append(
                    f"if (tb_timer_due()) {{ tb_gstack[tb_gsp++] = &&T{i}; "
                    f"goto *tb_timer_hdl; }} T{i}:;"
                )
            body.extend(self.gen(st, loops, i))
        if self.uses_eh:
            body.append(f"L{len(self.stmts)}:;")
        if loops:
            raise _Unsupported(f"unclosed loop(s): {[k for k, *_ in loops]}")

        parts = [_PRELUDE]
        if self.data:
            items = ", ".join(_cstr(t) for t, _ in self.data)
            parts.append(f"static const char *tb_data[] = {{ {items} }};")
            parts.append("static int tb_data_p = 0;")
        for name, (ty, dims, rank) in sorted(self.arrays.items()):
            cty, pre, _ = _VTYPES[ty]
            sep = "" if cty.endswith("*") else " "
            m = f"a{pre}{_base(name)}"
            if dims is not None:
                size = " * ".join(str(hi - lo + 1) for lo, hi in dims)
                parts.append(f"static {cty}{sep}{m}[{size}] = {{0}};")
            else:
                parts.append(f"static {cty}{sep}*{m} = 0;")
                for k in range(1, rank + 1):
                    parts.append(f"static long {m}_lo{k} = 0, {m}_n{k} = 0;")
        parts.extend(self.vars[k] for k in sorted(self.vars))
        if self.uses_clear:
            parts.append("static void tb_clear_all(void);")
        parts.extend(self.fns)
        parts.append("int main(void) {")
        if self.uses_eh:
            # tb_error longjmps here; the installed handler label takes over
            parts.append("    if (setjmp(tb_env)) goto *tb_handler;")
        parts.extend("    " + ln for ln in body)
        parts.append("    return 0;")
        parts.append("}")
        if self.uses_clear:
            clr = ["static void tb_clear_all(void) {", "    tb_reset();"]
            for m in sorted(self.vars):
                zero = '""' if "char *" in self.vars[m] else "0"
                clr.append(f"    {m} = {zero};")
            for name, (ty, dims, rank) in sorted(self.arrays.items()):
                _, pre, _ = _VTYPES[ty]
                m = f"a{pre}{_base(name)}"
                if dims is not None:
                    clr.append(f"    memset({m}, 0, sizeof {m});")
                else:
                    clr.append(f"    free({m}); {m} = 0;")
                    clr.extend(
                        f"    {m}_lo{k} = 0; {m}_n{k} = 0;" for k in range(1, rank + 1)
                    )
            clr.append("}")
            parts.extend(clr)
        return "\n".join(parts) + "\n"


def emit_c(stmts) -> str:
    """Typed IR statements -> a self-contained C translation unit (gcc/clang).

    Raises ValueError for programs using constructs outside the implemented
    vocabulary -- fail-loud, like the decoder."""
    return _Gen(stmts).build()
